### ISSUE TITLE
X11 grabber should be refactored to support XRender

### ISSUE THREAD

**Issue by pdf** [hyperion-project/hyperion#282]
XGetImage is extremely slow, for acceptable performance the X11 grabber should use XRender per boblight-X11 where XRender is the default, and XGetImage is a fallback for ancient systems where XRender is not supported.

**Comment by tvdzwan** [comment]
Thanks for the input. I will try and update the grabber as soon as I find some time. Do you have any references to the API of XRender?

**Comment by pdf** [comment]
@tvdzwan boblight-X11 does pretty much exactly what you want :wink:, but actually I think it might be enough just to use `XShmGetImage` when it's available.  SimpleScreenRecorder does that, and it seems fast enough: https://github.com/MaartenBaert/ssr/blob/master/src/AV/Input/X11Input.cpp

**Comment by Paulchen-Panther** [comment]
#458

**Comment by Paulchen-Panther** [comment]
#458

**Comment by brindosch** [comment]
@pdf 
Are you able to install the latest beta and report back?
https://hyperion-project.org/threads/install-latest-hyperion-beta-v1-03-0.25/

Thank you

**Comment by brindosch** [comment]
Part of V1.03.0
//Closed
