### ISSUE TITLE
Music visualization

### ISSUE THREAD

**Issue by Knoet** [hyperion-project/hyperion#3]
Hello!

First: Nice work!

Is it possible to make hyperion react to playing music?
Visualizations on RPi are not very satisfying.

**Comment by wirthual** [comment]
Hello Guys,
I also work on a music visualization for Hyperion but for Android. I inspired myself on @MarcDahlem s approch and ported it to Android. Unfortunately my Hyperion hardware didn't arrive yet :( To show you what it does i made a short Video and created a Fake-View that animates the Leds.

https://plus.google.com/102908861368834422170/posts/4grZGE64pxd

Currently it works with Google Play Music and Apollo. All you have to do is start music with one of the apps, and open the Visualizer app, then the data is send to Hyperion via WebSocket.

Can someone test it on his System?

**Comment by RanzQ** [comment]
@wirthual where can I download your app? I can test it. :)

**Comment by wirthual** [comment]
@RanzQ worte you a email :+1:

**Comment by Pitito** [comment]
I am happy to know that someone developpe this work.
I tought that I was the only one to have the idea such a program, ouf
@wirthual where can I download your app? I can test it too. :)

**Comment by RanzQ** [comment]
@wirthual I tested with both aePlayer and Google Play, didn't work. My hyperion setup should be fine since my python app can connect to it. I don't know how to debug Android apps, but I think it would be easier for you to test if you'd install hyperion to a Linux machine (if you don't own RPi). You can make it output to a file (check hyperion config) instead of a real led setup.

**Comment by adritati** [comment]
@wirthual I would like to help you test the app as well ;)

**Comment by wirthual** [comment]
@Pitito @adritati Thank you for your offer. I will make some improvements these days, then I will let you know more. Stay tuned :+1:

**Comment by wirthual** [comment]
Hello everyone,

i will release a early version "alpha" via Google Plus Community of my App "Hyperion Auvi" the next days. So if you want to help test it, feel free to ask for a invitation to the community :) Then you can easily report feedback.

https://plus.google.com/u/1/communities/116677648689142264313

@Pitito , @adritati , @RanzQ, @tociek would be glad to welcome you in the community as well :)

**Comment by MarcDahlem** [comment]
@wirthual : great that you have been able to use my work somehow.
@tociek :+1: great, that you offered a free lightberry for a runnable plugin. Didn't see it before oO
@RanzQ : do you still have the python script/plugin somewhere online accesible? It sounds for me like the best idea to perform it directly on the py. Especially the libraries for frequency analysis can best be implemented in python or c directly

**Comment by tociek** [comment]
Actually we are supposed to send the price to @RanzQ who delivered something,  that (kind of) worked ;) 
We can still offer some great discounts for other contributors or even free items as long as you'll come up with something really awesome :)

**Comment by RanzQ** [comment]
@MarcDahlem yes it's in my repo: https://github.com/RanzQ/hyperion-audio-effects
I also now own I RPi but haven't got time to test my app with it yet. I'll probably test it after I've received the lightberry ;)

I used some hours to debug a problem that makes the setup lag on a Windows machine and the problem seems to be DirectSound and Gstreamer incombatibility. So it's best to use a linux machine. Gstreamer otherwise works very good for that purpose with python. As a python effect for hyperion it didn't work though, have to run a separate python process and connect with json.

**Comment by MarcDahlem** [comment]
@tociek sure, thats fine for me. Maybe I would have spent some more hours to adapt my code to cpp or to let it run under windows, if I've seen your offer earlier :P
@RanzQ thanks for the link. I will test and maybe reuse parts of your code

**Comment by wirthual** [comment]
@MarcDahlem I think about it. Would you join developing?

**Comment by curunoir** [comment]
Hi, I have just setup a RPI with a Lightberry pack and I'm really interested in your works. I'm also a developer (mostly web) so I could give you some feedback if you want.

**Comment by wirthual** [comment]
Hi,
I released the source code here: https://github.com/wirthual/HyperionAuvi

**Comment by RanzQ** [comment]
I've experimented with FFT to octaves mapping, effect is quite nice with straight led strip but not so cool behind TV: https://www.youtube.com/watch?v=n-_0KG4EsY8

Check my repo for updated version. :)

**Comment by lenod** [comment]
"Unfortunately, this video is not available in your country because it could contain music from SME, for which we could not agree on conditions of use with GEMA. "

Thank you google!

**Comment by RanzQ** [comment]
@lenod: link to original video: http://files.webbi.in/.leds/MVI_3567.mp4

**Comment by lenod** [comment]
Thanks ;-)

**Comment by Reborn2** [comment]
Hello

Is it possible to recode hyperion and include a audio grabber like http://youtu.be/E6IvAzZ8_ws for ambi-tv ? Its running dirctly on the pi. https://github.com/gkaindl/ambi-tv

**Comment by tpmodding** [comment]
what is with that? is anybody working on it?

**Comment by giovanne123** [comment]
I was starting using RanzQ solution: https://github.com/RanzQ/hyperion-audio-effects
But used other Pi with USB Sound Card (not directly the USB Grabber) an the Mic IN is connected to my AVR Hifisystem. 
All sound coming from the AVR can be visualized 

https://github.com/RanzQ/hyperion-audio-effects/issues/9 - But now everything for my first tests is working: 
-> your audio effect python -> hyperion -> ola -> art-net-node (ESP8266-01) ;-)

**Comment by RanzQ** [comment]
After looking the ambi-tv video it looks random color effect with music playing rather than music visualization. Or maybe there's just oo much delay. :)

My solution doesn't work on Pi itself (maybe on a separate Pi 2/3) but I'm working on improvements every now and then when I've got time.

**Comment by tpmodding** [comment]
@RanzQ any updates? :)

**Comment by RanzQ** [comment]
@tpmodding I'll do some tests with OSMC today. Let's see how it goes. :)

**Comment by brindosch** [comment]
@RanzQ 
Still a noise at the loopback for kodi?

**Comment by brindosch** [comment]
@RanzQ 
I will close this issue, due to the point it is not yours and the forum might be a better place for discuss and feedback gathering.

Your thread :)
https://hyperion-project.org/threads/hyperion-music-equalizer-effekt-vu-meter.73/
