### ISSUE TITLE
Amlogic AMCODEC support

### ISSUE THREAD

**Issue by pigbait** [hyperion-project/hyperion#310]
Hey guys, I've setup my amlogic S802 android M8 box with openelec with video capture enabled in the build.

( http://freaktab.com/forum/tv-player-support/amlogic-based-tv-players/eny-acemax-em8-square-em6q-etc-devices/491016-openelec-5-0-8-eny-m8-2g-square-with-amcodec-boblightd-support-updated )

I've talked to the developer of this rom and he mentioned that Hyperion would need to add the amcodec hardware acceleration to its code.. not sure if anyone here could maybe look into it.

This is what he said: "At the moment only boblight is supported because boblight has included the hardware amcodec. My build of Openelec has enabled the amcodec to output to /dev/videocap0 so that boblight can pick it up and do its thing.

If this is the official github of hyperion https://github.com/tvdzwan/hyperion you can open an issue and ask for them to add amcodec support. You are better off asking them due to you having all the hardware that is required for hyperion."

**Comment by pigbait** [comment]
Is this possible to fix? i see the XBMC addon hasn't been updated in a long time

**Comment by brindosch** [comment]
If someone could do it, yes

**Comment by brindosch** [comment]
Please see the other issue
