### ISSUE TITLE
hyperion x11 + Kodi 17 Krypton results in flicker

### ISSUE THREAD

**Issue by meowmoo** [hyperion-project/hyperion#451]
The Api for RenderCapture changed in OE7 so Hyperion is not working properly 

see #433

**Comment by bimsarck** [comment]
```
ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <type 'exceptions.AttributeError'>
                                            Error Contents: 'xbmc.RenderCapture' object has no attribute 'waitForCaptureStateChangeEvent'
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/script.service.hyperion/addon.py", line 48, in <module>
                                                next_state = state.execute()
                                              File "/storage/.kodi/addons/script.service.hyperion/resources/lib/state.py", line 103, in execute
                                                self.__capture.waitForCaptureStateChangeEvent(200)
                                            AttributeError: 'xbmc.RenderCapture' object has no attribute 'waitForCaptureStateChangeEvent'
                                            -->End of Python script error report<--
20:16:47 T:140678252209920 WARNING: CPythonInvoker(0, /storage/.kodi/addons/script.service.hyperionon.py): the python script "/storage/.kodi/addons/script.service.hyperion/addon.py" has left several classes in memory that we couldn't clean up. The classes include: N14PythonBindings31XBMCAddon_xbmc_Monitor_DirectorE,N9XBMCAddon4xbmc6PlayerE
```

hyperion addon not working anymore from Intel Nuc. RPI is the ambilight master!

**Comment by brindosch** [comment]
A fix for kodi v17 was submitted
until merged, use this 
https://github.com/brindosch/script.service.hyperion

**Comment by meowmoo** [comment]
@brindosch 

Thanks but im using the x11 file not the addon (for lights working in menu also)

**Comment by brindosch** [comment]
Could you short explain what you mean with x11 file?

**Comment by meowmoo** [comment]
If you Start Hyperion With the x11 file, you don't need the add-on because the x11 file do the capture? I don't now how it exactly work...

But it's the only way to get lights in the kodi menu on my chromebox

**Comment by redPanther** [comment]
Perhaps @neowmoo mean he start the hyperion-x11 for capturing. Without params it streams x11 screen content via proto to local hyperiond.

**Comment by brindosch** [comment]
Kodi Krypton is at least not Alpha. If someone wants to fix it. Just could do it ;)
But i see no hurry

**Comment by brindosch** [comment]
@meowmoo 
How is your status?
Installed latest version, still the same error? on OE chromebox?

**Comment by meowmoo** [comment]
Im running latest Hyperion, but on kodi 16 at the Moment, i will try a Krypton alpha build tonight and report back

**Comment by iLLiac4** [comment]
Where are new api changes listed?

**Comment by brindosch** [comment]
Thank you for response. This is my question too :)

**Comment by meowmoo** [comment]
https://github.com/xbmc/xbmc/pull/8613#event-496601515

I changed the Titel to oe8 because oe7 will be kodi 16 and oe8 will be kodi 17, where the render api change.

I'm running a custom egl OE build witch is basicly oe8,  I'm back to the last version before the api changed, so I can still use Hyperion, but I'm happy to upgrade and do all the testing that's needed

**Comment by brindosch** [comment]
@iLLiac4 made a pull request. It is listed in your link as reference too.
We are talking about the Kodi plugin?

**Comment by meowmoo** [comment]
Plugin should be fix already?!

But all no plugin users (RPI(?), X-11) will run into issues.

**Comment by brindosch** [comment]
I don´t know in which way x-11 and kodi rendering are affecting each other.
I know that with kodi v17 on windows is everything running with this fix.

You use X-11 and the kodi plugin at the same time? Kodi plugin sends the pictures to hyperion.
X-11 should grab through the x-11 window manager? I have to setting up  a system with oe to check this.

**Comment by meowmoo** [comment]
I'm just using x-11,  since someone tells me i need it for working lights in menu, I tried the add-on once.

Maby I give it a try again tonight.

I don't know how x-11 grab the picture.

On my current setup everything is working just fine, latest Hyperion (x11) kodi 17 alpha, the last bevor the render change.

**Comment by iLLiac4** [comment]
Rpi uses fremabuffer, also nvidia is able to work without addon (mine 610 works), If framebuffer is used then it is able to grab light from menus. Rpi can not use x11. x11 is used only on x86_64 builds. On intel builds (do not know for ATI) the addon is needed (can not grab menus) or. x11 if you want to grab menus.

**Comment by brindosch** [comment]
@meowmoo 
News?

**Comment by meowmoo** [comment]
Using this kodi build (OE8, Kodi 17Alpha)
http://forum.kodi.tv/showthread.php?tid=238393&pid=2300371#pid2300371
using the x11 file
watching a video works fine, 
but on menu it is kinda "flashy"
here is a crappy video, but you get the idea
https://www.youtube.com/watch?v=5ypGOFeLE24

after watching a tv show, it also flash
https://www.youtube.com/watch?v=YxtPyM_mM4A

this is my config file
https://drive.google.com/open?id=0B9bSf6HADVkFckxnNHNIWjRMXzQ
i tried to get a log with the HyperCon Get log button, but it did not work, HyperCon just frezz

Btw, HyperCon dont save my USB device setting and Baudrate, I need to change them after every start

**Comment by brindosch** [comment]
1. Did you get the same result with openelec 7 beta 2? That we have an idea which versions are afftected.
2. yes, i have to admit i never tested the function. will be work for 100% and all present installs with the next version.
3. yes, not yet implemented

**Comment by meowmoo** [comment]
no, oe 7 beta 2 works fine, because its still Kodi 16 ;P

**Comment by brindosch** [comment]
It is still working with DISPMANX (osmc Kodi V17 Alpha), on OpenELEC with milhouse builds i had a problem with a not working black border detection, the difference(s) are the deps and maybe another tweak. So it is more a hyperion-x11 bug than a big change.

**Comment by brindosch** [comment]
Part of V1.03.0
//Closed
