### ISSUE TITLE
NO ISSUE - IRC for support

### ISSUE THREAD

**Issue by tpmodding** [hyperion-project/hyperion#515]
hey community,

it is sometimes hard to communicate on github if you only have a quick question!
I created a IRC channel on quakenet to communicate faster and easier

you can join on quaknet in channel #hyperion and ask questions, i will help you as far as possible

you can use the webchat if you dont have IRC
http://webchat.quakenet.org/?channels=hyperion&uio=d4

ps: for german support you can also join to #rpiambi 
http://webchat.quakenet.org/?channels=rpiambi&uio=d4

See you there!

**Comment by brindosch** [comment]
great idea tpmodding,
thank you for all efforts!
