### ISSUE TITLE
Test cases and approaches discussion

### ISSUE THREAD

**Issue by penfold42** [hyperion-project/hyperion#536]
It would be great to get some automated test coverage and I thought I'd get the ball rolling on some ideas.

It's  obvious that a successful build and run is easy to test, but without real hardware and cameras to watch the LEDs it's a bit harder to go further.

Could we use strace  to catch writes to SPI and uart devices ?

We can use the effects engine to provide some known led data.

Do we care about security testing ? As more and more of hyperion is exposed to the network, maybe this is becoming more important.

**Comment by redPanther** [comment]
just a short note. I've written a sim for led hardware:
https://github.com/redPanther/hypersim
you can test complete hyperion except the led things. (e.g. grabbers, color transforms, led layout, forwarding ....)

**Comment by tpmodding** [comment]
i would prefer the real-system-test. i can test the nearly most systems...(rpi b,b+,3....osx/windows/enigma2(stb receiver)) i have one wire leds (ws2812b) and data/clock (lpd8806) also i have utv007/easycap and stk1160 USB video grabber... it takes only a little bit time, but its the best solution..

security testing: hmm is this necessary? sure it is better to be secure anytime, but have you examples what to secure? connection between udp-devices? 

ps: i would love to see important/active users like @redPanther @penfold42 @brindosch  in IRC to discuss necessary thinks :+1: :+1: 
http://webchat.quakenet.org/?channels=hyperion&uio=d4 or IRC client: quakenet -> #hyperion channel

**Comment by brindosch** [comment]
All new pull request will be redirected to the Beta branch, where we could test everything until it is inside master.
@penfold42 some good ideas, but who will could setting this up and invest the testing time?
I can´t
I will test everything that is new and i can test (hardware) in the Beta branch.

**Comment by penfold42** [comment]
I missed your post from 2 weeks ago about the simulator. Cool !

I also remember there's the "test" led driver that writes the output led data to a file.
I don't know why I didn't think of it before - it's how my UDP driver started !

**Comment by redPanther** [comment]
my fadecandy driver starts also with the ledtest driver. BTW I would suggest that we rename the test driver to "file" - because this tells a little bit more about the driver. 
ATM I had limited time for coding, so if somebody wants to rename it ....

**Comment by penfold42** [comment]
I'll do it.

I'll also default the output file to /dev/null

**Comment by tpmodding** [comment]
@redPanther @penfold42 

Any News? How we handle that hole thing now? with the file output?

**Comment by brindosch** [comment]
More or less moved to hyperion.ng

**Comment by redPanther** [comment]
we have a test framework in hyperion.ng. Not that great as it could be, but it's a start and it's helpfull

**Comment by brindosch** [comment]
Yes, for sure it will be improved as time goes by :)
