### ISSUE TITLE
Configuration Reference wiki is incomplete

### ISSUE THREAD

**Issue by penfold42** [hyperion-project/hyperion#543]
Hi all,

I've created a new wiki page https://github.com/tvdzwan/hyperion/wiki/Configuration-Reference to detail all configuration options.
I've grepped through the source hopefully catching every config item thats there right now.

I dont know what the best format is to describe all the options, but I've made a start on a couple I know all about!

Please help with more detailed descriptions! *grin*

**Comment by brindosch** [comment]
Thank your for your work on this. We need a big buck of time until all is good described
Additional not all devies are in HyperCon (like UDP, i found a documentation in the repo deps....)
Work.. Work.. Work..
2 years of no care :(

If someone wants to help to add (explain) all HyperCon options just do it!
@tpmodding and i spent too much time last days to hyperion. We have to "calm" down a little bit.

**Comment by redPanther** [comment]
thx for the hard work!!! 
just short todo:
missing: grabber configs
good thing is to sort (devices) alphabeticly.
add example code for config
link section to wiki page if exists (e.g. network stuff)
documentation about default values

**Comment by NicoHood** [comment]
I find it really hard to make wikis looking good and finding what you are searching for. To keep a good overview you need to use some style formats. Also you should avoid duplicating information.

So I'd rather create a proper wiki page about the .json config file and describe all possible parameters (especially the possible devices). The tool basically just changes those values. You can link to the json wiki page then and every doc is in sync. Additionally I'd describe the process of ordering leds, mirroring etc what is not related to the .json directly.

I'd use a headline, a small description (with maybe details) and an example config.
An example device description could look like this:

---

### RawHID
RawHID sends all LED data via USB HID Protocol to the device. An Arduino with the [HID Project](https://github.com/NicoHood/HID) can be used. You can find an usage example there.

**Example:**
```json
	/// Device configuration contains the following fields:
	/// * 'name'       : The user friendly name of the device (only used for display purposes)
	/// * 'type'       : The type of the device or leds
	/// * 'VID'        : USB Vendor ID of the RawHID device.
	/// * 'PID'        : USB Product ID of the RawHID device.
	/// * 'colorOrder' : The order of the color bytes ('rgb', 'rbg', 'bgr', etc.).
	"device" :
	{
		"name"       : "MyPi",
		"type"       : "rawhid",
		"VID"        : "0x2341",
		"PID"        : "0x8036",
		"colorOrder" : "rgb"
	},
```

---

Also while looking at this the color order should be moved somewhere else and not to the device.
Then it should also be possible to use multiple outputs in the fututre (with different names?)

**Comment by penfold42** [comment]
All good points above - we almost need a table format for the parameters - name, type, range, default, mandatory.

I'll look into why my grep through the source missed the grabber options - I suspect I started too low in the file structure.

Funny you should mention the colororder. The code looks crazy to me when I was looking at it today. I think it needs refactoring. It's parsed a couple of times, converted back and forth to and from strings. Should it not be moved into the leddevicefactory ?

**Comment by NicoHood** [comment]
I do not know about the colororder feature, but I can think of two implementations:
* It is a general color order setting (which would be bad)
* It would be an optional parameter for every device, cause some led strips invert colors

If it is the last option It would be cool if this is optional, cause then we can shorten the examples for RawHID devices. But well. Hm maybe not. It might be a good ideas to keep it like that, so you can always change the order on any device.

**Comment by brindosch** [comment]
At least the WS2801 change their color order from stripe to stripe. As far as i know tha apa102 are all the same order.
To keep it running - i would leave it as it is (for the moment)
Keep in mind that i have to change HyperCon too and what do we do with people that update hyperion but not the config? I am not sure if this is necessary (fot the moment :) )

**Comment by penfold42** [comment]
Ws2811 can be built in any colour order too. Anything with a discrete chip could do crazy stuff.

No problem with the 2812 - it's all integrated !
