### ISSUE TITLE
Network and distributed features wiki is incomplete

### ISSUE THREAD

**Issue by penfold42** [hyperion-project/hyperion#544]
Please help flesh out the newly introduced features that allow us to use a distributed deployment in oh so many ways...

I've started:
https://github.com/tvdzwan/hyperion/wiki/Network-and-distributed-features

**Comment by RickDB** [comment]
Just reworked the page a bit with split examples and clearer layout.

**Comment by penfold42** [comment]
Great work, thanks !

**Comment by tpmodding** [comment]
think can be closed...
