### ISSUE TITLE
[Feature request] Discovery (zeroconf, broadcast)

### ISSUE THREAD

**Issue by WeeJeWel** [hyperion-project/hyperion#545]
It would be nice to discover a hyperion server by a broadcast, or zeroconf (Bonjour) for example.

**Comment by penfold42** [comment]
Me too!

I was watching a tcpdump today as the iOS app did a sweep of the local subnet.

I have 3 instances running on one box and zeroconf would let the app find the instances running on non default ports.

**Comment by penfold42** [comment]
This doesn't look too hard http://avahi.org/download/doxygen/client-publish-service_8c-example.html

So now we need to think about service names and how we uniquely identify multiple instances on the same host.

Maybe the existing "device name" can be reused.

What services do we need ?
proto, Json, bob light and I guess my UDP led receiver can register itself in Python

**Comment by redPanther** [comment]
I think bob light is not needed, because the boblight client didnt use zeroconf.

mainly the json server should support auto discovery, because it is controllable by a client with ui like the android app.

having this for proto too would be very nice, because this makes forwarder config very easy.

e.g.
```
forwarder : {
  json : "*",
  proto: "*"
}
```
then all messages would be send to all available clients. 
Nice thing - anyone to implement this?

**Comment by RickDB** [comment]
There's also a Qt based zeroconf / avahi option:

https://github.com/johanneshilden/qtzeroconf

**Comment by penfold42** [comment]
Anyone want to look at my attempt so far ?

https://github.com/penfold42/hyperion/tree/zeroconf?files=1

**Comment by brindosch** [comment]
Sounds/looks interesting!
The new dependencies (libs) needs to be installed on raspbian/osmc and should be part for openelec.deps.tar.gz for openelec/rasplex and so on?

**Comment by penfold42** [comment]
Yep - Here's what I installed whilst working out whats required:
libavahi-common-dev:armhf
libdbus-1-dev:armhf
libavahi-client-dev:armhf
libavahi-core-dev:armhf
libavahi-compat-libdnssd1:armhf
libavahi-compat-libdnssd-dev:armhf
libavahi-qt4-1:armhf
libavahi-qt4-dev:armhf
avahi-utils:armhf

**Comment by RickDB** [comment]
Looks good!

So in each service (json / proto) we get a description and service name where the first name is its name and the last one the service type to filter out which is which right?

**Comment by penfold42** [comment]
Yep! With hopefully meaningful defaults if omitted.

Do you think we need a disable/ enable option as well ?

**Comment by penfold42** [comment]
const std::string hostname = QHostInfo::localHostName().toStdString();
const std::string mDNSDescr = jsonServerConfig.get("mDNSDescr", hostname).asString();
const std::string mDNSService = jsonServerConfig.get("mDNSService", "_hyperiond_json._tcp").asString();

**Comment by RickDB** [comment]
Think we keep it default on as with multicast it's only a presence (listener) with a hostname name like your above example which would be perfect :+1: , that way it will just work for the users without them having to worry about editing their configs with a new setting but we can best throw this in the group on the forum to discuss :)

If they do run more instances without setting mDNS config info maybe we can append a "_1" "_2" etc.. to its mDNSDescr but not sure if we can reliably multiple Hyperiond instances at the moment?

**Comment by penfold42** [comment]
Even if we don't append a suffix, they'll each have unique port numbers advertised so you'll see the separate instances

**Comment by brindosch** [comment]
May it possible to advertise the current loaded config name? Not sure if i know which port is attached to which function. :D
Makes this sense?
So you could easy see which instance use which config. (if you use the forwarder)

**Comment by penfold42** [comment]
I'll look into it.
I think there's also a txt attribute we can abuse too

**Comment by brindosch** [comment]
@penfold42 
additional idea, hostname or something to see which hyperion it is (if you use more then one hyperion)

these values could be used to extract and insert this as "hyperion profile name" so you always know which Hyperion you use without to edit your self the name

**Comment by penfold42** [comment]
I'll look again in a few days and do a PR.

Right now it has conflicts

**Comment by brindosch** [comment]
take your time!

**Comment by penfold42** [comment]
I've got too many branches ! I really need to get them documented and fix the merge conflicts.
At the risk of abusing this as my todo list :
- zeroconf
- sk6812rgbw
- new UDP driver

Then I need to add sk6812 support and data inversion to my new SPI driver

Does anyone have a view on which is more important ?

**Comment by brindosch** [comment]
Much work!
If Rick starts at the smartphone apps it may be handy to have a zeroconf for auto discovery.
also to add the possibility to save the calibrated values to the current loaded config and restart hyperion may be great from a user view.
(just user view and new smartphone apps are really necessary to complete hyperion in a good way -again)

We could proceed fast to take the first testing steps with QT5, we just need some time and a feedback on every platform.

**Comment by RickDB** [comment]
Yep zeroconf would mean we can add servers on the fly with ease  :)  do plan on adding by hostname instead of IP as well with the default port filled as to handle dynamic IP setups.
Will have a working concept of the app (android / windows with XAML design) next week which will already have the basics and hope to get the calibration in it then as well.

**Comment by redPanther** [comment]
@RickDB ... thx for your work! 
new udp driver - will it based on qt classes? would be very good if this is you plan, because hyperion is a qt project. I've written a tpm2net driver with qt classes if you need inspiration https://github.com/redPanther/hyperion/blob/tpm2net/libsrc/leddevice/LedDeviceTpm2net.cpp

zeroconf:
I suggest we should implement this only for qt5. When we build with ENABLE_QT5=OFF then zeroconf stuff is switched off.

**Comment by penfold42** [comment]
Yep checkout my branch - QT made it much nicer and simpler than my first C implementation

**Comment by penfold42** [comment]
Btw, my zeroconf stuff does work with qt4 and qt5 but it's big and fat because it includes a lot of Anahi junk.

There are others that need qt5 and now I can build for qt5 I'll check them out to see if there's less bloat

**Comment by brindosch** [comment]
yes, skip qt4. I don´t fear the qt5 testing. As @redPanther  said it is worth to work more on this

**Comment by penfold42** [comment]
Given I've got it working with qt4 ill do the qt5 only one as well and use conditionals to select it with cmake

**Comment by brindosch** [comment]
Will be part of V1.03.0
/closed
