### ISSUE TITLE
get current state with JSON?

### ISSUE THREAD

**Issue by Bootscreen** [hyperion-project/hyperion#548]
Hello,

is it possible to get the current state over the json interface? i.e. the current (lowest priority) effect or color 

Greetings Bootscreen

**Comment by penfold42** [comment]
Have you tried Hyperion-remote -l ?

**Comment by Bootscreen** [comment]
no, because on the remote system i don't have hyperion.

**Comment by p1n9** [comment]
try to send the json object : {"command": "serverinfo"}

**Comment by Bootscreen** [comment]
maybe i am blind, but where can i find the active effect in the result?

**Comment by p1n9** [comment]
you will not see the active effect name, only it's priority and duration

**Comment by Bootscreen** [comment]
any other possibility to find out the current effect?

**Comment by p1n9** [comment]
I'm afraid not...

**Comment by p1n9** [comment]
a workaround : you can set effects with different priority in order to use priority as "id"

**Comment by Bootscreen** [comment]
that doesn't work in my case.

i wrote a module for the homeautomation server FHEM in which i can set color or effect. and now i would like to implement the current state as current color, effect or grabber, no matter from where it's startet

**Comment by MakeMeASandwich** [comment]
Related: #398

**Comment by tavalin** [comment]
Is there any good documentation regarding the json commands? I'm also planning to control hyperion from my home automation software.

**Comment by penfold42** [comment]
Not yet, but it would be a good thing.
Some examples in perl, Python etc would be good too.

If I get time, I'll rework my lirc listener perl script that lets me used an IR remote to control it.

In the interim, there's always hyperion-remote --print

**Comment by brindosch** [comment]
I would appreciate a article at the wiki that show some code snippets.
The json interface will be extended with some great things anyway :)

thank you :)

**Comment by brindosch** [comment]
https://github.com/hyperion-project/hyperion/pull/622

/will be merged soon, active effects is already available in V1.02.0
thank you
