### ISSUE TITLE
Aarch64 compile error

### ISSUE THREAD

**Issue by alex240188** [hyperion-project/hyperion#550]
I'm attempting to build for the 64bit amlogic s905 processor.
However protobuf seems unable to compile on the target platform.
It built successfully using amlogic grabber & fb grabber which I have used previously on s805 hardware.
When starting Hyperion it starts up fine but would not establish a connection to Kodi to get play modes despite using the correct settings. Is protobuf required for the kodi connection?

**Comment by stefansaraev** [comment]
not at all. you may want to set xbmcAddress to ::1 instead of localhost.

**Comment by alex240188** [comment]
Ah thank you for this one.
I didn't expect it would be looking for ipv6 format because it's connected to the network using ipv4.
Now menu grabbing seems to be alive but no video.
Doh I didn't enable amvideocap.
I'll recompile and try again

**Comment by alex240188** [comment]
Hyperion still fails to grab amcodec video
here is the log
Failed to retrieve video state continues indefinetely
`OpenELEC-M18:/dev # /storage/hyperion/bin/hyperiond.sh /storage/.config/hyperion
.config.json
Application build time: Mar  8 2016 14:01:48
QCoreApplication initialised
Selected configuration file: /storage/.config/hyperion.config.json
ColorTransform 'default' => [0; 153]
Device configuration:
{
        "colorOrder" : "rgb",
        "name" : "MyPi",
        "output" : "/dev/ttyACM0",
        "rate" : 2000000,
        "type" : "adalight"
}

Opening UART: /dev/ttyACM0
Creating linear smoothing
Created linear-smoothing(interval_ms=16;settlingTime_ms=50;updateDelay=0
Effect loaded: Cinema brighten lights
Effect loaded: Cinema dim lights
Effect loaded: Knight rider
Effect loaded: Blue mood blobs
Effect loaded: Cold mood blobs
Effect loaded: Full color mood blobs
Effect loaded: Green mood blobs
Effect loaded: Red mood blobs
Effect loaded: Warm mood blobs
Effect loaded: Police Lights Single
Effect loaded: Police Lights Solid
Effect loaded: Rainbow mood
Effect loaded: Rainbow swirl fast
Effect loaded: Rainbow swirl
Effect loaded: Random
Effect loaded: Running dots
Effect loaded: System Shutdown
Effect loaded: Snake
Effect loaded: Sparks Color
Effect loaded: Sparks
Effect loaded: Strobe blue
Effect loaded: Strobe Raspbmc
Effect loaded: Strobe white
Effect loaded: Color traces
Effect loaded: UDP listener
Effect loaded: X-Mas
Initializing Python interpreter
Hyperion created and initialised
run effect Rainbow swirl fast on channel 0
Black border threshold set to 0.01 (3)
DETECTION MODE:default
Boot sequence(Rainbow swirl fast) created and started
XBMC video checker created and started
Json server created and started on port 19444
[AmlogicGrabber::AmlogicGrabber(unsigned int, unsigned int)] constructed(160x160)
Black border threshold set to 0.01 (3)
DETECTION MODE:default
AMLOGIC grabber created and started
Framebuffer opened with resolution: 1920x1080@32bit
Black border threshold set to 0.01 (3)
DETECTION MODE:default
Framebuffer grabber created and started
XBMC Connected
Message from XBMC: {"id":666,"jsonrpc":"2.0","result":[{"playerid":1,"type":"video"}]}
XBMC checker: switching to VIDEO mode
Message from XBMC: {"id":668,"jsonrpc":"2.0","result":{"System.ScreenSaverActive":false}}
Failed to retrieve video state from device: Invalid argument
Failed to retrieve video state from device: Invalid argument
Message from XBMC: {"id":667,"jsonrpc":"2.0","result":{"item":{"file":"/storage/samples/T4A_AmbiLightTest.mp4","label":"T4A_AmbiLightTest.mp4","type":"unknown"}}}
Failed to retrieve video state from device: Invalid argument
Message from XBMC: {"id":670,"jsonrpc":"2.0","result":{"version":{"major":16,"minor":1,"revision":"9cbbe01","tag":"releasecandidate","tagversion":"2"}}}
Failed to retrieve video state from device: Invalid argument
Failed to retrieve video state from device: Invalid argument
Failed to retrieve video state from device: Invalid argument
Failed to retrieve video state from device: Invalid argument
Failed to retrieve video state from device: Invalid argument
Failed to retrieve video state from device: Invalid argument
Failed to retrieve video state from device: Invalid argument`

**Comment by stefansaraev** [comment]
then your amvideocap is probably not correctly set up, double check device tree
I have an s905 device here, need to compile openelec for it, and will try reproduce this weekend.

btw, here is what I have working like charm on my wetek core (s812) : http://sprunge.us/iXUd

**Comment by alex240188** [comment]
Hmm. Looking around I see my DTD lacks reserve-memory and reserve-iomap for amvideocap.0
I'll try adding and recompiling tonight and see if that sorts it.

**Comment by alex240188** [comment]
so after changing the kernel header includes in AmlogicGrabber.cpp

it now starts up correctly however i still cannot grab with amcodec.
the amvideocap appears not to open with the error
"[int AmlogicGrabber::grabFrame(Image<ColorBgr>&)] Failed to open the AMLOGIC device (12): Cannot allocate memory"

here is another log
http://pastebin.com/MGVdXdiM

**Comment by stefansaraev** [comment]
that means your /dev/amvideocap0 does not work. at all :)

**Comment by tpmodding** [comment]
tried to start with sudo?

**Comment by alex240188** [comment]
well thats dissapointing.
do you think I've missed anything.

checked the DTD file, it now looks like this


amvideocap{
compatible = "amlogic,amvideocap";
dev_name = "amvideocap.0";
status = "okay";
reserve-memory = <0x00800000>;//1920*1088*4
reserve-iomap = "true";
};

changed kernel.conf to add
CONFIG_AM_VIDEOCAPTURE=y

I can see /dev/amvideocap0

any suggestions on how to debug further into why amvideocap0 will not work?
thanks for the suggestion tpmodding but I'm using OpenELEC so already running as root

**Comment by msfabxda** [comment]
I'm stuck at the exact same problem right now. Were you able to find a solution ?

**Comment by alex240188** [comment]
No I have not been able to get any further towards a solution.

**Comment by msfabxda** [comment]
I finally got it working. It seems like the videcap driver has changed an no longer needs reserved memory. The Kernel log revealed that this function is failing: 
 "getgctrl()->vaddr =(unsigned long)dma_alloc_coherent(amports_get_dma_device(),
						  getgctrl()->size, &dma_handle,
						  GFP_KERNEL);"
it seems like it's no possible to allocate more then 2M see: http://stackoverflow.com/questions/19423736/dma-alloc-coherent-fails-when-buffer-2m-on-kernel-3-2
I changed the CONFIG_FORCE_MAX_ZONEORDER to 12 as suggested and recompiled kernel but this sadly didn't  fix the problem. So I changed the define BUF_SIZE_MAX to 0x1FFFFF  in amvideocap.c and recompiled the Kernel. I seems to work perfectly now, excapt for the fact that the colors are switched ( I changed to color order as a temporary solution).


https://github.com/hardkernel/linux/blob/odroidc2-3.14.y/drivers/amlogic/amports/amvideocap.c

**Comment by brindosch** [comment]
Hint added

**Comment by stefansaraev** [comment]
@alex240188 I just got an s905 device. indeed. the header has changed. damn amlogic..

a simple fix that worked for me: http://sprunge.us/iPND
better fix that should work for both 3.10 and 3.14: http://sprunge.us/EYPO

amcodec/amports/amstream.h is part of "libamcodec". @redPanther fyi.

**Comment by redPanther** [comment]
thx, I will look into.
> "However protobuf seems unable to compile on the target platform."
can you confirm that? because protobuf is mandatory for hyperion.ng. 

I assume the new version (with int) doesn't work for kernel prior 3.14?

**Comment by stefansaraev** [comment]
> can you confirm that? because protobuf is mandatory for hyperion.ng.

well, I use external protobuf. no problem with it.

> I assume the new version (with int) doesn't work for kernel prior 3.14?

yea, it should not work. however, in 3.10 there was no amlogic aarch64 support, so binaries compiled for wetekplay / wetek core will not work on wetek hub / wetek play2 and newer anyway.

**Comment by alex240188** [comment]
I don't think protobuf would compile if I tried compiling natively on aarch64 however it worked fine if cross compiling.
Don't quote me on that as it's been quite a while since I had attempted to do anything with the s905 box
