### ISSUE TITLE
hyperion-x11 Flicker

### ISSUE THREAD

**Issue by siam28** [hyperion-project/hyperion#568]
I am using hyperion on an x86 machine with Arch Linux (all packages are at their latest version).
My hyperion config file is listed here:
http://pastebin.com/LbiWYnkw

I am getting a blue flicker-type behavior when transitioning from 1 image to another when I use hyperion-x11 for the grabbing. After starting hyperiond with the config file above, I use `DISPLAY=:0 hyperion-x11` to start hyperion-x11.  This issue is not present when I use v4l2.
A video to demonstrate is shown [here](https://www.youtube.com/watch?v=-pNEwmcpnHU&feature=youtu.be)

Seems to be related to the menus as the flickers  disappear during video playback, but reappear if I pull up a menu during playback. A video to demonstrate is shown [here](https://www.youtube.com/watch?v=ccUrJwV-xMk&feature=youtu.be)

Using the Kodi addon eliminates the flickering issue when I pull up the menu/main window from a playing video, however, the addon only covers video playback.  I like hyperion enabled in the menus as well.

**Comment by meowmoo** [comment]
Witch kodi Version? 17alpha?

**Comment by siam28** [comment]
16.0-2.
That's the latest version in the Arch repository which was updated on Feb.
24.
I'll roll back to an earlier version and see if it makes a difference.

On Sunday, March 27, 2016, meowmoo <notifications@github.com> wrote:

> Witch kodi Version? 17alpha?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/tvdzwan/hyperion/issues/568#issuecomment-202041520>
>


-- 
*Siam Aumi*

**Comment by siam28** [comment]
The menu flicker issue is still  there with 15.2-5 and latest git version of hyperion-x11 - when I pull up the main menu from a playing video, I see the flickering, and when I go back to full screen, the flickering is gone.

**Comment by pdf** [comment]
You'll also get weird frames injected if the frame-rate doesn't match - I've been running hyperion-x11 at 30fps, and if I switch the display output to 50hz (sometimes it starts that way), then start a music viz, there's heaps of flickering and mostly blue frames being output.  I've gone back to boblight-x11 for now, but that loses black bar detection etc.

**Comment by brindosch** [comment]
@meowmoo @siam28 
Could you install the latest beta and report back?
https://hyperion-project.org/threads/install-latest-hyperion-beta-v1-03-0.25/

Thank you

**Comment by pdf** [comment]
@brindosch can I just build from the Beta branch?

**Comment by brindosch** [comment]
yes, but you don´t need to.
Just use the script to install it. You could go back at any time.

**Comment by pdf** [comment]
> yes, but you don´t need to.
> Just use the script to install it. You could go back at any time.

I would have to read the script to work out what it's going to to do my system, but I already know what the build system will do :wink:

In any case, the result for me is not so good - hyperion-X11 does not work at all for me now:

```
/opt/hyperion/bin/hyperion-x11 -f 30 -s 4
hyperion-x11:
        version   : Beta (brindosch-aa9a4f3/c2c4fd6-1464120939
        build time: May 25 2016 21:52:22
PROTOCONNECTION INFO: Connecting to Hyperion: 127.0.0.1:19445
X Error of failed request:  RenderBadPicture (invalid Picture parameter)
  Major opcode of failed request:  139 (RENDER)
  Minor opcode of failed request:  8 (RenderComposite)
  Picture id in failed request: 0x17
  Serial number of failed request:  13
  Current serial number in output stream:  14
```

**Comment by brindosch** [comment]
hm, @Paulchen-Panther

**Comment by pdf** [comment]
The above was with XRender obviously (and that's certainly my preference), but for completeness I get the following when requesting XGetImage:

```
/opt/hyperion/bin/hyperion-x11 -x -f 30 -s 4
hyperion-x11:
        version   : Beta (brindosch-aa9a4f3/c2c4fd6-1464120939
        build time: May 25 2016 21:52:22
PROTOCONNECTION INFO: Connecting to Hyperion: 127.0.0.1:19445
X11GRABBER ERROR: Grab failed
PROTOCONNECTION INFO: Connected to Hyperion: 127.0.0.1:19445
X11GRABBER ERROR: Grab failed
X11GRABBER ERROR: Grab failed
X11GRABBER ERROR: Grab failed
X11GRABBER ERROR: Grab failed
X11GRABBER ERROR: Grab failed
X11GRABBER ERROR: Grab failed
X11GRABBER ERROR: Grab failed
X11GRABBER ERROR: Grab failed
X11GRABBER ERROR: Grab failed
X11GRABBER ERROR: Grab failed
... etc
```

**Comment by Paulchen-Panther** [comment]
Sorry. Once again, the copy and paste (and delete) error has crept in.

@brindosch: Can you please fix the error for me. In X11Grabber.cpp line 120 please insert "updateScreenDimensions();" See Picture: 
![screenshot](https://cloud.githubusercontent.com/assets/16664240/15546784/924f690e-22a1-11e6-8b7e-1ad9886e9f88.png)

Many Thanks. 

@pdf: In the meantime, please try the corrected hyperion-x11 binary file.
https://github.com/Paulchen-Panther/hyperion/blob/master/hyperion_x86_x64.zip

or please wait for fix the Beta.

Sorry again

**Comment by brindosch** [comment]
New bins online, thank you for response.
@pdf 
Please test the new implementation and report back, then i could mark it as "ready for stable"  :)

Thank you :)

**Comment by pdf** [comment]
Both grabber modes are now functional.  I think the flicker issue might be improved too, but it's hard to see during the day time in my viewing area - I'll confirm tonight and let you know.

**Comment by meowmoo** [comment]
looks good on my end, no flickering anymore on the latest libreelec millhouse build

**Comment by pdf** [comment]
Yep, looking good here, thanks @Paulchen-Panther, @brindosch.

**Comment by brindosch** [comment]
Ah, one additional question, is someone using the KodiCheck with hyperion-x11? Is it possible to stat/stop grabbing depending on the kodi state?

**Comment by brindosch** [comment]
Does someone use 3D MVC? I need a screenshot of a grabbed picture.
thank you :)

**Comment by meowmoo** [comment]
@brindosch 

no its not possible, i disable everything in the KodiCheck, beside Menu, and the lights are still on all the time (movie, menu, pictures, music)

**Comment by brindosch** [comment]
hm, okay. So no implementation (connection) here. Good to know.
a complete resorting and same feature level for all grabbers would be great.
