### ISSUE TITLE
Random Flashes from LEDs during playback using Hyperion/OpenElec

### ISSUE THREAD

**Issue by jweaver100** [hyperion-project/hyperion#569]
I have a Raspberry Pi2 running Openelec (6.0.3) and have recently added Hyperion using WS2801 LEDs

Its working perfectly but I have noticed occasional "flashes" from all of the LEDs.. Just one frame where they go all white for a fraction of a second.

There is no pattern to this, and if I rewind the problem does not happen at the same point. Sometimes i can go for hours without seeing this.. Other times it happens fairly frequently.

Has anyone else experienced this?

Jon

**Comment by penfold42** [comment]
How often does it happen ?

Does it happen when running effects ?

How robust is the wiring ?

What is the power supply you're using ?

Do you have any level shifters ?

**Comment by jweaver100** [comment]
1. Sometimes every few mins.. Other times hours... Seems to be worse in some movies making me think its caused by the source material

2. Havnt used effects for every long and since this only happens randomly, i am not sure i could test this.

3. Wiring very robust. Massively over engineered. Used 13amp cable. Also feeding in power at both ends of the loop.. 

4. PSU is a 10amp version.. Well upto the job considering i have less than 150 LEDs

5. Not sure what level shifters are.. Sorry.

**Comment by penfold42** [comment]
If I'm reading the data sheet of the 2801 correctly, they want vcc*0.8v for a guaranteed logical 1.

At 5v this means you need an input of 4v which is higher than the 3.3v gpio on the Pi.
Level shifters convert the 3.3v to a higher level like 5v.
Having said that, many people get away without level shifters.

Can you try putting some CPU load on the pi and see if it makes it worse ?

**Comment by jweaver100** [comment]
I am pretty sure Its nothing physical. If i "pause" a movie and leave the LED stuck in their last state, i have never seen this flashing... 

I like the idea of this being CPU related.. Is there an easy way to load the CPU?

**Comment by brindosch** [comment]
I encounter also sometimes flashes with my apa102. The last 2 weeks ago, but i really have no idea why that happen sometimes. At a flashing moment i cut the Network cable but nothing changed. It may be related to "a over the air frequency" or power interferences of the whole network.
Also i can´t figure out it is cpu load. just random

This may be realted to point 5 (not the flash itself, the result)
https://github.com/tvdzwan/hyperion/wiki/FAQ-Frequently-Asked-(Problems)-Questions

**Comment by brindosch** [comment]
Check out point 1 too

**Comment by brindosch** [comment]
Should be answered
/closed

**Comment by jweaver100** [comment]
Those 2 points didnt help me.. But i did make a change which may have helped.

I had the baud rate set at 100,000.. So now i have lowered it to 25,000 and i dont think i have seen these flashes since.. But i am still monitoring this.

**Comment by brindosch** [comment]
Ok, thank you for reply
