### ISSUE TITLE
Remote control and Schedule on and off its posible?

### ISSUE THREAD

**Issue by Luiscvi** [hyperion-project/hyperion#573]
Can i use Hyperion app when i am out my home?
can i schedule turn on and off of leds?

**1.** i use raspberry P 2
**2.** ws2018 led strip

**Comment by penfold42** [comment]
Yes if port 19444 is open to the outside.

Use cron to schedule running Hyperion-remote

**Comment by Luiscvi** [comment]
How can i open my port? 

How schedule hryperion using cron

Could you help me?
@penfold42

**Comment by penfold42** [comment]
On your firewall/internet gateway you need to setup some sort of port forwarding - you'll need to consult the manual for your device.

cron is available on all UNIX/Linux platforms.
Google for "how to use cron on raspberry pi"

**Comment by Luiscvi** [comment]
do you know what conmand is fot turn on and turn off hyperion?

**Comment by Luiscvi** [comment]
thanks @penfold42 
do you know what conmand is fot turn on and turn off hyperion?

**Comment by penfold42** [comment]
Hyperion-remote

Either set the colour to black or set the HSV "value" to zero

**Comment by RickDB** [comment]
For a full list of hyperion-remote parameters there's this wiki page:

https://github.com/tvdzwan/hyperion/wiki/Command-line-utility

**Comment by Luiscvi** [comment]
For example if i want to turn on at 18:00 hdmi input, and turn off 22:30 how i have to type in the command line?

**Comment by RickDB** [comment]
You can't specifically toggle the HDMI input however you can block incoming requests by setting it to black and thus leaving off the leds like off the leds:

**From withing rPi SSH session**

- Open cron schedule overview by executing command:

crontab -e

- Add the following 2 entries there:

0 18 * * * hyperion-remote --clearall
30 22 * * * hyperion-remote --color black -p 1

- This will clear all priorities at 18:00 every day to allow new colors via live capture in your case and on 22:30 it will block all by setting it to black on the highest priority possible (1)

**Comment by Luiscvi** [comment]
thanks, @RickDB 
do i need to create any hyperion-remote file?

**Comment by Luiscvi** [comment]
or only i pur those commands on putty?

**Comment by Luiscvi** [comment]
or i only need to put those commands on putty SSL?

**Comment by Luiscvi** [comment]
I have to have my Rpi always connected to the Internet to work? or I can enter commands and disconnected and will run the same way? @RickDB

**Comment by penfold42** [comment]
Cron is a scheduler that runs on the background as long as the pi is on to will keep enabling and disabling all by itself

**Comment by Luiscvi** [comment]
thats mean that it will work also is offline?

**Comment by penfold42** [comment]
crontab -e
This is used to edit the cron config file so that once you save and quit you can disconnect

**Comment by Luiscvi** [comment]
i put commands and my hyperion stops work,

**Comment by Luiscvi** [comment]
when using crontab -e and entered the hyperion commands stopped working, even the hdmi input, Hyperio app and everything stopped working.

**Comment by Luiscvi** [comment]
when using it, and entered the hyperion commands stopped working, even the hdmi input, Hyperio app and everything stopped working. @penfold42 @RickDB

**Comment by RickDB** [comment]
Most likely you're executing the commands in the ssh session instead of adding them as scheduled tasks (cron jobs), make sure to execute the "crontab -e" command first in a ssh session and wait for a text editor (nano preferable) to show up in that session.

After that add the mentioned 2 lines at the bottom and save with F2, that will update the scheduler config and run those commands at the specified times.
A more detailed explanation can be found here:

https://help.ubuntu.com/community/CronHowto

**Comment by Luiscvi** [comment]
maybe I have to enter the command like this?

0 18 * * */ hyperion-remote/ --clearall
30 22 * * */ hyperion-remote/ --color black -p 1

**Comment by RickDB** [comment]
That wouldn't work as hyperion-remote is a local program and adding a / after would make it point to a file location that doesn't exist.

**Comment by Luiscvi** [comment]
how name i need to save the file?
@RickDB @penfold42

**Comment by RickDB** [comment]
No need to save a new file as crontab handles that for you, made an automated script for you which does the crontab updates for you:

Step 1
Via putty make an SSH connection to your raspberry pi

Step 2
Execute the following commands in this SSH session **separately and in this order**:

wget http://bit.ly/1UHyHJe
sh hyp_cron.sh

Step 3

Disconnect from the SSH session (putty) and now you have created 2 cron jobs which will run in the background.

**Comment by RickDB** [comment]
@Luiscvi is the schedule working correctly after running the script?

**Comment by Luiscvi** [comment]
I paste the scrip just as your shared but it did not work.
at least not the black color, clean all, I'm not sure. 
could you send me just as paste in the editor?
please

**Comment by RickDB** [comment]
That script should have worked, any specific errors?
Here's the script source for copy / pasting:

```
#write out current crontab
crontab -l > mycron
#echo new cron into cron file
echo "0 18 * * * hyperion-remote --clearall" >> mycron
echo "30 22 * * * hyperion-remote --color black -p 1" >> mycron
#install new cron file
crontab mycron
rm mycron
```

**Comment by Luiscvi** [comment]
do i need to activate cron jobs? i never used cron after.
and still no work :( @RickDB 
also my date is wrong any command for get GTM -7 phoenix?

Thanks

**Comment by Luiscvi** [comment]
do i need to activate cron jobs? i never used cron before.
and still no work :( @RickDB 
also my date is wrong any command for get GTM -7 phoenix?

Thanks

**Comment by RickDB** [comment]
https://www.raspberrypi.org/documentation/configuration/raspi-config.md

**Comment by Luiscvi** [comment]
![captura1](https://cloud.githubusercontent.com/assets/8108675/14336098/bb734bdc-fc15-11e5-860e-3f4f0e5c7623.PNG)
still does not work any help please I'm desperate!!

**Comment by Luiscvi** [comment]
i put this command on putty _/storage/hyperion/bin/hyperion-remote.sh --priority 5 --clearall_ and it works but in crontab no works @penfold42 @RickDB @tvdzwan 
ANYBODY PLEASE HELPMEEEE!! :(

**Comment by penfold42** [comment]
how did you get there?

that looks like the shell script that you should have run is actually IN the crontab config file.

please follow the steps listed above:

Step 1
Via putty make an SSH connection to your raspberry pi

Step 2
Execute the following commands in this SSH session separately and in this order:

wget https://gist.githubusercontent.com/RickDB/18f3421148adbe57dedf08f8a61b6f0c/raw/d86cddda92cbd182613d116ec06a27f92b1c0916/hyp_cron.sh

sh hyp_cron.sh

**Comment by Luiscvi** [comment]
![step1](https://cloud.githubusercontent.com/assets/8108675/14341376/28b1fc5e-fc46-11e5-9154-d0136e8e4046.PNG)
STEP 1

![step2](https://cloud.githubusercontent.com/assets/8108675/14341379/2c1b0296-fc46-11e5-85f9-7e19dd8f3516.PNG)
STEP 2 

STEP 3 nothing happens.

**Comment by Luiscvi** [comment]
any idea? @penfold42 @RickDB

**Comment by brindosch** [comment]
I am sorry, this is not hyperion related. Also you mention now after post x that you use openelec. Please check our wiki for openelc special cases. It is possible that it may not work with openelec.
/Closed
