### ISSUE TITLE
Problems after installing Hyperion

### ISSUE THREAD

**Issue by xircom** [hyperion-project/hyperion#577]
Hello everybody, I am having some troubles after the installation of Hyperion. I have a Raspbeery 3 with osmc and ws2812b leds, to install the hyperion I've followed this steps:

sudo apt-get update
sudo apt-get install libqtcore4 libqtgui4 libqt4-network libusb-1.0-0 ca-certificates
wget -N https://raw.github.com/tvdzwan/hyperion/master/bin/install_hyperion.sh
sudo sh ./install_hyperion.sh WS281X

The problem is:  Everytime that I put a video from my hdd the screen starts to on an off randomly but if I stop the hyperion with putty, everything works fine again. Do you have any idea?

**Comment by penfold42** [comment]
I've seen this before. can you try a couple of things:
1)
Stop Hyperion
Start a movie
Start Hyperion 
Does that work ok ?

2)
What framegrabber setting do you have ?
I changed mine to 64 x 64 and it seemed to fix this properly.

The 281x driver seems slightly flaky at the moment depending on what distribution its run with

**Comment by xircom** [comment]
I have stopped a started hyperion like you say and it's not working, about the frame grabber, here is the configuration ( I don't touch anything) What I need to change?

///  The configuration for the frame-grabber, contains the following items: 
	///   * width        : The width of the grabbed frames [pixels]
	///   * height       : The height of the grabbed frames [pixels]
	///   * frequency_Hz : The frequency of the frame grab [Hz]
	///   * priority     : The priority
	"framegrabber" : 
	{
		"width"        : 80,
		"height"       : 45,
		"frequency_Hz" : 10.0,
		"priority"     : 900
	},

	/// The configuration of the Kodi connection used to enable and disable the frame-grabber. Contains the following fields: 
	///  * xbmcAddress       : The IP address of the Kodi-host
	///  * xbmcTcpPort       : The TCP-port of the Kodi-server
	///  * grabVideo         : Flag indicating that the frame-grabber is on(true) during video playback
	///  * grabPictures      : Flag indicating that the frame-grabber is on(true) during picture show
	///  * grabAudio         : Flag indicating that the frame-grabber is on(true) during audio playback
	///  * grabMenu          : Flag indicating that the frame-grabber is on(true) at the Kodi menu
	///  * grabScreensaver   : Flag indicating that the frame-grabber is on(true) when Kodi is on screensaver
	///  * enable3DDetection : Flag indicating that the frame-grabber should switch to a 3D compatible modus if a 3D video is playing
// 	"xbmcVideoChecker" : 
// 	{
// 		"xbmcAddress" : "127.0.0.1",
// 		"xbmcTcpPort" : 9090,
// 		"grabVideo" : true,
// 		"grabPictures" : true,
// 		"grabAudio" : true,
// 		"grabMenu" : false,
// 		"grabScreensaver" : true,
// 		"enable3DDetection" : true
// 	},

**Comment by mlask** [comment]
It's the same issue like #557

**Comment by penfold42** [comment]
Change width and height to be 64 and 64

**Comment by brindosch** [comment]
Could someone explain why that happen? 64x64 needs more cpu usage (more pixels)
But?...
I have to change default value back to 64x64 when all (just pwm) complain about problems!

**Comment by xircom** [comment]
Ok,  I've changed to 64x64 10fps and the crashes has stopped, thank you very much

**Comment by penfold42** [comment]
I wish I knew why !

For me with OSMC it doesn't matter which led driver I use - it happens with both 2801 and 281x drivers.

**Comment by brindosch** [comment]
I change the default value back to 64x64, that isses again and again bothers me

**Comment by kixounet** [comment]
I have opened an issue #557 about the same behaviour days ago. To my experience lowering the grabber resolution and framerate sometimes solve the issue sometimes not.

I think of a performance issue. Not a CPU performance issue, but I/O performance or GPU performance issue.

I don't think it is cpu issue because the cpu stay under 20 % of usage.

I will keep on investigating this when I will have more free time

**Comment by brindosch** [comment]
The funny thing here is anyway 64x64=4096, 80x48=3600. It should lower the cpu usage

**Comment by xircom** [comment]
Yes, it's very strange... But with 64x64 10 fps is working fine, magic?

**Comment by mlask** [comment]
It isn't working. Any height combined with 64px width doesn't work correctly. And it's not a CPU related issue, because load stays low. It's something with dispmanx grabber, in my instance...

**Comment by brindosch** [comment]
Please take notice: It is just a pwm led problem - all that weird stuff

**Comment by mlask** [comment]
Can't be - it also happens with LEDs on Arduino connected via USB. Calling hyperion-dispmanx statically just to take screenshots also causes that screen flickering...

**Comment by brindosch** [comment]
Okay, redo. But my SPI leds are working without any problems. Why?

**Comment by brindosch** [comment]
When your hyperion-dispmanx throws that probelms too, something went wrong with your software?
Any news?

**Comment by mlask** [comment]
Everything else worked ok. Flickering stopped just after killing hyperiond. Now I gave up with Rpi and switched to C2 so won't help anymore in this topic. Now I'm just waiting for hyperion build for aarch64 ;)
