### ISSUE TITLE
Add proper wiki sidebar

### ISSUE THREAD

**Issue by NicoHood** [hyperion-project/hyperion#579]
The wiki sidebar is full of articles (which is good) but uses a lot of space. If we add a custom one the font is smaller and can have more entries, with subcategories. It can also be sorted.

Examples of my wiki pages:
https://github.com/NicoHood/HID/wiki
https://github.com/NicoHood/HoodLoader2/wiki

**Comment by brindosch** [comment]
ping (The structure is already done, not online)
@tpmodding

**Comment by tpmodding** [comment]
We are working on it... we work silently in the background :) there are some big things coming...but it needs a little bit more time... i study and work, and have to manage my private life also :D 

http://imgur.com/Fy4ssUR --> will come soon, we dont wont to do it step by step...we work for everything in the background and will drop all at once :)

its difficulty, brindosch and i only "manage" this project, big thinks has to be cleared with tvdzwan :)

**Comment by brindosch** [comment]
Wiki will be (re)moved

**Comment by NicoHood** [comment]
And to where?

**Comment by brindosch** [comment]
hehe, be patient :)

**Comment by brindosch** [comment]
@NicoHood 
Hyperion have a new home!
Please read the announcement post and the changelog for V1.02.0
www.hyperion-project.org

Please have a look at our new wiki! (EN/DE)
wiki.hyperion-project.org

All discussions/questions should be moved to the new forum!

**Comment by NicoHood** [comment]
The topic pictures are broken for me, even though I allowed all scripts of the site. I guess my other anti tracking addins block those. I dont know which suspicious host you are using for the forum. But a forum is a very nice idea.

![screenshot from 2016-04-29 22 32 44](https://cloud.githubusercontent.com/assets/6888294/14928793/50d2da02-0e5a-11e6-902b-023cfbd1eeec.png)

I am not sure if a different wiki than on github is better, but I would vote to take the german translation offline. I speak german too, but I find it very annoying to have people write german only tutorials which I cannot share. Or if the german gets out of sync with english its less informative. So this can only work if both are kept in sync with very high care. If not, I suggest to take the german down or add a highlighted warning about reading/editing the translation.

**Comment by tpmodding** [comment]
This is a Community Supported project. You ste welcome to help and Support us. We Tested different wikis and this was the best for us... Users can edit/ update the Wiki. We can moderate every request. We have a History of every edit etc...

Nicht nur meckern sondern aktiv auch was machen... :)

**Comment by tpmodding** [comment]
Btw we Tested with Different systems and Different Browsers... We cant reproduce your suspicious issues... Did you tried with another browser without all of your Plugins?

**Comment by NicoHood** [comment]
Sure I appreciate all the work. Its not that this was meant negative, just some thoughts. Cause "everything is wonderful" doesnt help at all.

Other browsers work. I got adblock, ghostery, https everywhere and noscript as addon. I guess ghostery is the issue here. I just wanted to let you know the bug, as others might also run into it. I do not really care about icons, its not the only webpage that does not work for me.
