### ISSUE TITLE
is there a way to adapt  the color of a portion of the LED strip?

### ISSUE THREAD

**Issue by edwinvd1** [hyperion-project/hyperion#580]
**Please provide some information that we could help as fast as possible.
Please check the wiki in case your problem is already known/feature requested.**

**1.** Used hardware and sofware (Wetek,RPi1,Rpi2,... Ubuntu 14.04(64bit),OSX,OpenELEC,OSMC,XBian,...)
**2.** Your LED device and additional hardware (if used) (WS2801,APA102,WS2812B,...  connected through (direct,arduino uno,...))
**3.** Please upload your Hyperion log to pastebin.com and insert the link. Have a look at the wiki how you get one.
**4.** Please upload your "Hyperion Configuration File" to pastebin.com and insert the link.

**Comment by edwinvd1** [comment]
I have a rp2 and the ws2801 pixel led 100 pcs.50 pcs I ordered earlier than the other 50 pcs
.the white balance of the first 50 is not good.
I can customize this

**Comment by edwinvd1** [comment]
can anyone help me?

**Comment by penfold42** [comment]
https://github.com/tvdzwan/hyperion/wiki/Color-Calibration

You'd need to do this process twice - once for each range of LEDs.

Where it says " LEDs" : "*" you would change tints be 0-49 then duplicate it and change the second group to be 50-99

**Comment by brindosch** [comment]
Note: Wiki article is still not valid with the current version :) But you could set the index on old configs too

**Comment by edwinvd1** [comment]
if I do so, he does nothing.

"transform" :
		[
			{
				"id"   : "default",
				"leds" : "0-49",
				"hsv" :
				{
					"saturationGain" : 1.0500,
					"valueGain"      : 1.0000
				},
				"red" :
				{
					"threshold"  : 0.1900,
					"gamma"      : 2.0000,
					"blacklevel" : 0.0000,
					"whitelevel" : 1.0000
				},
				"green" :
				{
					"threshold"  : 0.1900,
					"gamma"      : 2.0000,
					"blacklevel" : 0.0000,
					"whitelevel" : 0.8000
				},
				"blue" :
				{
					"threshold"  : 0.1900,
					"gamma"      : 2.0000,
					"blacklevel" : 0.0000,
					"whitelevel" : 0.7300
				}	
				
				"id"   : "default",
				"leds" : "50-99",
				"hsv" :
				{
					"saturationGain" : 1.0500,
					"valueGain"      : 1.0000
				},
				"red" :
				{
					"threshold"  : 0.1900,
					"gamma"      : 2.0000,
					"blacklevel" : 0.0000,
					"whitelevel" : 1.0000
				},
				"green" :
				{
					"threshold"  : 0.1900,
					"gamma"      : 2.0000,
					"blacklevel" : 0.0000,
					"whitelevel" : 0.8000
				},
				"blue" :
				{
					"threshold"  : 0.1900,
					"gamma"      : 2.0000,
					"blacklevel" : 0.0000,
					"whitelevel" : 0.7300
				}
			}
		],

**Comment by edwinvd1** [comment]
I like LEDs "*" Changing in LEDs "0-49" does nothing more

**Comment by edwinvd1** [comment]
can someone help me I really can not.

**Comment by tpmodding** [comment]
any updates?

**Comment by edwinvd1** [comment]
no nothing is working.

**Comment by edwinvd1** [comment]
"color" :
	{
		"correction" :
		[
			{
				"id"   : "eerst",
				"leds" : "0-49",
				"correctionValues" :
				{
					"red" 	: 255,
					"green"	: 255,
					"blue" 	: 255
				}
			}
		],
		"temperature" :
		[
			{
				"id"   : "eerst",
				"leds" : "0-49",
				"temperatureValues" :
				{
					"red" 	: 255,
					"green"	: 255,
					"blue" 	: 255
				}
			}
		],
		"transform" :
		[
			{
				"id"   : "eerst",
				"leds" : "0-49",
				"hsv" :
				{
					"saturationGain"	: 1.0000,
					"valueGain"		: 1.0000
				},
				"hsl" :
				{
					"saturationGain"	: 1.0000,
					"luminanceGain"	: 1.0000
				},
				"red" :
				{
					"threshold" 	: 0.0000,
					"gamma"     	: 1.0000,
					"blacklevel"	: 0.0000,
					"whitelevel"	: 1.0000
				},
				"green" :
				{
					"threshold" 	: 0.0000,
					"gamma"     	: 1.0000,
					"blacklevel"	: 0.0000,
					"whitelevel"	: 1.0000
				},
				"blue" :
				{
					"threshold" 	: 0.0000,
					"gamma"     	: 1.0000,
					"blacklevel"	: 0.0000,
					"whitelevel"	: 1.0000
				}
			}
		],
,
		"correction" :
		[
			{
				"id"   : "laatst",
				"leds" : "50-99",
				"correctionValues" :
				{
					"red" 	: 255,
					"green"	: 255,
					"blue" 	: 255
				}
			}
		],
		"temperature" :
		[
			{
				"id"   : "laatst",
				"leds" : "50-99",
				"temperatureValues" :
				{
					"red" 	: 255,
					"green"	: 255,
					"blue" 	: 255
				}
			}
		],
		"transform" :
		[
			{
				"id"   : "laatst",
				"leds" : "50-99",
				"hsv" :
				{
					"saturationGain"	: 1.0000,
					"valueGain"		: 1.0000
				},
				"hsl" :
				{
					"saturationGain"	: 1.0000,
					"luminanceGain"	: 1.0000
				},
				"red" :
				{
					"threshold" 	: 0.0000,
					"gamma"     	: 1.0000,
					"blacklevel"	: 0.0000,
					"whitelevel"	: 1.0000
				},
				"green" :
				{
					"threshold" 	: 0.0000,
					"gamma"     	: 1.0000,
					"blacklevel"	: 0.0000,
					"whitelevel"	: 1.0000
				},
				"blue" :
				{
					"threshold" 	: 0.0000,
					"gamma"     	: 1.0000,
					"blacklevel"	: 0.0000,
					"whitelevel"	: 1.0000
				}
			}
		],

**Comment by edwinvd1** [comment]
No LEDs light up.
not even the rainbow does.
Hyperion does not start even with these settings.

**Comment by edwinvd1** [comment]
my debug looks.

terminate called after throwing an instance of 'std::runtime_error'
  what():  Failed to parse configuration: * Line 110, Column 1
  Missing '}' or object member name

**Comment by tpmodding** [comment]
what(): Failed to parse configuration: * Line 110, Column 1
Missing '}' or object member name

can you recheck this?

**Comment by edwinvd1** [comment]
OpenELEC:~ # sh /storage/hyperion/bin/hyperiond.sh /storage/.config/hyperion.con
fig.kodi.json
Hyperion Ambilight Deamon
        Version   : V1.01.1 (brindosch-d4ad877/fc7bc3c-1458755689
        Build Time: Mar 23 2016 14:20:16
INFO: Selected configuration file: /storage/.config/hyperion.config.kodi.json
HYPERION INFO: ColorTransform 'laaste' => [0-49]
HYPERION INFO: ColorCorrection 'laaste' => [0-49]
HYPERION INFO: ColorCorrection 'laaste' => [0-49]
LEDDEVICE INFO: configuration:
{
        "colorOrder" : "rgb",
        "name" : "MyHyperionConfig",
        "output" : "/dev/spidev0.0",
        "rate" : 250000,
        "type" : "ws2801"
}

HYPERION (C.correction) ERROR: No correction set for 50
HYPERION (C.correction) ERROR: No correction set for 51
HYPERION (C.correction) ERROR: No correction set for 52
HYPERION (C.correction) ERROR: No correction set for 53
HYPERION (C.correction) ERROR: No correction set for 54
HYPERION (C.correction) ERROR: No correction set for 55
HYPERION (C.correction) ERROR: No correction set for 56
HYPERION (C.correction) ERROR: No correction set for 57
HYPERION (C.correction) ERROR: No correction set for 58
HYPERION (C.correction) ERROR: No correction set for 59
HYPERION (C.correction) ERROR: No correction set for 60
HYPERION (C.correction) ERROR: No correction set for 61
HYPERION (C.correction) ERROR: No correction set for 62
HYPERION (C.correction) ERROR: No correction set for 63
HYPERION (C.correction) ERROR: No correction set for 64
HYPERION (C.correction) ERROR: No correction set for 65
HYPERION (C.correction) ERROR: No correction set for 66
HYPERION (C.correction) ERROR: No correction set for 67
HYPERION (C.correction) ERROR: No correction set for 68
HYPERION (C.correction) ERROR: No correction set for 69
HYPERION (C.correction) ERROR: No correction set for 70
HYPERION (C.correction) ERROR: No correction set for 71
HYPERION (C.correction) ERROR: No correction set for 72
HYPERION (C.correction) ERROR: No correction set for 73
HYPERION (C.correction) ERROR: No correction set for 74
HYPERION (C.correction) ERROR: No correction set for 75
HYPERION (C.correction) ERROR: No correction set for 76
HYPERION (C.correction) ERROR: No correction set for 77
HYPERION (C.correction) ERROR: No correction set for 78
HYPERION (C.correction) ERROR: No correction set for 79
HYPERION (C.correction) ERROR: No correction set for 80
HYPERION (C.correction) ERROR: No correction set for 81
HYPERION (C.correction) ERROR: No correction set for 82
HYPERION (C.correction) ERROR: No correction set for 83
HYPERION (C.correction) ERROR: No correction set for 84
HYPERION (C.correction) ERROR: No correction set for 85
HYPERION (C.correction) ERROR: No correction set for 86
HYPERION (C.correction) ERROR: No correction set for 87
HYPERION (C.correction) ERROR: No correction set for 88
HYPERION (C.correction) ERROR: No correction set for 89
HYPERION (C.correction) ERROR: No correction set for 90
HYPERION (C.correction) ERROR: No correction set for 91
HYPERION (C.correction) ERROR: No correction set for 92
HYPERION (C.correction) ERROR: No correction set for 93
HYPERION (C.correction) ERROR: No correction set for 94
HYPERION (C.correction) ERROR: No correction set for 95
HYPERION (C.correction) ERROR: No correction set for 96
HYPERION (C.correction) ERROR: No correction set for 97
HYPERION (C.correction) ERROR: No correction set for 98
HYPERION (C.correction) ERROR: No correction set for 99
terminate called after throwing an instance of 'std::runtime_error'
  what():  HYPERION ERROR: Color correction incorrectly set
Aborted (core dumped)

**Comment by edwinvd1** [comment]
I get this message now

**Comment by Sotnikov** [comment]
Have a same problem, any solution?
Version : V1.01.1

**Comment by Sotnikov** [comment]
@edwinvd1 i have found a solution, if u need help please i can help you

**Comment by Sotnikov** [comment]
my right config is `"transform" :
		[
			{
				"id"   : "default",
				"leds" : "*",
				"hsv" :
				{
					"saturationGain"	: 1.0000,
					"valueGain"		: 1.0000
				},
				"hsl" :
				{
					"saturationGain"	: 1.0000,
					"luminanceGain"	: 1.0000
				},
				"red" :
				{
					"threshold" 	: 0.0000,
					"gamma"     	: 1.0000,
					"blacklevel"	: 0.0000,
					"whitelevel"	: 0.9000
				},
				"green" :
				{
					"threshold" 	: 0.0000,
					"gamma"     	: 1.0000,
					"blacklevel"	: 0.0000,
					"whitelevel"	: 0.8500
				},
				"blue" :
				{
					"threshold" 	: 0.0000,
					"gamma"     	: 1.0000,
					"blacklevel"	: 0.0000,
					"whitelevel"	: 0.3000
				}
			},
			{
				"id"   : "top",
				"leds" : "20-47",
				"hsv" :
				{
					"saturationGain"	: 1.0000,
					"valueGain"		: 1.0000
				},
				"hsl" :
				{
					"saturationGain"	: 1.0000,
					"luminanceGain"	: 1.0000
				},
				"red" :
				{
					"threshold" 	: 0.0000,
					"gamma"     	: 1.0000,
					"blacklevel"	: 0.0000,
					"whitelevel"	: 0.6000
				},
				"green" :
				{
					"threshold" 	: 0.0000,
					"gamma"     	: 1.0000,
					"blacklevel"	: 0.0000,
					"whitelevel"	: 1.0000
				},
				"blue" :
				{
					"threshold" 	: 0.0000,
					"gamma"     	: 1.0000,
					"blacklevel"	: 0.0000,
					"whitelevel"	: 0.2500
				}
			}
		],`

**Comment by edwinvd1** [comment]
Thanks.
it works half.
I will continue to work the next few days here.

**Comment by brindosch** [comment]
you need to assign all your leds, you could create as much sections as you want
https://hyperion-project.org/threads/2-sets-of-lights.62/#post-708
