### ISSUE TITLE
[Wiki Article] PhilipsHue Documentation

### ISSUE THREAD

**Issue by brindosch** [hyperion-project/hyperion#587]
@ntim 
We are moving slowly forward, but we need a PhilipsHue device wiki article, we don´t own them and you may be the only person that we could reach for a proper documentation that explains the usage of the device settings

**Comment by ntim** [comment]
My fork contains a wiki entry on the hue, I can migrate it if you like but please have a look first.

**Comment by ntim** [comment]
My fork contains a wiki entry on the hue, I can migrate it as soon as github is running normal again, if you like but please have a look first.

**Comment by brindosch** [comment]
After a quick look, very good. Maybe some more things.
As a dump user and not owning them:
"lightIds"   : [...] Where do i get that ID´s? May that know every person? (i don´t know how visible they are)
You could add a short description about LED config <> amount of hue bulbs and maybe a short mention of the hscan vscan (what is left/right - and order? First led > first ID(or all  ids))

thank you for all efforts!

**Comment by ntim** [comment]
Ok, added a small comment on how to get the light ids. The rest will follow. Do you then copy the text to the hyperion wiki?

**Comment by brindosch** [comment]
Just push the article to the hyperion wiki and ping me, cause you never get a notice if someone delete the whole wiki

**Comment by apurbas** [comment]
Since I have a hue setup, I can contribute as well.

**Comment by ntim** [comment]
Would appreciate!

**Comment by brindosch** [comment]
@ntim 
I have a small problem, i cant add your light ids section to hypercon, i can´t create with the present implementation a [1] or [1,2,56,89]. Is could just a string formatted like this "1,2,56,89"

**Comment by ntim** [comment]
Mmh, I will have a look into the hypercon source code. Would like to keep making use of the possibilities of JSON here, since it directly gives me an array and I do not have to parse a string.

**Comment by brindosch** [comment]
You could have a look, the construction is very simple as you see.

**Comment by ntim** [comment]
Ah it is to early, I can not find the source of HyperCon

**Comment by apurbas** [comment]
getting started guide to Philips Hue. Configuring through Hypercon will be next![getting started with philips hue on hyperion](https://cloud.githubusercontent.com/assets/16624176/14308474/07473388-fbf4-11e5-9c58-de2d87bba998.jpg)

**Comment by brindosch** [comment]
nice picture :) Have you done that?
Please note that we have no light ids in hypercon. But we a working on it :)

**Comment by apurbas** [comment]
Yup just noticed this conversation on light ids. I made this. Please feel free to use it in wiki or will edit as per @ntim suggestion.

**Comment by RickDB** [comment]
For the JSON array light ID saving in HyperCon issue I added this fix for AtmoOrb which isn't perfect but the best C++ solution I could find:

https://github.com/tvdzwan/hyperion/blob/Beta/libsrc/leddevice/LedDeviceFactory.cpp#L260-277

On the receiving end (device code) it's still the same list however the config structure will comply with Hypercon this way.

**Comment by ntim** [comment]
Mmh, would really fix that issue in HyperCon rather than in the LedDeviceFactory. We have JSON, then lets make use of the standard instead of re-implementing it.

**Comment by brindosch** [comment]
@apurbas 
a big thank you for this too!
I am glad that the hyperion community is helpfully that much! I didn´t expected!

**Comment by RickDB** [comment]
Same here, fixing it HyperCon would be preferred but might take some doing :)
If you guys do find a solution so that it can support JSON formatted lists will update AtmoOrb config code as it will make things a bit simpler.

**Comment by apurbas** [comment]
Thank you @brindosch. I assume we will have to live with (..for sometime) manual edit of the Hyperion.config.json from Hypercon. So here is fine tune guide - 
![fine tune config file](https://cloud.githubusercontent.com/assets/16624176/14327378/a46a38b2-fc4f-11e5-9410-4ea356a2c833.jpg)

**Comment by ntim** [comment]
Hi, copied the wiki-page to

https://github.com/tvdzwan/hyperion/wiki/Philips-Hue-Support

@apurbas can you integrate your graphics, they look really great!

**Comment by apurbas** [comment]
Go ahead @ntim

**Comment by ntim** [comment]
@brindosch I am not allowed to add these images to the wiki repo

**Comment by ntim** [comment]
@apurbas do you have higher resolution images I can put into the wiki?

**Comment by apurbas** [comment]
I do have. Will update.

**Comment by brindosch** [comment]
@apurbas 
Nice images yes!
@ntim 
Can´t change permissions?! But is should work? Or is this just me? I tested see commit.

**Comment by brindosch** [comment]
I am working on a complete hypercon guide, the config edit is not what i want to achieve with it :)

**Comment by brindosch** [comment]
@apurbas 
could you upload the bigger pictures? Thank you

**Comment by apurbas** [comment]
Does this work with you? Else I will make it even sharper..
https://www.hightail.com/download/ZWJYUWV0bTg5bEJsQXNUQw
https://www.hightail.com/download/ZWJYUWV0bThoeVlFSzhUQw

**Comment by ntim** [comment]
The fonts still look very mushy, please export as png (no compression loss) in 1080p or something or vector graphics.

**Comment by apurbas** [comment]
Ok, pngs here
https://www.hightail.com/download/ZWJYUWV0Q1I1bmp2bk1UQw
https://www.hightail.com/download/ZWJYUWV0Q1JveE5vSWNUQw

**Comment by brindosch** [comment]
Thank you for your contribution :)
