### ISSUE TITLE
[Hyperion Beta (V1.02.0)] Feedback 

### ISSUE THREAD

**Issue by brindosch** [hyperion-project/hyperion#588]
I am sure some people tested it already, i would gather some feedback about the new color calibration and the new guide.

After a short test, i have to say - 1000 thanks to @AEtHeLsYn my R/G/B is as near as perfect now!
But i have to admit, i don´t understand the calibration with the grey pictures, it seams it "doesn´t matter" which gamma value i set. As long they stays the same (example 2,5 2,5 2,5) for RGB it changes "nothing" that is -really- visible? this leads to the problem that i have now poor colors in between (example cyan picture)

Yes, i have done it wrong, but may be like a normal user would understand it.
If i setting up my gamma with the color pictures in between it should work?!
Maybe we add a additional small hint.

A problem that bothers me and i really fear the next version push
-> Android App | The issue flamewar may be big 
We don´t have the source code, if i saw that right. I will ask tvdzwan for this.
Have someone android app skills and may have the time to modify it? 

Just my thoughts - keep it commented :)

**Comment by RickDB** [comment]
Was wondering how the Android app was gonna be handled, could ask @poljvd the developer of that app if he can update it so that it works with the updated color calibration options.
And release a new version at the same time as Hyperion gets a stable release to avoid issues.

Played a bit with the Beta branch however couldn't get it calibrated perfectly yet, probably doing something wrong or maybe for apa102 its harder to get them setup properly but will test it further today.

**Comment by brindosch** [comment]
We could reach poljvd with tvdzwan :)

**Comment by AEtHeLsYn** [comment]
@brindosch 
You are doing it right. The grey pictures are intended to let the leds stay gray all the way. I mean, my half-grey was a bit reddish so I had to increase gamma until I got a perfect gray. With those gray pictures what you need to get is the same grey levels, not greenish, reddish or bluish. 

@RickDB 
I have apa102 too and its a bit harder to setup, but I got it after an hour or so. Now we have all the required color modification options, it's only a matter of setup lets properly. The color of the wall is pretty much involved too.

And btw, the Android app will still be working, but won't be able to set the new transform options. At this moment we should not delete commands, only mark them as deprecated (as @brindosch already did on hyperion-remote)

**Comment by brindosch** [comment]
@AEtHeLsYn 
i also own apa102, at which setting did you played around for 1 hour? I have no greenish/redish/blueish grey, but cyan and all other colors in between are a mess, So my gamma is wrong and i have to...? :goat:

**Comment by AEtHeLsYn** [comment]
@brindosch 
I had to adjust the green gamma value and the red component of the green colour. Those are my settings, but my wall has cream color, not white, so it's even harder to adjust.

```
"color" :
	{
		"temperature" :
		[
			{
				"id"   : "default",
				"leds" : "*",
				"temperatureValues" :
				{
					"red"   : 255,
					"green" : 255,
					"blue"  : 255
				}
			}
		],
		"channelAdjustment" : 
		[
			{
				"id"   : "default",
				"leds" : "*",
				"pureRed" :
				{
					"redChannel"	: 175,
					"greenChannel"	: 20,
					"blueChannel"	: 10
				},
				"pureGreen" :
				{
					"redChannel"	: 30,
					"greenChannel"	: 220,
					"blueChannel"	: 5
				},
				"pureBlue" :
				{
					"redChannel"	: 10,
					"greenChannel"	: 10,
					"blueChannel"	: 255
				}			
			}		
		],		
		"transform" :
		[
			{
				"id"   : "default",
				"leds" : "*",
				"hsl" :
				{
					"saturationGain" : 1.2000,
					"luminanceGain"  : 1.0000
				},
				"red" :
				{
					"threshold"  : 0.0000,
					"gamma"      : 1.8500,
				},
				"green" :
				{
					"threshold"  : 0.0000,
					"gamma"      : 2.0000,
				},
				"blue" :
				{
					"threshold"  : 0.0000,
					"gamma"      : 2.6500,
				}
			}
		],
	},
```

**Comment by brindosch** [comment]
@AEtHeLsYn 
I thought about to change HyperCon again.
![unbenannt](https://cloud.githubusercontent.com/assets/15967679/14366279/365cbe76-fd12-11e5-903c-550313ee203c.JPG)
It may be too confusing now, i want to move the the red marked values to a new row called "White" or "WhiteChannel". The current field positions will be just empty then.
What do you think about the idea?

**Comment by AEtHeLsYn** [comment]
@brindosch 
It would be more useful if we explain that Red is max,0,0; Green is 0,max,0 and Blue is 0,0,max, and the white if the result of adding the three colors (max, max, max). That way everyone can understand what they are doing.

**Comment by brindosch** [comment]
I know my idea is completely misleading in developer view, cause it is wrong in any way.
But just another example
![unbenannt](https://cloud.githubusercontent.com/assets/15967679/14377841/385e2b00-fd72-11e5-8504-7cbd1685e118.PNG)
I think it is confusing, even if you know what you have to touch! It is easy to screw up your white when you adjust the colors. Too much spinners. The orientation is very bad.
And to be honest, we all know that people can´t read. They may start open issue because of white, if i have still problems to keep the overview with that spinners.
You don´t have this chance in the .conf but the overview at the conf is much better!

Who bring me on this idea? A user at the rpiforum with a screwed up white, and he thought the white calibration easy with your guide... he also could follow the compilehowto.txt. not all user could follow/understand things that fast.
I fear the issues that will plop up, i don´t want to handle that. It is our wasted lifetime.
And they even plop up now sometimes.

Could you follow me?

**Comment by AEtHeLsYn** [comment]
Of course, I agree with that. Anyway I really don't know how to split whiteleveling from colors. Your initial idea may be good, but i think it will be misleading too, as you will be able to modify the "redChannel" only with green and blue. Maybe we can try and wait for some user feedback.

**Comment by brindosch** [comment]
Maybe i should complete it more,
this is just visual! I would remove the .conf snippet out of the guide and place a picture of the instead. The HypCon don´t interest anyway what is inside the conf. And all other will be know what is going on (hope so)

**Comment by AEtHeLsYn** [comment]
Yes, the easier the better, we must avoid misleadings

**Comment by brindosch** [comment]
This is ok for you? Or should we gather more comments?

**Comment by AEtHeLsYn** [comment]
I see it ok, but just because I know what I am doing. If you change the configuration parameters with images will even be easier for the final user, so I totally agree with the idea.

**Comment by brindosch** [comment]
![unbenannt](https://cloud.githubusercontent.com/assets/15967679/14382219/580536b4-fd8c-11e5-9c3a-8f3db0afb379.PNG)

**Comment by brindosch** [comment]
To much holes? looks not so nice. Maybe this?
![unbenannt](https://cloud.githubusercontent.com/assets/15967679/14382355/7001d5dc-fd8d-11e5-823c-ffcad5358bac.PNG)

**Comment by RickDB** [comment]
Can also try tabbed panes if the current UI allows for it, like so:

https://docs.oracle.com/javase/tutorial/uiswing/components/tabbedpane.html

That way you can split the different calibration groups (white / pure etc..) into different tabs to avoid confusion.

**Comment by brindosch** [comment]
Tabbed panes is also a idea. Now i have a solution that looks quite better.
![unbenannt](https://cloud.githubusercontent.com/assets/15967679/14382768/8b867e90-fd90-11e5-9389-e99553537d4b.PNG)
Good or good?

**Comment by AEtHeLsYn** [comment]
I like a lot the last idea, it is very intuitive.

**Comment by sgtriggs** [comment]
Curious about the Beta as I'm having a hard time getting good colour calibration.  How would I go about installing the Beta over the Master?

**Comment by tpmodding** [comment]
just the replace the binaries

**Comment by brindosch** [comment]
Nope, never uploaded. You need to follow the compilehowto.txt

**Comment by sgtriggs** [comment]
Cool beans, I'll give it a go in a while.  Thanks for the info brindosch

**Comment by sgtriggs** [comment]
Ok, so I'm having a crack at the calibration today but can't get past the first step.  Adjusting the Red/Green/Blue of each PureColor isn't actually making a difference.  I'm starting with a fairly pink-hue white and adjusting the Red of PureRed, even down to <100 levels makes no difference in the LED color.

Am I doing something wrong?  Is my config file broken?

Changing other settings (correction values, saturation etc) changes the colors...

Here's the current "blank" config file I'm using;
[http://pastebin.com/hFDMV3Ft](url)

**Comment by AEtHeLsYn** [comment]
@sgtriggs 
Did you compile the Beta code?? Setting a value of 150 of red channel of pureRed does the exact same operation as setting a red correction value of 150. I mean... is the exact same function ;)

**Comment by sgtriggs** [comment]
Hmm, nope, oops.  I followed the CompilwHowTo.txt and it appears I've compiled the Master release.  How do I specify I want to compile the Beta?

Thanks (an embarrassed Linux noob!)

**Comment by RickDB** [comment]
Change the following from the guide:

`
git clone --recursive https://github.com/tvdzwan/hyperion.git "$HYPERION_DIR"
`
to:

`
git clone -b Beta --recursive https://github.com/tvdzwan/hyperion.git "$HYPERION_DIR"
`

**Comment by sgtriggs** [comment]
Thanks for the help @RickDB @AEtHeLsYn 

Recompiled and working fine with my config.

**Comment by AEtHeLsYn** [comment]
@sgtriggs 
You are welcome. Would be useful if you write some feedback about new color adjustment functions

**Comment by stefanheijnen** [comment]
I've compiled the beta and copied the binaries to my RPi with OpenELEC 6.0.3. Now I get this error when I start Hyperion:

> /storage/hyperion/bin/hyperiond: error while loading shared libraries: libpython3.4m.so.1.0: cannot open shared object file: No such file or directory

How do I install this file without apt and the readonly filesystem from OpenELEC?

**Comment by AEtHeLsYn** [comment]
@stefanheijnen 
You need to compile hyperion with Python 2.7 support, not 3.4m. Following the guide, after you execute cmake.. And BEFORE make, edit the CMakeCache file inside build dir and change 3.4m by 2.7, everyone of them. After that execute cmake again and then you can follow the guide.

**Comment by brindosch** [comment]
we still compile with older libs to prevent problems with raspbian wheezy and older linux builds

**Comment by stefanheijnen** [comment]
I've successfully compiled Hyperion with Python 2.7, it's up and running. Time to try out the new color calibration!

**Comment by brindosch** [comment]
@stefanheijnen 
Your outcomes?

**Comment by brindosch** [comment]
Hyperion have a new home!
Please read the announcement post and the changelog for V1.02.0
www.hyperion-project.org

Please have a look at our new wiki! (EN/DE)
wiki.hyperion-project.org

All discussions/questions/development threads should be moved to the new forum!
We will close this issue now

**Comment by stefanheijnen** [comment]
Everything works as expected @brindosch

**Comment by brindosch** [comment]
@stefanheijnen 
Great! :D

**Comment by NicoHood** [comment]
I cannot see any version tag for the release:
https://hyperion-project.org/threads/hyperion-hypercon-v1-02-0-released.21/

https://github.com/hyperion-project/hyperion/releases

I wanted to rebuild the release myself but I do not know the git state.
Also there are multiple branches with versions as name? You should rather use tags than branches for different versions and the master as current dev version. So I do not even know which branch/tag i should build. Please make this more clear.
