### ISSUE TITLE
Hyperion on other SoC- or MCU-based  Boards

### ISSUE THREAD

**Issue by 7h30n3** [hyperion-project/hyperion#589]
Hey,

I'm using Hyperion for Ambilight since  long time with my RaspPi2 and now RaspPi3 and OpenELEC. I'm very happy with it.

Now I want to equip my flat with more LED-stripes using Hyperion, but I don't want to buy a RaspberryPi for every LED-strip.
So is there a way to use Hyperion on even cheaper SoC- or MCU-based Boards like Adruino?
Or at least a "light version" without framegrabber which uses the same commads to remotely set colors?

**Comment by penfold42** [comment]
How about an arduino/ESP8266 based led driver that listens to UDP packets?

https://github.com/tvdzwan/hyperion/wiki/Network-and-distributed-features#udp-led-device-support

**Comment by stefansaraev** [comment]
well, I am using hyperion on openelec/wetek core with DYI adalight like solution using esp8266 (esp-01) + pl2303 serial converter and ws8212b strip. an esp + serial convertor is ~ $5 on ebay, but I'd bet atmega328p nano will do the same job for the same price.

**Comment by 7h30n3** [comment]
For another project using node.js I wanna develop an extension/service to control hyperion clients. The module I'm using for this is https://github.com/WeeJeWel/node-hyperion-client which uses JSON websocket to send the commands. So the best case scenario would be if the hyperion client would "understand" JSON. ....or I just look for a module to convenietly send UDP packets.

**Comment by brindosch** [comment]
for nodeMCU, i am not sure if this fit your needs. You could use the hyperion fordwarder.
https://github.com/SciLor
a german short tutorial http://www.forum-raspberrypi.de/Thread-hyperion-tutorial-esp8266-nodemcu-addon-wifi-led-controller-udp

**Comment by brindosch** [comment]
Done? Done
/cleanup - for further discussion - forum
https://hyperion-project.org
