### ISSUE TITLE
grabber-v4l2 with openelec on raspberry pi2

### ISSUE THREAD

**Issue by dors1** [hyperion-project/hyperion#591]
Hi,
First of all, sorry about my English.

I installed the last version of OpenElec on raspberry pi 2, using Hyperion and USB Video Grabber.
The ambilight is working ok with kodi, but not with external video source, when i take a screenshot all i can see is green lines or black screen, i tried to modify the config file but apparently with no success.
What should i do to resolve this issue?
Thanks

**Comment by brindosch** [comment]
Hello dors1,
it is normal that you get often green lines at the picture (screenshot), as long as you have no problems with "green leds" all is good.
Could you upload pictures of your v4l2 screenshot? Do you get sometimes picturs without green lines?

**Comment by dors1** [comment]
Hi,
The main issue is that my ws2801 is not working with external video source, only with kodi.
I tried to get a screenshot right now and all i get is a black screen,  i did not get any pictures, just black screen or green lines (with black screen).
Thank you for the help

**Comment by brindosch** [comment]
is it a utv007? Are you using a hdmi to cvbs converter too?

**Comment by dors1** [comment]
I managed to get a picture, is it ok? thanks

![screenshot](https://cloud.githubusercontent.com/assets/18375739/14408993/8b692830-ff12-11e5-8433-44def2bf203e.png)

**Comment by brindosch** [comment]
1. In any case - it is no hyperion issue
2. which usb grabber are you using?
3. it is possible that the connection is bad
4. maybe a power fault, be sure you have enough
5. could you check without a hdmi to cvbs converter? maybe you hdmi to cvbs is damaged?

**Comment by tpmodding** [comment]
and please post your configs on pastebin.com and share the urls with us

**Comment by RickDB** [comment]
Try switching between PAL and NTSC on the hdmi to cvbs converter or screenshot grabber as that can help sometimes.

**Comment by brindosch** [comment]
@dors1 
News?

**Comment by tpmodding** [comment]
no answer...
