### ISSUE TITLE
How to install Hyperion in Retropie?

### ISSUE THREAD

**Issue by cmvac** [hyperion-project/hyperion#592]
Hi guys, I have a Raspberry Pi 2 with both Openelec and Retropie installed (dual boot). Hyperion is working fine on OpenELEC but when I start Emulation Station, I have no ambilight effect. The LEDs just freeze. Also when I go back to OpenELEC, the autostart.sh script doesn't kick in and Hyperion doesn't start. I have to start it manually. 

Any idea how to install hyperion on Retropie?

**Comment by brindosch** [comment]
dual boot mean, you have two separated partitions that you choose on startup? it make no sense that back on openelec it won´t work. if you really dualboot?!

**Comment by cmvac** [comment]
@brindosch Sort of... I have two partitions on the mSD card, but it starts up with Openelec. On Openelec I have a script which quits Openelec, reboots and launches Retropie. I then do the same to get back into Openelec. I got the dual boot done through this link: http://blog.petrockblock.com/forums/topic/retropie-multi-boot-images/

Actually let me correct something: autostart.sh does start Hyperion when getting back to OpenELEC, don't know why it didn't work yesterday. 

I did find a video on youtube (https://www.youtube.com/watch?v=g0do7WG6lfk) where on the first comments someone says the following: 

"The easiest guide to follow would be on Hyperion's wiki. OpenELEC locks the user down somewhat in terms of what they can install and where, which is why the OpenELEC guide is a bit different. If you follow the RaspBMC guide, you should get it working. Make sure you also check to see if the SPI has been enabled (I can't remember I needed to do this but it's always best to check). https://github.com/tvdzwan/hyperion/wiki/installation﻿"

But this is one year old.

**Comment by cmvac** [comment]
@brindosch, any news about this issue? Did you try Retropie with Hyperion according to the video's description? It would be sweet if Hyperion would work on Retropie as well! It could even be added to the OS' supported by Hyperion on the wiki page.

**Comment by brindosch** [comment]
I am sorry, not enough time atm. Did you try to install hyperion e second time on the retropie partition? someone wrote that he could use the retropie image and hyperion. so it should still be possible in a way. But i will investigate this if i find some time for it.

**Comment by cmvac** [comment]
@brindosch I followed the normal Raspbian tutorial, since Retropie is based on that OS, and tried to install Hyperion on the corresponding partition. I've been talking to the developer of PiPPLWare, also a Raspberry Pi combo distro, and he also confirmed me it should work. I don't get it. 

When I run these commands, I get this:

root@retropie:~# sudo service hyperion start
Starting hyperiond...                             Ok
root@retropie:~# sudo service hyperion stop
Stopping hyperiond                                /etc/init.d/hyperion: line 62: kill: (3295) - No such process
Ok

And no lightshow... :(

**Comment by penfold42** [comment]
Instead of using the service, why don't you try:
hyperiond /etc/hyperion.config.json

**Comment by cmvac** [comment]
Running that command I got this: 

hyperiond: error while loading shared libraries: libpython2.7.so.1.0: cannot ope                                                                                        n shared object file: No such file or directory

**Comment by cmvac** [comment]
also on sudo service hyperion status, I got:
Checking hyperiond...                             Process dead but pidfile exists

**Comment by brindosch** [comment]
Also this dualboot thing may manipulate too much? It seams it is not a true dualboot. No python 2.7 found. If it is a true dualboot you could choose between openelec and the original retropie partition. Anything other needs some hacking, but due to the point the original image is working i would use this instead (And create with this a true dualboot)

I tested with the original retropie image (newest 3.7)
It seams that the image you are using is older than the current (you use init.d and i use systemd with the latest retropie 3.7 image)
I just installed hyperion, inserted my config and rebooted (due to spi activation)
Works quite good
Sad that i own no controllers atm :smile_cat: 
![unbenannt](https://cloud.githubusercontent.com/assets/15967679/14603263/00fc5d96-056d-11e6-8af5-cd32a230dd98.PNG)

**Comment by penfold42** [comment]
Looks like you need to install Python 2.7

**Comment by brindosch** [comment]
Maybe you are interested at this new RetroPie feature.
https://github.com/RetroPie/RetroPie-Setup/wiki/KODI

**Comment by cmvac** [comment]
@brindosch and @penfold42, I read something about that here: 
http://www.forum-raspberrypi.de/Thread-hyperion-retropie-process-dead-but-pidfile-exists 
But the thread ends up not giving the solution for that issue. 

EDIT: I just installed Python through this:
sudo apt-get install python-dev
curl -O http://python-distribute.org/distribute_setup.py

And it is working! :

Thank you guys! You are the greatest!

**Comment by penfold42** [comment]
Yay !

**Comment by brindosch** [comment]
Good :)

**Comment by TylonHH** [comment]
@cmvac wich dualboot manager are you using?

**Comment by cmvac** [comment]
@TylonHH, I used an image taken from the Retropie Project website. It is available here: http://blog.petrockblock.com/forums/topic/retropie-multi-boot-images/
