### ISSUE TITLE
Can I connect IKEA DIODER Leds?

### ISSUE THREAD

**Issue by fhennig** [hyperion-project/hyperion#593]
Hi, I am using the [IKEA DIODER](http://www.ikea.com/us/en/catalog/products/50192365/) led strips. I wrote my own client server code to control them, but hyperion is way better, the app is already there which is something I would like to have. 

However, it seems like devices like the one I am using are not currently supported? I have connected the 4 led strips each with 3 pins, one for each color. So for example I've got strip1 R on pin 11, G on pin 10, B on pin 6. And so on for the other 3 strips. Each color is controlled with software PWM, I'm currently using some java library for that. the actual power to the leds is provided via a transistor setup.

Is it possible to control them with hyperion? If not, where is the best place to start looking into the code if I want to add support for them?

I know it's kind of a shitty ambient light if you only have one led per side, but I've already got the hardware so it would be neat to use it like that. Also I'd love to program my own effects.

**Comment by tpmodding** [comment]
sorry i have only a german tutorial for
http://www.forum-raspberrypi.de/Thread-hyperion-tutorial-ambilight-mit-standard-led-strips

but it should work with piblaster?

**Comment by fhennig** [comment]
Looks good, but I have four individual led strips, can this work as well? The relevant configuration part seems to be `"assignment" : " r   g b "` and it doesn't look like there is support for more than one led strip.

Also, on [https://github.com/tvdzwan/hyperion/wiki/Hardware](this) wiki page, the link to piblaster is broken.

**Comment by penfold42** [comment]
You Might be better is hanging an Arduino off the pi to do the low level stuff.

You could use serial, USB or SPI and make it look like an adalight or ws2801 device with only 2 or 3 logical LEDs.

**Comment by fhennig** [comment]
I've got these 4 strips, each should be a logical RGB led, so 4 logical leds. 

In hardware that is 4 * 3 pins used. 4 strips times 3 pins per strip, one for each color. 

I don't want to use another hardware device, it seems unnecessary, given that I've got all the hardware stuff already set up.
I'd like to have some config like 
```
[
  {"r": 15, "g": 16, "b": 1} # bottom
  {"r": 0, "g": 2, "b": 3} # left
  {"r": 8, "g": 9, "b": 7} # top
  {"r": 12, "g": 13, "b": 4} # right
]
```

each pin is a digital pin and should be controlled with software pwm, like piblaster. Maybe the piblaster device which is already implemented could be extended to support more than one logical led?

**Comment by penfold42** [comment]
The pi-bolster  seems to support 8 pins which gives you 2 RGB LED (strips) but seems to support more.

Adding support should be easy - just write the correct data to its fifo.

We already have a device that just writes to a file.

**Comment by penfold42** [comment]
Just looked at the existing pi-blaster source in Hyperion.

It seems to do 9 channels so 3 strips should be easy with some tweaks

**Comment by penfold42** [comment]
Check out my pi-blaster branch. I've changed the way piblaster works to assume you want groups of 3 physical channels to map to RGB of a single hyperion LED.

I dont have real hardware, but i can see the data its writing to the FIFO looks correct now.

**Comment by brindosch** [comment]
Do we have a Piblaster docu? Oh noes -.-

**Comment by penfold42** [comment]
I just grabbed a single RGB led with resistor and it seems to work ok so far.

**Comment by fhennig** [comment]
I looked at your branch, the changes you made look good. I installed the default hyperion release on my pi without issues, but to get yours working I first need to look into the HowToCompile. Or maybe you can build a release?
Also, what's the pin numbering scheme that is used?

**Comment by penfold42** [comment]
I'll put a binary somewhere so you can test it.

The  numbers refer to the gpio nimber and then which hyperiond led color component is mapped to it

**Comment by penfold42** [comment]
https://github.com/penfold42/hyperion/blob/piblaster-fix/deploy/hyperiond.gz?raw=true

**Comment by fhennig** [comment]
Oh, could you also upload your config file?

**Comment by penfold42** [comment]
https://github.com/penfold42/hyperion/tree/piblaster-fix/deploy/pi-blaster-test

sample config and my improved version of pi-blaster

**Comment by fhennig** [comment]
I can confirm that it works!
Great work, thanks a lot!

**Comment by penfold42** [comment]
Great ! I'll make a pull request

**Comment by brindosch** [comment]
@penfold42 
If would really appreciate a wiki article for piblaster hyperion usage - how to :+1: 
It seams you know what you do - i have no idea about this :)

**Comment by brindosch** [comment]
/done

Hyperion have a new home!
Please read the announcement post and the changelog for V1.02.0
www.hyperion-project.org

Please have a look at our new wiki! (EN/DE)
wiki.hyperion-project.org

All discussions/questions/development threads should be moved to the new forum!
We will close this issue now

**Comment by hiulit** [comment]
Hey @fhennig 

I also have an IKEA Dioder and I'd like to use it with my Raspberry Pi (running RetroPie) as and 'amiblight' clone.
Could you point in the right direction? I've been looking on the Internet and I haven't found any tutorial explicitly for the Dioder and the Raspberry Pi.

Thanks!

**Comment by fhennig** [comment]
Hey,
I haven't set up ambilight but I have set up hyperion to control the dioder strips with the app.
[Here](https://hyperion-project.org/threads/raspberry-pi-3-mediacenter-hyperion-ambilight-no-soldering.77/) is a tutorial for setting up ambilight with hyperion. If you want to use your dioder LEDs you just don't buy the LEDs from the tutorial and instead connect your dioder LEDs. For that you need transistors or a chip with 4 transistors on it ideally. I'm not entirely sure which one I used but I think this one: ULN2003. You can also search for connecting the Dioder to an Arduino, because its basically the same setup. Also google "Darlington", thats the name of the chip type you need. 
For hyperion you then need a configuration, I uploaded [mine](http://pastebin.com/zBDd9QpP) (probably the same as the one mentioned earlier in this issue).
Also I'm not sure which build of the software you need, just read this issue for more info. I hope I could help!
Cheers!

**Comment by hiulit** [comment]
Alright! Thanks a lot!
I'll take a look into all that ;)
