### ISSUE TITLE
Hyperion forward OSMC issues

### ISSUE THREAD

**Issue by apurbas** [hyperion-project/hyperion#594]
Hey @brindosch - Just tested Hyperion proto/ json forward to Philips Hue on OSMC, Rpi-1. Individual jsons to APA LED strips on Rpi GPIO & Philips Hue resolves fine. That's when implemented forward on hyperion.config. And the issues starts from there -
1. APA strips works flawless as usual.
2. Philips Hue shows very frequent color flicks (not the rainbow swirl) between a static color & color provided by grabber. The flick reduces after sometime in some cases. 
3.Finally config2 halts stating either 
*** Error in `/opt/hyperion/bin/hyperiond': double free or corruption (!prev): 0x01dcf650 ***
Aborted
_or_ Segmentation fault

_or_
*** Error in `/opt/hyperion/bin/hyperiond': corrupted double-linked list: 0x00ca0fb0 ***
Aborted

In the last instance both the hyperiond fails/ halts.

http://pastebin.com/5QPU7LS8
This is something I can't figure out yet why this is occuring only on forward.

**Comment by brindosch** [comment]
I have to admit, i still had no time to play around with the forwarder (hardware is here since 2 weeks waiting for use...)
But i am sure we have some experts here :)

**Comment by apurbas** [comment]
hmm - would wait :-)

**Comment by brindosch** [comment]
//cleanup
