### ISSUE TITLE
Trouble with RPi 2 + ws2812b

### ISSUE THREAD

**Issue by brzezou** [hyperion-project/hyperion#596]
hello,
i tried to install hyperion... no succes :(
My config is : RPi 2 + osmc (4.4.6-3-osmc) + hyperion(v1.01.1) + ws2812b (on BCM18)

I followed this :
1) installed osmc
2) `wget -nv -N https://raw.github.com/tvdzwan/hyperion/master/bin/install_hyperion.sh`
3) `sudo sh ./install_hyperion.sh WS281X`
and if I try: `hyperion-remote --priority 50 --color red --duration 5000`nothing.
I have "hyperiond" proccessing after installation and after reboot, but no hyperion service.

I used oscilloscope (at work) and it seems there is nothing (no clock or pwm) on pin BCM18.

I hope this can help you to help me ^^.

**Comment by penfold42** [comment]
Please post your config file to pastebin

In particular what is your device type set to ?
There are 2 that support this strip but only ws281x supports the pi2/3

**Comment by brzezou** [comment]
Thanks for helping.
Here is my config file : http://pastebin.com/hwjbU2XA
But on this page [Supported/Working platforms](https://github.com/tvdzwan/hyperion/wiki/Supported-Working-platforms) it says "OSMC have problems with PWM LEDs directly connected". Is it still actual?

**Comment by brindosch** [comment]
Yes, the fastest for you may be a fast test with openelec to verify that your hardware is working.

**Comment by brzezou** [comment]
@brindosch
Thanks for suggestion. I did it this weekend.
IN configured hyperion to write into file test and it seems to work. But nothing with my hardware.
We are agree that with the few commands above (in my initial post) , its enought to work?!
I'll try with an oscilloscope to find where is the right output pin...

I haven't Arduino to verify if my strip led working.

**Comment by penfold42** [comment]
With th pi in front of you with the gpio header top left.
Top row 6 from the left is GPIO 18

**Comment by brzezou** [comment]
well... by default, i mean after OpenElec and hyperion intallation with :
`curl -L --output install_hyperion.sh --get https://raw.githubusercontent.com/tvdzwan/hyperion/master/bin/install_hyperion.sh
sh ./install_hyperion.sh WS281X`
The config file still had a device description as for ws2801 led strip... so no output on GPIO18.

After configuration with HyperCon of device type as "ws281x" and the right path to effect, nothing more on output...
here my device description :

> "device" :
> {
> 	"name" : "MyHyperionConfig",
> 	"type" : "ws281x",
> 	"led" : 256,
> 	"colorOrder" : "rgb"
> }

I'll continue later, time to work :)

**Comment by brzezou** [comment]
The thing that i haven't told, this weekend I had tried to write into files test instead of GPIO, and it seems to work...

**Comment by brzezou** [comment]
Finally...
At beginning, i changed the config file into /hyperion/config, instead of in .config/ file.
That's why i haven't signal on GPIO18.
Then, I had error to on my hardware interface (to pass signal at 3.3V to 5V), my data pin wasn't connected on the right pin of my connector.
Thanks for helping anyway :).
