### ISSUE TITLE
Can's set the priority in the official Android App

### ISSUE THREAD

**Issue by TylonHH** [hyperion-project/hyperion#598]
Hi,
It would be nice if I can set also the priority, because I use several remotes. One of them has the priority 1. So I can't overwrite that.

Cheers #

**Comment by brindosch** [comment]
https://github.com/b2un0/kodi-script-hyperion/issues/1

**Comment by BooStars** [comment]
brindosch: He is talking about Android, not Kodi ;-)

**Comment by brindosch** [comment]
I am talking too :)

**Comment by brindosch** [comment]
I think that is answered :)
