### ISSUE TITLE
 can't create /sys/class/rc/rc0/protocols: nonexistent directory

### ISSUE THREAD

**Issue by TylonHH** [hyperion-project/hyperion#604]
RPi3 openelec with WS2801**
**3.** Please upload your Hyperion log to pastebin.com and insert the link. Have a look at the wiki how you get one: not possible due errot
**4.** Please upload your "Hyperion Configuration File" to pastebin.com and insert the link: not confirm to handle copy&paste (yet) / irrelevant?!?!

Hi,

when I try to
`/storage/.config/autostart.sh`  
I got  
`/storage/.config/autostart.sh: line 3: OpenELEC:~ # can't create /sys/class/rc/rc0/protocols: nonexistent directory`
I tried to Mkdir that Dir with `mc` but i get an `Operation permitted`

**Comment by tpmodding** [comment]
... You kidding us?!
what does that have to do with hyperion ?

Please write what you want to do and what the exactly problem is... should we guess what is in your autostart.sh?!?!

**Comment by brindosch** [comment]
I am sure line 3 in your autostart.sh has nothing to do with hyperion itself :)

**Comment by TylonHH** [comment]
Sorry that I confused you with to less information.
thats my autostart.sh
`(
 echo +mce_kbd > /sys/class/rc/rc0/protocols;
 ) &
/storage/hyperion/bin/hyperiond.sh /storage/.config/hyperion.config.json > /dev/null 2>&1 &`

when I just run `/storage/hyperion/bin/hyperiond.sh /storage/.config/hyperion.config.json` I got a totaly different issue :see_no_evil: :hear_no_evil: :speak_no_evil: 

```
Hyperion Ambilight Deamon
        Version   : V1.01.1 (brindosch-d4ad877/fc7bc3c-1458755689  
        Build Time: Mar 23 2016 14:20:16  
INFO: Selected configuration file: /storage/.config/hyperion.config.json  
HYPERION INFO: ColorTransform 'default' => [0; 95]  
HYPERION INFO: ColorCorrection 'default' => [0; 95]
HYPERION INFO: ColorCorrection 'default' => [0; 95]
LEDDEVICE INFO: configuration:
{
        "colorOrder" : "rbg",
        "name" : "MyHyperionConfig",
        "output" : "/dev/spidev0.0",
        "rate" : 1000000,
        "type" : "ws2801"
}

INFO: Creating linear smoothing
HYPERION (CS) INFO: Created linear-smoothing(interval_ms=40;settlingTime_ms=200;updateDelay=0
EFFECTENGINE INFO: Initializing Python interpreter
INFO: Hyperion started and initialised
INFO: Boot sequence 'Rainbow swirl fast' EFFECTENGINE INFO: run effect Rainbow swirl fast on channel 0
BLACKBORDER INFO: threshold set to 0 (0)
BLACKBORDER INFO: mode:default
started
INFO: Kodi checker created and started
terminate called after throwing an instance of 'std::runtime_error'
  what():  JSONSERVER ERROR: could not bind to port
Aborted
```
I guess an conflict with the [Hyperion Addon](https://github.com/b2un0/kodi-script-hyperion) and the issue https://github.com/hyperion-project/hyperion/issues/37

**Comment by penfold42** [comment]
My guess is another hyperion is already running

**Comment by TylonHH** [comment]
Yeah I guess too, but how to figure out / avoid?

**Comment by penfold42** [comment]
For now just "killall hyperiond" then try starting t again

**Comment by TylonHH** [comment]
It was HyperCon?!?!
I connected to via HyperCon over SSH and stopped the host. 
`INFO: Frame grabber created and started
KODICHECK INFO: Kodi Connected
KODICHECK INFO: Kodi Message: {"id":666,"jsonrpc":"2.0","result":[]}
KODICHECK INFO: switching to MENU mode
KODICHECK INFO: Kodi Message: {"id":668,"jsonrpc":"2.0","result":{"System.ScreenSaverActive":true}}
KODICHECK INFO: Kodi Message: {"id":670,"jsonrpc":"2.0","result":{"version":{"major":15,"minor":2,"revision":"02e7013","tag":"stable"}}}
EFFECTENGINE INFO: effect finished
BORDER SWITCH REQUIRED!!
CURRENT BORDER TYPE: unknown=0 hor.size=0 vert.size=0`

**Comment by brindosch** [comment]
hypercon does still the same as you or openelec. If you push the start button more than once, or push it without push on stop before, you may able to start hyperion as often you like. This is not really a hypercon issue, more a bad design of openelec.

It is not possible to do this on any init.d/systemd system.

**Comment by TylonHH** [comment]
just for understanding.
when I use `clearall` do I *restart* the LEDs with an color(effect)/input?

**Comment by brindosch** [comment]
fyi: The next hypercon release will introduce a hyperion.log for all new and old installs (of course you need to run the install script once). Also to show it with hypercon (log button).

clearall reset every active effect/color you set. So it will be black or use the grabbed pictures again for processing

**Comment by TylonHH** [comment]
Thank you for detailed and patient explanation . Issue can be closed.
