### ISSUE TITLE
2 Bugs HyperCon

### ISSUE THREAD

**Issue by KrX3D** [hyperion-project/hyperion#607]
Hello,

i tried out HyperCon version 1.01.2 and when i i.e. change the baudrate to 250000 this setting is not saved after closing and starting HyperCon again (default 1.000.000 is always shown and saved)

there is also an bug at the internal grabber setting for intervall, it saves the value (i.e. 40) at HyperCon  but when ceating an json file this value isnt saved. Its always:

		"frequency_Hz" : 25.0,

**Comment by brindosch** [comment]
> this setting is not saved after closing and starting HyperCon again

Yes, known problem

>"frequency_Hz" : 25.0,

the funny thing is, this just with 40, not with 41 or 39. Need to check which math is done there and what hyperion wants

thank you for your report

**Comment by El-Mare** [comment]
25 Hz means every 40 ms, maybe it comes from there?!

**Comment by brindosch** [comment]
Yes, you are so right *head*desk*, Due to the convert from [ms] to [HZ]
which means: 25Hz means 25 pictures in 1 second. (1/Hz)
And 40ms x 25 = 1000ms -> 1 second
It is working the right way.

**Comment by KrX3D** [comment]
ah ok so it means i dont need to change the 25 Hz in the json to 40 right?

but the baudrate isnt loaded correctly from the .dat file
`DeviceConfig.mDeviceProperties={output\=/dev/spidev0.0, rate\=250000}`
it loads everytime 1million (1000000)

**Comment by brindosch** [comment]
yes, currently not implemented and on the wishlist
/Closed
