### ISSUE TITLE
Unable to load existing Config file

### ISSUE THREAD

**Issue by jpohlman89** [hyperion-project/hyperion#609]
Has anyone Successfully loaded an existing Config file? I have set up a file using lightberry's openelec plugin and would like to edit it in the hyperion configuration tool. But every time I "load" the file, i get a successfully loaded notification, but none of the parameters update to my existing config.

**Comment by penfold42** [comment]
Nope.- it won't read an existing Hyperio.confg file

**Comment by jpohlman89** [comment]
if you can't load an existing config file, what is the load button doing at the bottom next to save?

**Comment by brindosch** [comment]
If you hover the buttons with your mouse, you get this message - "Load your saved HyperCon settings"
No Hyperion config file.
If you click save. it will create a .dat and no .json
If you click load. you will see a "HyperCon_settings.dat" pre-filled in. also you can´t see .json in that filechooser.
Why you thought that you can load a .json?

**Comment by brindosch** [comment]
Should be done
