### ISSUE TITLE
Color calibration doesn't exist in hyperion.config.jason

### ISSUE THREAD

**Issue by rv112** [hyperion-project/hyperion#610]
Hi!

I just downloaded hyperion for my OpenELEC 6 system. But I can't find the  "channelAdjustment" sectio nin the config. I also tested the HyperCon, this also doesn't give me the opportunity to adjuist my colors.
Copy & paste this section to my config doesn't work.

What am I doing wrong?

Thanks!

**Comment by apurbas** [comment]
To the best of my knowledge that's still in beta.

**Comment by brindosch** [comment]
yes, we will release the new version this week.

**Comment by brindosch** [comment]
@rv112 
Hyperion have a new home!
Please read the announcement post and the changelog for V1.02.0
www.hyperion-project.org

Please have a look at our new wiki! (EN/DE)
wiki.hyperion-project.org

All discussions/questions should be moved to the new forum!

**Comment by rv112** [comment]
Thank you and good work!
