### ISSUE TITLE
Information on how Hyperion works

### ISSUE THREAD

**Issue by JuJup** [hyperion-project/hyperion#611]
Hello,

I know this is not a real issue, but id did not see any other way to connect the developers.
For a university project where I'd like to present the technology background of Ambilight, I need information on how Ambilight really works. So how does it determine the correct colors for the LEDs, how does it deal with time delays, different video codecs etc.

Therefore I started to analyse the Hyperion code (cause I use Hyperion - it works perfectly on my Pi). I realized that the FrameGrabber makes a screenshot in a downscaled resolution which is then used by the ImageProcessor. But there are still many questions for me..
So are there any further information about the technology/algorithms behind it or is there anybody willing to help me?

Thanks so much in advance
Jujup

**Comment by tpmodding** [comment]
1. http://www.tweaking4all.com/wp-content/uploads/2014/03/boblight_xbmc_process.jpg
2. http://hacks.esar.org.uk/hdmi-light/
3.http://www.keiang.de/Content-pid-51.html

i had a website (video?!) where is shown how its work, but cant find it sorry

**Comment by brindosch** [comment]
@JuJup 
I also can´t tell you in detail what happend, but @tvdzwan could. He is very very limited in time.

**Comment by brindosch** [comment]
Hyperion have a new home!
Please read the announcement post and the changelog for V1.02.0
www.hyperion-project.org

Please have a look at our new wiki! (EN/DE)
wiki.hyperion-project.org

All discussions/questions/development threads should be moved to the new forum!
We will close this issue now
