### ISSUE TITLE
Unused LEDs on 

### ISSUE THREAD

**Issue by apurbas** [hyperion-project/hyperion#612]
It may sound primitive.
I have just started testing a new APA strip (150+ LED) with 88 LEDs in use. I'm bit surprised to find that 89th & 90th LEDs remains on & emits blue/white light even when hyperion is not receiving signal. Killing Hyperion switches them off.

So I gave some garbage Hscan/vscan value for 89th /90th LEDs. Like a maze now 91 & 92nd LEDs are on. 
What could be the reason? Anyone else faced the same?

**Comment by brindosch** [comment]
I have to admit, i never got the idea to use a strip without using the whole one.
Sounds like a bug.

**Comment by penfold42** [comment]
The end frame in the apa protocol is sized based on the number of LEDs you have defined in the config file.

Can you define all of your physical LEDs in the config with nonsensical hscan values ?

We could alter the code to have a defines number of physical LEDs, but it's obviously simpler to just define all the LEDs.

**Comment by penfold42** [comment]
On second thoughts, maybe we should add the config option. Some effects that index LEDs by number will misbehave with the above setup

**Comment by penfold42** [comment]
I will try to do a proper fix - i know exactly what to do.

**Comment by brindosch** [comment]
As long we can´t save hypercon device settings it is very frustrating :)

**Comment by penfold42** [comment]
Huh ?

**Comment by apurbas** [comment]
Its lovely actually to have little backlit when your TV/ hyperion is not in use.
But as we are purist, so others facing similar issue - define all the LEDs ( used + unused) in your hyperion config.
Give hscan/vscan 0 for unused LEDs - till its fixed.
`		{
			"index" : The index of the led,
		"hscan" : { "minimum" : 0.0000, "maximum" : 0.0000 },
			"vscan" : { "minimum" : 0.0000, "maximum" : 0.0000 }
		}`

**Comment by brindosch** [comment]
as long :)

Hyperion have a new home!
Please read the announcement post and the changelog for V1.02.0
www.hyperion-project.org

Please have a look at our new wiki! (EN/DE)
wiki.hyperion-project.org

All discussions/questions/development threads should be moved to the new forum!
We will close this issue now

**Comment by penfold42** [comment]
yes, yes, I know i should be using the forum....

@apurbas Can you test my fixes? I have no real hardware so have to use debug printf to see if it works.
If you can build from source:
https://github.com/penfold42/hyperion/tree/apa-fix
If you want to cheat https://github.com/penfold42/hyperion/blob/apa-fix/hyperiond.test-binary

**Comment by brindosch** [comment]
Hehe, no problem to use this tracker for code related things too. We just want to move the discussion stuff to the forum. So i closed a little here and there with this notice :)
Thank you for the created thread!

**Comment by brindosch** [comment]
apurbas is already registered at the forum :)

**Comment by penfold42** [comment]
I think once a clear defect is identified we should definitely use this so we have clear traceability.

Is there a cool way to cross reference between the  forums and GitHub ?

**Comment by penfold42** [comment]
@apurbas any news ?

@brindosch you want a pull request ?

**Comment by brindosch** [comment]
as reported at the forum it seams not to work :)

**Comment by penfold42** [comment]
Nothing for days and then I look away for a few hours !

**Comment by brindosch** [comment]
Sorry, as you see i work through the list slowly :)
