### ISSUE TITLE
Pi3+Raspbian+WS2812b - LEDs dont or react extremly delayed?

### ISSUE THREAD

**Issue by bigdx** [hyperion-project/hyperion#613]
Hi,

im completly new to Raspberry and Hyperion, so I hope for "stupied" and easy to solve issue a made ...

I have a RaspPi3 with the newest Raspbian running and connected a 3 LED (for testing) long WS2812b strip to it (directly, via GPIO 18). I followed the instructions in the wiki for WS281X. The LED  light up, but not as i would expect. Sometimes only 1 or 2 of 3 reacts, sometime none, sometimes all reacts, but the strangest thing is, its mostly extremely delayed/slow. Only a few times changes a visible immidiatly.
Currently i ran $ hyperion-remote -e "Rainbow swirl fast" and only the first LED is on. Over the last few minutes it changed slowly from red to green/yellow, like in slow motion. Sending $ hyperion-remote -c red has no effect. Even $ hyperion-remote -x is ignored. The JSON-Server is running and according log receiving everything ...

> $ hyperion-remote -x
> hyperion-remote:
>         version   : V1.01.1 (brindosch-d4ad877/fc7bc3c-1458755689
>         build time: Mar 23 2016 14:19:58
> Connected to localhost:19444
> Clear priority channel 100

Corresponding Log:
> Mar 18 10:08:25 raspberrypi hyperiond[409]: JSONSERVER INFO: New connection
> Mar 18 10:08:25 raspberrypi hyperiond[409]: BLACKBORDER INFO: threshold set to 0 (0)
> Mar 18 10:08:25 raspberrypi hyperiond[409]: BLACKBORDER INFO: mode:default
> Mar 18 10:08:25 raspberrypi hyperiond[409]: JSONSERVER INFO: Connection closed

See also ...
hyperion log: http://pastebin.com/jfedts5a
hyperion config: http://pastebin.com/a0XmGJA9

I hope someonw can help me with that ...
Kind Regards,
BigD

**Comment by bigdx** [comment]
Aaaaahm ... never mind ... got it ... SOMEBODY (that is going to get beaten when back in office) has mixed up the sorted Resistor-Boxes and i didnt realise having taken a 330 Ohm Resistor out of the 100 Ohm Resistor box -_- 

If someone encounters such strange behavier: 
330 Ohm is already to much. Looks like parts of the DATA signal still pass, but only randomly ... 

With the original 100 Ohm everything works just fine (as far as i have tested yet).

Maybe a corresponding comment in the wiki could be helpful to someone?

**Comment by apurbas** [comment]
"colorOrder" : "grb"..Do the colors look ok to you? 
You may infact download the images only from here [https://github.com/hyperion-project/hyperion/wiki/Color-Calibration](url) & test the colors.

**Comment by bigdx** [comment]
colors look fine as "red" is red, "blue" is blue and "green" is green. If you mean more specific regarding color temparture etc. i haven't tested/tried yet.

**Comment by apurbas** [comment]
Great ! keep tweaking till you are happy :-)

**Comment by brindosch** [comment]
A dump question from me now. Why do you use a resistor?

**Comment by brindosch** [comment]
Closed

**Comment by bigdx** [comment]
I read that the DATA Port is easiely damaged and it is recommended to protect it with a resistor ... the hyperion wiki says that too

**Comment by brindosch** [comment]
yes, i noticed. sorry for the dump question :)
I never used the pwm leds

**Comment by bigdx** [comment]
No Problem ;-)
