### ISSUE TITLE
Sample xonfigs directory ?

### ISSUE THREAD

**Issue by penfold42** [hyperion-project/hyperion#615]
I think we need a folder with sample working xonfigs.

Discuss !

**Comment by brindosch** [comment]
My thoughts
1. No, my target is to remove any not relevant "code" from the repo, like the datasheets.
2. No, we could store sample configs at the wiki in code tags or maybe better as file download (as file download we could keep track how often people downloaded, to get a idea how often this was used.

**Comment by RickDB** [comment]
New wiki would be better home as we can link several configs with additional info on how to setup the hardware, right now we have documentation for Hue and Orb for instance where we can inline include configs either in code tags or as attachements.

**Comment by penfold42** [comment]
They look good - we should use this format for many other non obvious device types.

We could have an overall master page that walks through the possible config sections with links

**Comment by brindosch** [comment]
@penfold42 
Hyperion have a new home!
Please read the announcement post and the changelog for V1.02.0
www.hyperion-project.org

Please have a look at our new wiki! (EN/DE)
wiki.hyperion-project.org

All discussions/questions should be moved to the new forum!
We will close this issue now
