### ISSUE TITLE
Huge imbalance between colors

### ISSUE THREAD

**Issue by andrewmunro** [hyperion-project/hyperion#617]
I have just set up hyperion with my Rpi3 and a new set of WS2801 LED's I got from eBay. I was amazed at how easy it was to plug them in and get them working with OSMC straight away.

I have one major problem though, the intensity of the red light is about 10-20% the intensity of the blue and green which are both extremely bright. This means that the colours when mixing with red are completely off, and to compensate for this, I have to tone the other two colours down by changing their white light to 0.2. This means that my lights are omitting at 20% of the original brightness and the effect is very disappointing.

I understand that this is probably a hardware problem, but thought it would be best to post here to see if anyone has some advice for troubleshooting them. (On a side note, I had to set the config to 'RBG' instead of 'RGB', is this standard for WS2801's?). Unfortunately I have already cut up the strips and soldered them together on my TV so returning them is not an option.

**Comment by penfold42** [comment]
I suspect they were assembled wrong.

Mismatched resistors for the different colours

**Comment by brindosch** [comment]
Yes, there should be no huge difference. Maybe a bad batch

**Comment by penfold42** [comment]
Have you tried asking them for a refund or return anyway ?

Your modification could not have caused this defect and they shouldn't be reselling a know faulty item anyway

**Comment by andrewmunro** [comment]
I'll send them an email when I get home. Also now that you mention resistors, I did accidentally get a piece of solder on top of the resistor. I didn't notice til it short-circuited and the Rpi wouldn't switch on. After removing the solder it started up fine, but maybe that resistor was damaged in the process. If that's the case I can try cutting out that LED and testing...

**Comment by brindosch** [comment]
this may be possible!

Hyperion have a new home!
Please read the announcement post and the changelog for V1.02.0
www.hyperion-project.org

Please have a look at our new wiki! (EN/DE)
wiki.hyperion-project.org

All discussions/questions/development threads should be moved to the new forum!
We will close this issue now
