### ISSUE TITLE
Violet light while border is black

### ISSUE THREAD

**Issue by rhoman** [hyperion-project/hyperion#619]
Hello,

I've just added ambilight to my Kodi (Open Elec, Raspberry 2). It works great, except that i have violet light while border is black.
How can i change this?

Bets,
Martin

**Comment by ntim** [comment]
Also experience this from time to time. My feeling is that it occurs when the quality of the video is not very high.

**Comment by brindosch** [comment]
Hello rhoman,
Please refer to our support forum for further questions.
We will no longer provide support on github.
www.hyprion-project.org

Thank you
