### ISSUE TITLE
rpi2 wont talk to arduino

### ISSUE THREAD

**Issue by lidorsho** [hyperion-project/hyperion#620]
hi.
first of all,amazing work on the hyperion,it looks great!
im trying to get my setup working,i have rpi2 with openelec,WS2812B LED strip,and arduino(nano uno and more)
the problam is that the rpi wont talk to the arduino!
the RX led is off
![untitled](https://cloud.githubusercontent.com/assets/19189817/15017592/d151a678-121e-11e6-895b-cdd055da071c.jpg)
what do i miss here?

**Comment by brindosch** [comment]
Hello lidorsho,
Please refer to our support forum for further questions.
We will no longer provide support on github.
www.hyprion-project.org

Thank you
