### ISSUE TITLE
hyperiond segfaults with invalid/unknown/missing led device type

### ISSUE THREAD

**Issue by penfold42** [hyperion-project/hyperion#624]
hyperiond segfaults if you configure:
- an unknown led device type
- a missing led device type
- no led device config section

Should we just abort cleanly if the device type is unknown?
Will anyone want to use hyperiond with no attached led devices?

INFO: Selected configuration file: /etc/hyperion.config.json.pwm60
HYPERION INFO: ColorTransform 'default' => [0; 59]
LEDDEVICE INFO: configuration:
{
        "NOtype" : "ws281x",
        "blah" : 0,
        "colorOrder" : "grb",
        "dmanum" : 5,
        "invert" : 0,
        "leds" : 60,
        "name" : "MyPi",
        "rgbw" : 0
}

LEDDEVICE ERROR: Unknown/Unimplemented device unspecified
HYPERION INFO: Not creating any smoothing
EFFECTENGINE INFO: Initializing Python interpreter
Segmentation fault

**Comment by brindosch** [comment]
1. hm yeah a clean abort might be better. (from code view). From user view it does not matter, cause you "see" it at the log already.
2. A circumstance where this is used? Hm

**Comment by penfold42** [comment]
Grabber on a device with no local LEDs forwarding to another device?

Corner case - I'll ignore it for now and create a pull request.

You want a separate one or can I include it with the apa fix ?

**Comment by brindosch** [comment]
You could include it at the apa fix. In hope it don´t brake something :)
