### ISSUE TITLE
Wrong version installed?

### ISSUE THREAD

**Issue by bouwew** [hyperion-project/hyperion#628]
I just tried to perform an upgrade as described in the Wiki.

Result is: Version   : V1.02.0 (brindosch-f4162eb/2d45d51-1462453507

I was expecting V1.02.3? Something wrong?

**Comment by brindosch** [comment]
Everything okay, we just raise the last number in case of a bugfix, as written at the announcement section it was always a update for HyperCon.
https://hyperion-project.org/forums/official-announcements.2/

Thank you

**Comment by bouwew** [comment]
Hi brindosch,

Ok, good to read that the correct version has been installed.
However, I don't understand why you (and maybe others) would choose to have the 1.02.3-version report itself as V1.02.0. Then have it report itself as V1.02.
I had installed V1.02.1. Can you understand my confusion when I see the update is V1.02.0, while I expect to see V1.02.3?

**Comment by brindosch** [comment]
Hyperion is still version V1.02.0. So it reports V1.02.0
Not sure why you expect version V1.02.3 for Hyperion?

**Comment by bouwew** [comment]
Never mind :)
I need to look better, I'm seeing Hyperion where it reads HyperCon.
Sorry about that!
