### ISSUE TITLE
ws2801+pi3 leds are not changing color

### ISSUE THREAD

**Issue by 2dela** [hyperion-project/hyperion#629]
hi,

i just installed raspbian and openelec both with same result. 
the hyperion service is running in both cases but the led are not lighting as they should be, just some of them are lighting in withe, those led are lighting with the pi with or whiout power, its like the gpio ports 19 and 23 are not seding the right signals.

the thing is how can i check that those ports are seding what they should send and/or my led are fine hehe

also i am not able to put the led on with HyperCon

any help or any advise will be really apreciated

btw output of my hyperion daemon:
root@Urd:/etc/ssh# /usr/bin/hyperiond /opt/hyperion/config/hyperion.config.json
Hyperion Ambilight Deamon
        Version   : V1.02.0 (brindosch-f4162eb/2d45d51-1462453507
        Build Time: May  5 2016 06:07:47
INFO: Selected configuration file: /opt/hyperion/config/hyperion.config.json
HYPERION INFO: ColorTransform 'default' => [0; 84]
HYPERION INFO: ColorCorrection 'default' => [0; 84]
HYPERION INFO: ColorAdjustment 'default' => [0; 84]
LEDDEVICE INFO: configuration:
{
        "colorOrder" : "rgb",
        "name" : "MyHyperionConfig",
        "output" : "/dev/spidev0.0",
        "rate" : 250000,
        "type" : "ws2801"
}

HYPERION INFO: Not creating any smoothing
EFFECTENGINE ERROR: Effect directory can not be loaded: /storage/hyperion/effects
EFFECTENGINE INFO: Initializing Python interpreter
INFO: Hyperion started and initialised
INFO: Boot sequence 'X-Mas' EFFECTENGINE INFO: run effect X-Mas on channel 0
EFFECTENGINE ERROR: effect X-Mas not found
failed
INFO: Kodi checker created and started
INFO: Json server created and started on port 19444
INFO: Proto server created and started on port 19445
INFO: Boblight server created and started on port 19333
DISPMANXGRABBER INFO: Display opened with resolution: 1920x1080
BLACKBORDER INFO: threshold set to 0 (0)
BLACKBORDER INFO: mode:default
INFO: Frame grabber created and started
KODICHECK INFO: Kodi Connected

**Comment by brindosch** [comment]
Greetings 2dela,
we provide no support on Github, please refer to our support forum.
www.hyperion-project.org

Thank you
