### ISSUE TITLE
Flickering on imx6 with more than 20 leds

### ISSUE THREAD

**Issue by JonathanRuizPaez** [hyperion-project/hyperion#630]
Hello,

We have 2 humming-boards and in one of them we compiled Openlec enabling the SPI from user space.

After fixing some issues (Libraries), we can run Hyperion with up to 20 leds configured. If we configure more it start to flicker. We connected the oscilloscope and it looks like an overflow in the SPI buffers / DMA or whatever Hyperion use to communicate through SPI. 

Do you know what can be the problem?

Regards,
Jonathan.

**Comment by penfold42** [comment]
You might have more luck posting to the forum:
https://hyperion-project.org/

We don't do any dodgy low level access when using SPI - we just use the kernel drivers and we don't manage our own fifo

**Comment by JonathanRuizPaez** [comment]
I replaced the "writeBytes" method inside the file "LedSpiDevice.cpp" with the next one:

`
int LedSpiDevice::writeBytes(const unsigned size, const uint8_t * data)
{
        if (mFid < 0)
        {
                return -1;
        }
        spi.tx_buf = __u64(data);
        spi.len    = __u32(size);

        unsigned int currentPosition = 0;
        int retVal = 0;
        while(currentPosition < size)
        {
            spi.tx_buf = __u64(data+currentPosition);
            spi.len = 30;
            if(spi.len > (size - currentPosition))
                spi.len = size - currentPosition;
            retVal = ioctl(mFid, SPI_IOC_MESSAGE(1), &spi);
            currentPosition += spi.len;
        }
        if (retVal == 0 && mLatchTime_ns > 0)
        {
                // The 'latch' time for latching the shifted-value into the leds
                timespec latchTime;
                latchTime.tv_sec  = 0;
                latchTime.tv_nsec = mLatchTime_ns;

                // Sleep to latch the leds (only if write succesfull)
                nanosleep(&latchTime, NULL);
        }

        return retVal;
}
`


It solve the flickering in my leds string (72 Leds). I did not have this problem with the raspberry, I am sure that it is something related to an overflow in the FIFO of the SPI device.

To fix the issue in right way I need to know which module of software should be the responsible to split the message. I think it should be the user space driver in the Linux kernel, but if there is a way to ask the driver about the maximum length of the SPI message then the responsible should be Hyperion.

Do you know if the SPI driver has a way to ask about the maximum message length?

**Comment by penfold42** [comment]
Yuk

I tend to agree that the kernal should do the right thing.
Maybe it's buggy ?

I can't imagine an iMX6 board and working kernel struggling with 60 byte at a time.

It really needs to be in the kernel - if you have to split the writes from user space your could get rescheduled between fragments which in extreme cases will
Cause flicker you can't fix

**Comment by JonathanRuizPaez** [comment]
It is true, the delay between every write is variable because of the OS, but at least it seems to work good. I will try to fix the problem in the Linux driver and publish it to Openelec, but meanwhile if someone else has the same problem at least they can try this workaround.
Thanks!!

**Comment by penfold42** [comment]
# cat /sys/module/spidev/parameters/bufsiz
 
What do you get ?

**Comment by JonathanRuizPaez** [comment]
I get 4096.

I didn't take a look yet, but the communication should be something like:

hyperiond <-> SPIDev <-> SPI.

I think this buffer is the buffer between hyperiond and SPIDev, and the problem should be in the other communication because of the hardware FIFO.

Thanks you very much for your time.

**Comment by JonathanRuizPaez** [comment]
Hello,

I solve the problem with the driver, using the latest one available in the official Linux repository. I have created a patch and I will try to introduce it in openelec. The issue is: [Issue in OpenELEC](https://github.com/OpenELEC/OpenELEC.tv/issues/4950).

Cheers.
