### ISSUE TITLE
Clean git history

### ISSUE THREAD

**Issue by NicoHood** [hyperion-project/hyperion#639]
Cloning the git history takes forever (even with a 50k connection). This is due to a lot of binaries inside the history. I highly suggest to remove them, as most of them are outdated anyways. You can publish those as release if you wish, but I think it is not really required.

The best way would be to create a 2nd branch where you test all the deletions and then finally apply the change with a force push after some time.

**Comment by penfold42** [comment]
Agree

**Comment by penfold42** [comment]
In the meantime --depth is your friend

**Comment by redPanther** [comment]
@nicohood can you give me an example of how to delete the binaries from history?

**Comment by brindosch** [comment]
of course yes, no idea how to perform this step

**Comment by penfold42** [comment]
https://help.github.com/articles/remove-sensitive-data/

**Comment by NicoHood** [comment]
That is a pretty good link. I think this will do it (I tested it, however this needs to be done on all branches it seems).
```
git filter-branch --force --index-filter \
'git rm --cached --ignore-unmatch deploy/hyperion*.tar.gz' \
--prune-empty --tag-name-filter cat -- --all
```

And as stated in [this tutorial](http://naleid.com/blog/2012/01/17/finding-and-purging-big-files-from-git-history) I then used the clone command to copy the repository to a new location:
```
git clone --no-hardlinks . new-repo-clone-name
```

The new output does not show any hyperion*.tar.gz release anymore. There are some hypercon files still available which we might just want to keep.

**Comment by brindosch** [comment]
I tried it with bfg. 2mb as filesize

output looks good
```
Deleted files
-------------

	Filename                               Git id                                                 
	----------------------------------------------------------------------------------------------
	HyperCon.jar                         | 4451ebfa (7,7 MB), fb506ad2 (7,7 MB), ...              
	TestImageBBB_02.png                  | 048b062d (3,1 MB)                                      
	TestImage_01.png                     | 427d6ffe (7,4 MB)                                      
	hyperion.deps.openelec-imx6.tar.gz   | 198ac3d4 (6,6 MB)                                      
	hyperion.deps.openelec-rpi.tar.gz    | a628a0f8 (6,7 MB), 5e8ca7ba (6,7 MB), 4d50c38a (6,7 MB)
	hyperion.deps.openelec-x32x64.tar.gz | e55dbd64 (7,6 MB), dcef2212 (7,6 MB)                   
	hyperion.tar.gz                      | 05b947e9 (7,3 MB), bf3e36a0 (7,3 MB), ...              
	hyperion_imx6.tar.gz                 | 3785db40 (7,1 MB), 53710fe4 (7,5 MB), ...              
	hyperion_rpi.tar.gz                  | 5b0f057a (7,7 MB), 5c164e4f (7,6 MB), ...              
	hyperion_wetek.tar.gz                | 752ebb4f (7,6 MB), 05227980 (7,2 MB), ...              
	hyperion_x32.tar.gz                  | f3e3f4a3 (7,3 MB), 511ab205 (7,7 MB), ...              
	hyperion_x64.tar.gz                  | 6f86ceeb (7,4 MB), e26ac1a0 (7,7 MB), ...              
	hyperiond                            | 391a5783 (2,1 MB), 5031f4b1 (2,1 MB), ...              
	hyperiond.test-binary                | e15fd82e (2,3 MB)                                      


In total, 2376 object ids were changed. Full details are logged here:

	/home/sascha/CLEANING/hyperion.git.bfg-report/2016-05-25/07-31-55

BFG run is complete! When ready, run: git reflog expire --expire=now --all && git gc --prune=now --aggressive
```
After git reflog expire
i proceed with git push

but i get
```
To https://github.com/hyperion-project/hyperion.git
 ! [rejected]        Beta -> Beta (fetch first)
 ! [rejected]        V1.01.1 -> V1.01.1 (fetch first)
 ! [rejected]        V1.02.0 -> V1.02.0 (fetch first)
 ! [rejected]        master -> master (fetch first)

```
Error: commits at the repos

I am not really familiar with git on command line, help is appreciated :)
But i am really near! :)

**Comment by NicoHood** [comment]
Ohoh. Please be really careful. I hope you were pushing to a fork of hyperion and not the main project. So please test it on another branch first.

Could you tell me the push command you used? I think you forgot tot use `--force`. However I think it is not a good idea to remove the test pictures, only the old binaries of hyperion itself and possibly hypercon.

**Comment by brindosch** [comment]
The current test pictures are not that big. These are older ones (i had a look)
I have a backup of that git? So i may able to revert this?

**Comment by NicoHood** [comment]
I would not push it to the master. Not even with a backup. Its not the first git I messed up. Please use a fork first and verify it there. It should not hurt. Then you also need to check how forks of your fork behave. If you have pending PRs you need the users to tell to rebase their git. Its not that simple, you can easily break a lot of work (from others as well) very fast.

**Comment by brindosch** [comment]
i do a test with a fork :)

**Comment by brindosch** [comment]
Hm,
git push --force 
did the trick,
now i have a branch with 950 more commits and i still clone
100% (10099/10099), 379.54 MiB | 12.37 MiB/s, done.

which should not be the case? Maybe cause i used --recursive to clone?
Could you verify this?
https://github.com/brindosch/hyperion

**Comment by NicoHood** [comment]
I think the problem is that the "non master" branches still have those commits.
I suggest to first tag them correctly (via release, or just via tags) and the remove the branch completely. I suggested that somewhere else already. Versions should be tagged and not "branched".

Then you can try to tune the master branch.
`git branch --all` lists all branches. You might want to try to clone ONLY the master branch. and delete all other, if they still exists.

```
$ git clone -b master --single-branch https://github.com/brindosch/hyperion.git hyperion_test
Cloning into 'hyperion_test'...
remote: Counting objects: 7797, done.
remote: Compressing objects: 100% (34/34), done.
remote: Total 7797 (delta 265), reused 254 (delta 254), pack-reused 7509
Receiving objects: 100% (7797/7797), 93.29 MiB | 3.74 MiB/s, done.
Resolving deltas: 100% (4917/4917), done.
Checking connectivity... done
```

As you can see it works. The other branches just have those "bad commits" left. You need to rebase them to the master (or remove).

I am just wondering if the left 100mb are still big or if we can shrink this even further.

**Comment by unorthodox-engineers** [comment]
Yeah, someone needs to fix this. It takes 400Mb to download the repo to a Raspberry PI, which can be almost 10% of available disk space. That's too much to blink a couple of LEDs. I'm giving up on trying to get Hyperion installed for this reason alone - I'm not going to inflict this as a dependency on my users. Not even at 100Mb.

At the very least, put the clone --depth instructions in the README at the top in the meantime.

**Comment by penfold42** [comment]
Your users are building from source ?

**Comment by brindosch** [comment]
/done
new filesize
```
git clone --recursive -b master https://github.com/hyperion-project/hyperion.git
Nach »hyperion« wird geklont
remote: Counting objects: 8448, done.
remote: Compressing objects: 100% (2338/2338), done.
remote: Total 8448 (delta 1311), reused 82 (delta 82), pack-reused 5754
Objekte werden empfangen: 100% (8448/8448), 6.39 MiB | 3.81 MiB/s, done.
```
I keep the beta branch for now until the beta building is running automatically based on a nightly build
master -> stable
Beta -> unstable

We could change this later, The biggest problem is eliminated
@unorthodox-engineers 
user should use the installation, there is no reason to compile yourself.
If there is issues with something create a PR with a fix or ask for a solution :)
