### ISSUE TITLE
Submodule discussion 

### ISSUE THREAD

**Issue by penfold42** [hyperion-project/hyperion#645]
In particular rpi_281x and rgbw support.

From memory we are now tracking the latest commit at jgarff.

Should we keep doing this ?
Should we peg it to the current commit ?

Do we reference my fork until my rgbw support gets merged ?

I think I'm ready to submit a PR to jgarff to get this done

**Comment by brindosch** [comment]
Not sure how many plans you have to extend these dependencies
If jgarff is not fast enough in merging it may be good to fork it?

**Comment by penfold42** [comment]
I don't want to maintain my own fork unless we have no choice

**Comment by brindosch** [comment]
then we leave it as is. :)

**Comment by penfold42** [comment]
Maybe I should make a tag on the branch of my fork and track it for now.
I actually have some sk6812rgbw and would like it integrates properly

**Comment by brindosch** [comment]
We will see which source we (you) need in future. Depending on this we could switch.

**Comment by penfold42** [comment]
It looks like it will be merged into the main code base in the medium term

**Comment by penfold42** [comment]
https://github.com/jgarff/rpi_ws281x/issues/89
