### ISSUE TITLE
discuss internal colour model

### ISSUE THREAD

**Issue by penfold42** [hyperion-project/hyperion#648]
So.... since inception, the simple RGB colour space has been fine.

Now we have RGBW led devices - which im providing support for at the led device layer by mapping RGB to RGBW.

This is ok, but I cant directly access R,G,B and W from effects or the json interface.
We could also need transforms and adjustments to be applied too - think of supporting different colour temperature variants of the white component.

should we consider changing our internal representation to RGBW ?

**Comment by AEtHeLsYn** [comment]
IMO, working with RGB is fine, as RGBW is not a "real" color space. To maintain backwards compatibility with all the LED strips, the RBG to RGBW conversion should be done only when sending color info to LED strips, there is no need to change all the color code.

**Comment by redPanther** [comment]
I agree no need for big changes, but we should add methods to deal with rgbw (e.g. conversion from rgb to rgbw, a type for colorRgbw ... )

**Comment by penfold42** [comment]
I've done the rgbw type and started on conversion algorithms in my sk6812rgbw branch

**Comment by brindosch** [comment]
Done? :)
I think so. It will be not that easy to port the whole processing to RGBW just because of one or two chips? (and due to the point there is no real rgbw space)

**Comment by penfold42** [comment]
Agreed - we'll revisit if someone does a RYGCBW led !
