### ISSUE TITLE
make potobuffer mandatory

### ISSUE THREAD

**Issue by redPanther** [hyperion-project/hyperion#658]
currently protobuffer is optional - means can be switched of during compilation. if you do so many features are deactivated. (all standalone grabbers, forwarder)

I think this makes no sense anymore, because proto connection is mandatory and don't harm to have it.
I want to remove the possibility to deactivate protobuffer - what's your opinion? Does anybody use hyperion with not compiled in protobuffer?

Making this mandatory would simplify cmake code and spare some lines of code in various source files

**Comment by brindosch** [comment]
opinion - remove it.

For sure there are guys out there 0,01% that want to disable protobuffer to save some space(processing?). But of course, 99,99% of the people don´t care at all.

did you know that you could disable JSON and PROTO with the config (if you remove the complete section)? Proto throws some erros at the grabbers but it is still working :)

**Comment by redPanther** [comment]
disabling != removing

yes i know we can disable it by removing it from config.
I think this should be enough for the - 0,01% people -

BTW currently I'm cleaning the code. Indentions, windows line-endings and stuff ...

**Comment by brindosch** [comment]
of course yes, this was just a side note :)
code cleanup is boring isn´t it? :)

**Comment by redPanther** [comment]
> code cleanup is boring isn´t it? :)
yes, indeed.

BTW I saw lots of code duplications / pattern duplications. There is some room for refactoring.

Especially the standalone grabbers have mostly the same code, this should be generalized ...

**Comment by brindosch** [comment]
makes sense, sad that i am not able to do it :(

**Comment by penfold42** [comment]
From memory the colour order code is a bit dodgy - parsed and reparsed a couple  of times
