### ISSUE TITLE
rpi 3 works, but rpi A+ not

### ISSUE THREAD

**Issue by pete111** [hyperion-project/hyperion#670]
Hello, I installed hyperion to my RPi 3 (raspbian, v4l2 with stk1160) and it worked ok. I tried to simply eject microSD card and put it into my Rpi A+ but I found out it is not working (initial rainbow is ok, but then colors from played video show just for a while and then disappear. After few seconds colors show again and then dissappear again). I know the power issue of usbm so I connected it via powered usb hub. 

Any idea why it is not working with rpi A+?

**Comment by brindosch** [comment]
Greetings,
we provide no support on github (no longer)
Please have a look at our webpage - sounds like a power issue of your grabber or Pi.
We may need further informations
https://hyperion-project.org/threads/before-you-open-a-new-thread.22/

**Comment by pete111** [comment]
Hi, I tried to post it to forum but I must wait for approval of my account by forum admin.

**Comment by brindosch** [comment]
Hm, there is no pending account.
Are you sure?

**Comment by pete111** [comment]
yes, I created it about 8 hours ago. (name peter)
