### ISSUE TITLE
Build error generated mac el capitan

### ISSUE THREAD

**Issue by zarboz** [hyperion-project/hyperion#693]
`/Users/zarboz/hyperion/libsrc/utils/Logger.cpp:49:25: error: use of undeclared identifier 'program_invocation_short_name'
        _appname = std::string(program_invocation_short_name);
                               ^
/Users/zarboz/hyperion/libsrc/utils/Logger.cpp:61:12: error: use of undeclared identifier 'program_invocation_short_name'
                openlog (program_invocation_short_name, LOG_CONS | LOG_PID | LOG_NDELAY, LOG_LOCAL0);
                         ^
2 errors generated.
`

**Comment by redPanther** [comment]
programm_invocation_shortname is the linux way to get application name. I dont know how its called on osx.
I have no acces to osx so its hard to fix it for me. If you find how this var is called, let me know and I will make a fix.

**Comment by penfold42** [comment]
Tsk tsk...

Conforming to

These variables are GNU extensions, and should not be used in programs intended to be portable.

**Comment by penfold42** [comment]
Looks like an easy fix:
https://lists.freedesktop.org/archives/mesa-dev/2013-June/041123.html

**Comment by zarboz** [comment]
if i reset latest commit i can build

**Comment by penfold42** [comment]
Try replacing program_invocation_short_name

With "blah" in double quotes

**Comment by redPanther** [comment]
This compiles of course, but this isn't the idea. I have the solution for freeBSD. Perhaps this helps the mac.

**Comment by penfold42** [comment]
The link i posted above has 
 +#undef GET_PROGRAM_NAME
>>> +#ifdef __GLIBC__
>>> +#	define GET_PROGRAM_NAME() program_invocation_short_name
>>> +#else /* *BSD and OS X */
>>> +#	include <stdlib.h>
>>> +#	define GET_PROGRAM_NAME() getprogname()
>>> +#endif
>>> +

**Comment by redPanther** [comment]
@work I use getprogname for bsd. Osx manpages knows getprogname too.

My repo is messed up, so my pr with an osx fix have to wait. In the meantime replace program_.... with getprogname()
