### ISSUE TITLE
LEDDEVICE ERROR: Unknown/Unimplemented device ws2801

### ISSUE THREAD

**Issue by NicoHood** [hyperion-project/hyperion#708]
This is my config:

```
        "device" :
        {
                "name"       : "MyHyperionConfig",
                "type"       : "ws2801",
                "output"     : "/dev/spidev0.0",
                "VID"        : "0x2341",
                "PID"        : "0x8036",
                "rate"       : 1000000,
                "colorOrder" : "rgb"
        },
```

I do not know why I get this error. I recompiled the source on arch for arm6 on a pi zero, using the master brach. This also happens with the sample config.

But I also get this error:
```
Unable to load library icui18n "Cannot load library icui18n: (icui18n: cannot open shared object file: No such file or directory)"
```

With installing `icu` This error could be solved, but the main issue still exists.

It seems that `-DENABLE_DISPMANX=ON -DENABLE_DISPMANX=ON` was missing in make. Someone changes the default settings?

I do not know how cmake works, but this causes the error:
https://github.com/hyperion-project/hyperion/blob/master/CMakeLists.txt#L25

I tried to compile with this command as cmake:
```
cmake -DCMAKE_BUILD_TYPE=Release -DENABLE_DISPMANX=ON -DENABLE_SPIDEV=ON -Wno-dev ..
```

However I still get:
`Failed to open device('/dev/spidev0.0') `

I've added dtparam=spi=on to my config.txt though. I had to start hyperion as root. So this is expected I think.

**Comment by penfold42** [comment]
What are you using to attach the LEDs ?
Are they attached to the SPI interface or via some sort of USB device ?

This config has elements of both so I can't tell which you are using.

**Comment by brindosch** [comment]
This message is thrown when you compile without SPI?

My suggestions, please test with raspbian first. If this works, you need to search the errors on your custom build. We will never support these "customized" builds, cause it might be a never ending story for us.

If you compile your own system, deal with it! Might be harsh but what shall we do?

**Comment by NicoHood** [comment]
Yes I am using SPI. And no I do not use a customized build. The only difference is that I am using Arch and that the cmake does not recognize that I am compiling for a raspberry pi, so it leaves out the SPI lines. This should get fixed. However I cannot find the reason why this happens. I provided as much information as I could. Please reopen.

**Comment by redPanther** [comment]
you should compile with:
cmake -DCMAKE_BUILD_TYPE=Release -DPLATFORM="rpi" ..

there is no error. You found the right line in code ...

**Comment by brindosch** [comment]
mh, documentation never updated here.

**Comment by NicoHood** [comment]
Ah, I see. That makes sense. Ive added it here:
https://github.com/hyperion-project/hyperion/pull/706/files#diff-827d5b5e6ae90ff76f6633a1714d7ac1
