### ISSUE TITLE
Release Tags

### ISSUE THREAD

**Issue by NicoHood** [hyperion-project/hyperion#709]
There is no single release tag. I guess they all disappeared when rebasing (clearing the large files).
I do not even know which is the current version at the master. No changelog, nowthing. Could you tag the releases again and add a changelog.txt file somewhere?

**Comment by penfold42** [comment]
We probably need to do a final cleanup on Hyperion.

Master is rally old, but beta is the closest to the final release.

We're r only doing bug fixes here - Hyperion.ng repository is where the current development is happening.

**Comment by NicoHood** [comment]
What is Hyperion.ng?

**Comment by penfold42** [comment]
https://github.com/hyperion-project/hyperion.ng/pulse

We cloned the repo and renamed it so we can make more sweeping changes.

Things like move to qt5, re factor lots of code, and not have to worry much about backward compatibility.

We should update the readme to make this clear for everyone who wants to contribute

**Comment by NicoHood** [comment]
Actually this is a very good idea. Will you keep the name hyperion or will you use Hyperion-NG?  I'd prepare an AUR package for the ng version or update the existing one. The problem is, that currently nothing works. All old versions are gone and you only have the master branch. So when is a first NG release planned?

**Comment by penfold42** [comment]
Personally don't think the name will stay for ever.

My preference is a Hyperion 2.0 with no guarantee on old supported platforms.

Does Hyperion Beta still compile and work ?
We might need to looks at rolling back a few commits and doing a 1.04 for those who need it

Unless you have a clear need, I'd focus any effort to the NG repo

**Comment by redPanther** [comment]
I would suggest when hyperion v2 is ready we rename repo hyperion to hyperion.legacy and hyperion.ng to hyperion. Then continue to develop hyperion there in branches and make nice tags for release versions :-)

**Comment by NicoHood** [comment]
You should at least publish one last legacy release for all those online docs that are currently available.
I will try the NG now. (I also suggest to just give it a version 2.x but still name it just hyperion.)

**Comment by brindosch** [comment]
>  The problem is, that currently nothing works.

you mean the arch thing won't work? 99% of hyperion users don't use arch for sure.
> All old versions are gone and you only have the master branch

yeah?
> or update the existing one

Better update this one first and when v2 is ready - update it. The ng branch is alpha, you should not point with any install package on it.
> So when is a first NG release planned?

Maybe 2016, you could help to work on the issues, enough todo. The more people help the faster we are. Keep in mind this is a non profit open source project - it's done when it's done.

**Comment by redPanther** [comment]
pkgbuild for hyperion.ng should look like that (not finished, but this is the way to go)

```
# Maintainer: redpanther <bla@blub>
pkgname=hyperion-next-git
pkgver=r680.c8a2fe8
pkgrel=1
pkgdesc="An opensource 'AmbiLight' implementation"
arch=('i686' 'x86_64')
url="https://github.com/hyperion-project/hyperion.ng"
license=('MIT')

depends=('protobuf' 'libusb' 'qt5-base' 'qt5-serialport' 'avahi')
optdepends=('xorg-server: X11 grabbing')
makedepends=('git' 'cmake')
provides=("${pkgname%-git}")
conflicts=("${pkgname%-git}")
replaces=()
backup=('etc/hyperion/hyperion.config.json')
options=()
source=("hyperion::git+${url}#branch=master")
sha256sums=('SKIP')

# Please refer to the 'USING VCS SOURCES' section of the PKGBUILD man page for
# a description of each element in the source array.

pkgver() {
        cd "$srcdir/${pkgname%-git}"
        printf "r%s.%s" "$(git rev-list --count HEAD)" "$(git rev-parse --short HEAD)"
}

build() {
        cd "$srcdir/${pkgname%-git}"
        git submodule init 
        git submodule update
        cmake -DCMAKE_INSTALL_PREFIX=$pkgdir -DPLATFORM=x86 -DCMAKE_BUILD_TYPE=Release ..
        make -j$(nproc)
}

package() {
        install -d "$pkgdir"/{usr/bin,etc/hyperion,etc/systemd/system,usr/share/hyperion}
        make install
        install -m 644 "$pkgdir/${pkgname%-git}/usr/share/hyperion/config/hyperion.config.json.default" "$pkgdir/etc/hyperion/hyperion.config.json"
        #install -m 644 "$pkgdir/${pkgname%-git}/usr/share/hyperion/config/hyperion.config.json.default"hyperiond.service "$pkgdir"/etc/systemd/system/
}

```

**Comment by NicoHood** [comment]
I modified the package a bit, but arch complains about the installation directory /bin. How can I specify to use /usr/bin? See this:
https://www.archlinux.org/news/binaries-move-to-usrbin-requiring-update-intervention/

Would it also make more sense to add the install prefix to the cmake or rather pass it in the make install command?

**Comment by redPanther** [comment]
/usr was missing. I updated the script. if cmake/configure is used always set install prefix during cmake/configure phase. 
To make install process not to complicated (-> more complicated -> more bugs) all service files are installed into hyperions share folder (those few bytes more on harddisk won't hurt anybody) - but only systemd service is copied into system and used.

BTW same script should work with hyperion/master (not .ng), because make install feature was introduced before hyperion(.legacy)  feature freeze. youe rember? You asked for that feature ....
(of course git path needs a change)

**Comment by NicoHood** [comment]
I see. I added /usr and it seems to be fixed now. You can find my PKGBUILD here:
https://gist.github.com/NicoHood/4a020d59e30833da9e23bb1e80ab5c42

So will you keep all service files with the make install command? If yes I'd rather symlink them. Or remove, not sure.

BTW: You also forgot a -D for the avahi shared libs. This should be noted in the compile instructions too. Also the x86 option. That'd be really nice :)

Also I am wondering where the grabber went. Its not installed anymore.

**Comment by redPanther** [comment]
keep the files, please no symlink. consider the share/service files as documentation. you have to enable the hyperion service via systemctl enable hyperion. Please do not add this to pkgbuild. It is not nice when a simple package install mess around with your boot sequence. arch is no no-noob distro - user is forced to do the work or better say, user is given the force to make it as they wish

**Comment by NicoHood** [comment]
But if the service is disabled, this will not cause any problems? You just provide the option to do so.

**Comment by redPanther** [comment]
no, this will not make any probs. I can start it manually if I want or I enable it on boot -> this means full control. No ubuntu like - I-put-it-into-your-boot-sequence,-because-I-know-what-you-want-automatism

Perhaps a nice text "to enable it on boot type ...". In debian packages is such a text. Arch users usualy deals with that by their own or a via arch wiki (https://wiki.archlinux.org/)

**Comment by NicoHood** [comment]
No I meant it like this:
`systemctl enable hyperion` will enable the service. But therefor it has to be in a specific location, doesnt it? I just want to place it there, but not enable it.

**Comment by redPanther** [comment]
look at the last line of the script, service file is placed at the right location:
`install -m 644 "$pkgdir/usr/share/hyperion/service/hyperiond.service" "$pkgdir/usr/lib/systemd/system/"`

**Comment by NicoHood** [comment]
I might missunderstand but isnt this the location where all services get placed, but are not essentiall activated? If the path is wrong, which would be the correct path? I possibly missunderstood the wiki.

**Comment by NicoHood** [comment]
Will we get at least a final release tag of the old version? We are currently also discussing it here:
https://aur.archlinux.org/packages/hyperion/

**Comment by brindosch** [comment]
set

**Comment by NicoHood** [comment]
Thanks.
The last version on AUR was `0.1.42-2` however. I do not know about the version schema before, but I am confused that the version number is smaller. Could you explain this real quick please? thanks :)

**Comment by brindosch** [comment]
As tvdzwan said he just played around with it and he never thought about to use a real versioning "system" or schema. I raised it just up to prevent confusion.

**Comment by NicoHood** [comment]
Is the master branch now the equivalent of the beta branch?

**Comment by penfold42** [comment]
I look at it that way - there are releases now that should provide more stable reference points

**Comment by brindosch** [comment]
Yes and yes.
