### ISSUE TITLE
Migrate to more recent rpi_281x

### ISSUE THREAD

**Issue by penfold42** [hyperion-project/hyperion#711]
We need to update the rpi_281x submodules to the later Hyperion-project fork.

It has improved hardware detection that ignores the warranty bit

**Comment by brindosch** [comment]
Has this something to do with Pi3 fix?

**Comment by penfold42** [comment]
https://hyperion-project.org/threads/unable-to-initialize-ws281x-library.258/#post-2029

**Comment by brindosch** [comment]
Edit: hm, just change to out fork?
I will push out a new release. This includes also the fix for the Pi zero with the new hw revision?

**Comment by penfold42** [comment]
It definitely has the warranty code in it.

I have t checked the latest commits - you might need to merge them to the sk6812 branch

**Comment by penfold42** [comment]
The latest commit in master isn't in the sk6812 branch:
https://github.com/jgarff/rpi_ws281x/commit/7d47edce1b14837fec2c16cbbd3420ef32e717bf
