### ISSUE TITLE
Hyperion lightberry config not working.

### ISSUE THREAD

**Issue by dentinox** [hyperion-project/hyperion#718]
I can't seem to get the leds working using the hyperconfig tool. They work, but they are not capturing like it should. I guess it has something to do with the blackborderdetection. It also seems that when using the hyperconfig tool, the leds also respond to the kodi background colors.

When I use the kodi lightberry addon, it works like it should. Colors respond to black borders, leds don't respond to kodi background, but the plugin won't let me set the color mode BGR, and won't let me set the first led to the left bottom. I can edit the json file from, RGB to BGR, but nothing changes. It only changes if I set it at the top of the config file.

[Hyperion.config.json :](https://hyperion-project.org/attachments/hyperion-config-json.493/)
This is the config file of the kodi plugin. Which responds to blackborders, no kodi background light, but can't set it to the right color and right led offset.

[Hyperconfigtool_working-hyperion.config.json](https://hyperion-project.org/attachments/hyperconfigtool_working-hyperion-config-json.494/)
This is the right file where the leds and color mode is set right and is working. Only problem is that it won't use certain leds in e.g lasershow. I guess the problem is borderdetection. This is showing kodi background light (which I don't need)

**Comment by brindosch** [comment]
duplicate
