### ISSUE TITLE
cant update/reinstall Hyperion

### ISSUE THREAD

**Issue by RyoSaeba2k6** [hyperion-project/hyperion#731]
I've had a problem that hyperion had by reading h264 files and blacked the screen. I've wanted to update the Hyperion with the Hypercon V1.03.1 but its not working it says:
ssh out: 	cd /tmp && curl -# -k -L --output install_hyperion.sh --get https://raw.github.com/hyperion-project/hyperion/master/bin/install_hyperion.sh && sh ./install_hyperion.sh HyperConInstall ; rm install_hyperion.sh
ssh out: 	######################################################################## 100.0%
ssh in: 	*******************************************************************************
ssh in: 	This script will install/update Hyperion Ambient Light
ssh in: 	Created by brindosch - hyperion-project.org - the official Hyperion source.
ssh in: 	*******************************************************************************
ssh in: 	---> Critical Error: CPU information does not match any known releases -> abort

i've did connect to Libreelec 7.90.009 on RPI 3

**Comment by tpmodding** [comment]
on which device? raspberry?

**Comment by RyoSaeba2k6** [comment]
yes, the rasberry Pi 3

**Comment by tpmodding** [comment]
hm, i had the same setup yesterday and it worked...pi3 and libreelec...

could you try this
https://hyperion-project.org/wiki/Installation-with-command-line

**Comment by RyoSaeba2k6** [comment]
the command line shows the same error:
This script will install/update Hyperion Ambient Light
Created by brindosch - hyperion-project.org - the official Hyperion source.
*******************************************************************************
---> Critical Error: CPU information does not match any known releases -> abort

**Comment by tpmodding** [comment]
could you copy your config from

 cat /proc/cpuinfo

**Comment by RyoSaeba2k6** [comment]
LibreELEC:~ # cat /proc/cpuinfo
processor       : 0
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 38.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt                                                                                                                                                              vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 1
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 38.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt                                                                                                                                                              vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 2
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 38.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt                                                                                                                                                              vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 3
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 38.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt                                                                                                                                                              vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

Hardware        : BCM2835
Revision        : a02082
Serial          : 0000000029f6f0ef

**Comment by tpmodding** [comment]
https://de.wikipedia.org/wiki/Raspberry_Pi#Hardware

sure that is a pi3?

where did you buy it?

**Comment by RyoSaeba2k6** [comment]
yes im sure. its from Pollin electronic, the bill says Pi3 Model B BCM2837 Quad

**Comment by RyoSaeba2k6** [comment]
ive opened the case an took a photo. its a Pi 3
[](https://picload.org/image/raaorrcr/dsc_0001.jpgl)

**Comment by brindosch** [comment]
Additional question, are these builds now 64bit instead 32bit?

**Comment by brindosch** [comment]
Added it to the script, please report back if hyperion is really working/running after configuration

**Comment by RyoSaeba2k6** [comment]
h out: 	cd /tmp && curl -# -k -L --output install_hyperion.sh --get https://raw.github.com/hyperion-project/hyperion/master/bin/install_hyperion.sh && sh ./install_hyperion.sh HyperConInstall ; rm install_hyperion.sh
ssh out: 	######################################################################## 100.0%
ssh in: 	*******************************************************************************
ssh in: 	This script will install/update Hyperion Ambient Light
ssh in: 	Created by brindosch - hyperion-project.org - the official Hyperion source.
ssh in: 	*******************************************************************************
ssh in: 	---> Stop Hyperion, if necessary
ssh in: 	---> Critical Error: Target platform unknown -> abort

**Comment by RyoSaeba2k6** [comment]
I've wrote a bug info at the Libre Elec forum. They say its ok and still 32 bit.
https://forum.libreelec.tv/thread-2876-post-22610.html#pid22610

**Comment by RyoSaeba2k6** [comment]
Its works now. I've tryed it today an its installed all fine.
