### ISSUE TITLE
Invalid ACK:

### ISSUE THREAD

**Issue by matze19999** [hyperion-project/hyperion#734]
Hey,

everytime I start hyperion I get the error message "Invalid ACK:"
Can somebody help?

thanks
![1](https://cloud.githubusercontent.com/assets/13684520/21074907/47b89b4e-bf05-11e6-9ebf-d3e43a2d5a71.PNG)

**Comment by penfold42** [comment]
Weird - I can't find that in the code.

Is this a recent install ?

**Comment by matze19999** [comment]
Yeah, it is

penfold42 <notifications@github.com> schrieb am Sa., 10. Dez. 2016, 22:35:

**Comment by penfold42** [comment]
How did you install ? Where did you get this bits from ?

What's your led device type ?

**Comment by matze19999** [comment]
I downloaded it via github with git clone and compiled it.
Im using ws2801 leds

**Comment by Paulchen-Panther** [comment]
This Message is not from Hyperion. Another Library? QT Version? OS? ldd output?

**Comment by Paulchen-Panther** [comment]
config please

**Comment by matze19999** [comment]
Here is my config file. Os is Ubuntu
[hyperion.config.json.txt](https://github.com/hyperion-project/hyperion/files/644070/hyperion.config.json.txt)

**Comment by penfold42** [comment]
The leddevice type looks weird - odlight ?

**Comment by matze19999** [comment]
For odroid c2

penfold42 <notifications@github.com> schrieb am Sa., 10. Dez. 2016, 22:50:

**Comment by Paulchen-Panther** [comment]
What is this?
`"xbmcAddress" : "::1",`

**Comment by matze19999** [comment]
Same like localhost

Paulchen Panther <notifications@github.com> schrieb am Sa., 10. Dez. 2016,
22:51:

**Comment by Paulchen-Panther** [comment]
IPv6 loopback address is "::1"
Please try it with 127.0.0.1

**Comment by Paulchen-Panther** [comment]
Kodi Version?

**Comment by penfold42** [comment]
Where did you git clone from ?

**Comment by matze19999** [comment]
@Paulchen-Panther  16.1 Jarvis
@penfold42 From this page

**Comment by Paulchen-Panther** [comment]
Hardware Firewall?

**Comment by matze19999** [comment]
No

Paulchen Panther <notifications@github.com> schrieb am Sa., 10. Dez. 2016,
23:36:

**Comment by penfold42** [comment]
Is that someone else's config file ?

There is no led device type of "odlight" that I can find in this fork of Hyperion.

**Comment by Paulchen-Panther** [comment]
Please upload the binary file

**Comment by Paulchen-Panther** [comment]
I think this is from here: https://github.com/bkrepo/hyperion

**Comment by penfold42** [comment]
Too funny - I just found this too...

**Comment by penfold42** [comment]
@bkrepo might know.

@matze19999:
It looks a lot like the adalight protocol.
Does the baud rate match between Hyperion config and the arduino sketch ?

**Comment by matze19999** [comment]
Yes, it does

penfold42 <notifications@github.com> schrieb am So., 11. Dez. 2016, 04:48:

**Comment by redPanther** [comment]
Regarding odlight, please ask the inventor, we havn't wrote that code nor we wern't aware of that this exist.
Btw why you don't use adalight? 
Sketch is here: https://github.com/hyperion-project/hyperion.ng/blob/master/assets/firmware/arduino/adalight/adalight.ino

**Comment by matze19999** [comment]
Because i have a tutorial found where everything is good described. 
You can find it at page 22.
[ODROID-Magazine-201611.pdf](https://github.com/hyperion-project/hyperion/files/644359/ODROID-Magazine-201611.pdf)

**Comment by penfold42** [comment]
I found that article too. It's the only way I knew you hadnt cloned the master repo ...

We can help if you're using the adalight sketch.
I don't see any real benefit to the odlight device driver and sketch over adalight.

**Comment by bkrepo** [comment]
@matze19999, 
I added odlight at [this repo](https://github.com/bkrepo/hyperion). Please use that repo if you follow the article of ODROID magazine.

**Comment by penfold42** [comment]
Hi @bkrepo,

How does odlight differ from the adalight protocol ?

Happy to consider a pull request for Hyperion.ng if there's an advantage over adalight.

**Comment by bkrepo** [comment]
@penfold42,
odlight is similar to adalight. Only the prefix in header is different. ('ada' -> 'od')
Additionally, odlight has ACK packet in order to check the data transmission validation.
odlight is small custom protocol from adalight. 
Is it still valuable to do a pull request for Hyperion.ng?

**Comment by penfold42** [comment]
Maybe we could merge the 2 drivers

**Comment by redPanther** [comment]
Is odlight a special device you can buy or is it just another arduino protocol. If so I wouldn't add it to hyperion. We have already to ada's and tpm2. Another thing is sending ack reduces performance and is not neccessary for lightning purpose. Ada already contains a checksum, so we detect transmission errors.

**Comment by matze19999** [comment]
Sorry for the noob question but what means "ACK" ?

**Comment by tpmodding** [comment]
acknowledgement

https://en.wikipedia.org/wiki/Transmission_Control_Protocol#Connection_establishment

**Comment by matze19999** [comment]
Thanks!
