### ISSUE TITLE
ubuntu xenial impossible to compile.

### ISSUE THREAD

**Issue by derdigge** [hyperion-project/hyperion#735]
i used hyperion for a long period on ubuntu trusty today i decided to upgrade to xenial. i was not able to compile hyperiond/x11. cmake parameters are from another issue here. 

i did:

root@Glotzkiste:~# git clone --recursive https://github.com/tvdzwan/hyperion.git
Cloning into 'hyperion'...
remote: Counting objects: 8678, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 8678 (delta 3), reused 0 (delta 0), pack-reused 8670
Receiving objects: 100% (8678/8678), 6.78 MiB | 1.14 MiB/s, done.
Resolving deltas: 100% (5549/5549), done.
Checking connectivity... done.
Submodule 'dependencies/external/protobuf' (https://github.com/tvdzwan/protobuf.git) registered for path 'dependencies/external/protobuf'
Submodule 'dependencies/external/rpi_ws281x' (https://github.com/hyperion-project/rpi_ws281x.git) registered for path 'dependencies/external/rpi_ws281x'
Cloning into 'dependencies/external/protobuf'...
remote: Counting objects: 1053, done.
remote: Total 1053 (delta 0), reused 0 (delta 0), pack-reused 1053
Receiving objects: 100% (1053/1053), 2.03 MiB | 780.00 KiB/s, done.
Resolving deltas: 100% (543/543), done.
Checking connectivity... done.
Submodule path 'dependencies/external/protobuf': checked out 'efb59b79e5a8f26eae4d15f38bbfb5667e23df60'
Cloning into 'dependencies/external/rpi_ws281x'...
remote: Counting objects: 433, done.
remote: Total 433 (delta 0), reused 0 (delta 0), pack-reused 433
Receiving objects: 100% (433/433), 212.00 KiB | 0 bytes/s, done.
Resolving deltas: 100% (267/267), done.
Checking connectivity... done.
Submodule path 'dependencies/external/rpi_ws281x': checked out '48d5e1af37fab4970f374d9d98e46bf5ebefa794'
root@Glotzkiste:~# cd hyp*
root@Glotzkiste:~/hyperion# cmake -DENABLE_DISPMANX=OFF -DENABLE_SPIDEV=OFF -DENABLE_X11=ON -DENABLE_V4L2=OFF -DENABLE_PROTOBUF=OFF
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- ENABLE_ZEROCONF = OFF
-- ENABLE_AMLOGIC = OFF
-- ENABLE_DISPMANX = OFF
-- ENABLE_FB = OFF
-- ENABLE_OSX = OFF
-- ENABLE_SPIDEV   = OFF
-- ENABLE_TINKERFORGE = ON
-- ENABLE_V4L2 = OFF
-- ENABLE_WS2812BPWM = OFF
-- ENABLE_WS281XPWM = OFF
-- ENABLE_X11 = ON
-- ENABLE_QT5 = OFF
-- ENABLE_TESTS = OFF
-- ENABLE_PROFILER = OFF
-- Current Version: master (GitHub-69f4b32/6445c35-1481143098)
-- Looking for Q_WS_X11
-- Looking for Q_WS_X11 - found
-- Looking for Q_WS_WIN
-- Looking for Q_WS_WIN - not found
-- Looking for Q_WS_QWS
-- Looking for Q_WS_QWS - not found
-- Looking for Q_WS_MAC
-- Looking for Q_WS_MAC - not found
-- Found libusb-1.0:
--  - Includes: /usr/include/libusb-1.0
--  - Libraries: /usr/lib/x86_64-linux-gnu/libusb-1.0.so
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8")
-- Looking for dlfcn.h
-- Looking for dlfcn.h - found
-- Looking for inttypes.h
-- Looking for inttypes.h - found
-- Looking for memory.h
-- Looking for memory.h - found
-- Looking for stdint.h
-- Looking for stdint.h - found
-- Looking for stdlib.h
-- Looking for stdlib.h - found
-- Looking for strings.h
-- Looking for strings.h - found
-- Looking for string.h
-- Looking for string.h - found
-- Looking for sys/stat.h
-- Looking for sys/stat.h - found
-- Looking for sys/types.h
-- Looking for sys/types.h - found
-- Looking for unistd.h
-- Looking for unistd.h - found
-- Protobuf: doing try-compiles for hash map/set headers
-- Protobuf: doing try-compiles for pthread test
-- Looking for stddef.h
-- Looking for stddef.h - found
CMake Warning (dev) at dependencies/external/protobuf/src/CMakeLists.txt:324 (get_target_property):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The LOCATION property should not be read from target "protoc_compiler".
  Use the target name directly with add_custom_command, or use the generator
  expression $<TARGET_FILE>, as appropriate.

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Using protobuf compiler: /root/hyperion/bin/protoc
-- Found PythonLibs: /usr/lib/x86_64-linux-gnu/libpython2.7.so (found version "2.7.12")
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- Found Qt4: /usr/bin/qmake-qt4 (found version "4.8.7")
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
X11_Xrender_LIB (ADVANCED)
    linked by target "hyperion-x11" in directory /root/hyperion/src/hyperion-x11

-- Configuring incomplete, errors occurred!
See also "/root/hyperion/CMakeFiles/CMakeOutput.log".
See also "/root/hyperion/CMakeFiles/CMakeError.log".

qt dev is installed in current version. Whats wrong?

**Comment by penfold42** [comment]
Googling the error suggests;

The XRender library could not be found. Please install the development package for it.

**Comment by penfold42** [comment]
Did you do this ?

# Install the required tools and dependencies
sudo apt-get update
sudo apt-get install git cmake build-essential libQt4-dev libusb-1.0-0-dev python-dev libxrender-dev python

**Comment by derdigge** [comment]
Hi! 

This one fails:
root@Glotzkiste:~# apt-get install git cmake build-essential libQt4-dev libusb-1.0-0-dev python-dev libxrender-dev python
Paketlisten werden gelesen... Fertig
Abh▒ngigkeitsbaum wird aufgebaut.
Statusinformationen werden eingelesen.... Fertig
E: Paket libQt4-dev kann nicht gefunden werden.

so i did:
apt-get install git cmake build-essential libqt4-dev libusb-1.0-0-dev python-dev libxrender-dev python

and now: (only warning is left)
root@Glotzkiste:~/hyperion# cmake -DPLATFORM=x86
-- ENABLE_ZEROCONF = OFF
-- ENABLE_AMLOGIC = OFF
-- ENABLE_DISPMANX = OFF
-- ENABLE_FB = OFF
-- ENABLE_OSX = OFF
-- ENABLE_SPIDEV   = OFF
-- ENABLE_TINKERFORGE = ON
-- ENABLE_V4L2 = OFF
-- ENABLE_WS2812BPWM = OFF
-- ENABLE_WS281XPWM = OFF
-- ENABLE_X11 = ON
-- ENABLE_QT5 = OFF
-- ENABLE_TESTS = OFF
-- ENABLE_PROFILER = OFF
-- Current Version: master (GitHub-69f4b32/6445c35-1481143098)
-- Found libusb-1.0:
--  - Includes: /usr/include/libusb-1.0
--  - Libraries: /usr/lib/x86_64-linux-gnu/libusb-1.0.so
CMake Warning (dev) at dependencies/external/protobuf/src/CMakeLists.txt:324 (get_target_property):
  Policy CMP0026 is not set: Disallow use of the LOCATION target property.
  Run "cmake --help-policy CMP0026" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The LOCATION property should not be read from target "protoc_compiler".
  Use the target name directly with add_custom_command, or use the generator
  expression $<TARGET_FILE>, as appropriate.

This warning is for project developers.  Use -Wno-dev to suppress it.

-- Using protobuf compiler: /root/hyperion/bin/protoc
-- Configuring done
-- Generating done
-- Build files have been written to: /root/hyperion

**Comment by derdigge** [comment]
Where did you pick that from in my compilehowto.txt there is no such line? Even a quick look at the wiki didnt pointet me there.

Thanks for your help!

**Comment by penfold42** [comment]
https://github.com/hyperion-project/hyperion/blob/master/CompileHowto.txt

Line 3

**Comment by derdigge** [comment]
too bad i "overscrolled" that, sorry for bothering arround here. Anyway, there is a mistake for at least xenial it has to be:

apt install git cmake build-essential libqt4-dev libusb-1.0-0-dev python-dev libxrender-dev python

the Qt4 just fails. lowercase works. Thanks for your effort!

**Comment by penfold42** [comment]
thanks for the update.

If you're into bleeding edge testing, Hyperion.ng is getting to a reasonable state.

**Comment by derdigge** [comment]
Sure i will do. I do have two 2812b installations with arduino in between.(both x86_64 xenial) 
There is also an testinstallation on openatv on vu+ solo4k box. I didnt found a suitable crosscompiler for it but willing to test also.

As we are off topic allready .... why is there an complete rewrite necessary ?

**Comment by redPanther** [comment]
Hyperion.ng is not a rewrite, just a major version. We switch to qt5 and other things. We want to keep development separate, so we do not disturb stable hyperion

**Comment by derdigge** [comment]
okay, thanks.

**Comment by tpmodding** [comment]
There is also an testinstallation on openatv on vu+ solo4k box. I didnt found a suitable crosscompiler for it but willing to test also.

-> if you use boblight, you dont need a usb-grabber

**Comment by derdigge** [comment]
Some more offtopic :)

Correct me please, it iam wrong. Afaik there is no boblight client for arm receivers like dm900 and solo 4K. Only mips is available in the forums. 

I am going to build my own framegrabber if needed with python. The same way openwebif is taking the screenshots. At the moment, this is only an idea but it could work on all platforms which provide python.

I do not have that much experience in These Linux receivers but i think it's doable.

**Comment by tpmodding** [comment]
oh didnt know that the new ones are arm-based...

maybe you could write a enigma-hyperion-client :))

**Comment by derdigge** [comment]
I am well skilled with bash/ash JavaScript and Linux but there is not that much experience with c. Bash is like is available on all these devices but not the best choice for timecritical processes. Phython is easy to learn I think so this is the way to go. At first I need to have a running Hyperion daemon on these arm boxes, there is a high demand in enigma community's.

Personaly i always prefer a good Kodi box above an enigma box but my father thinks different.... so challenge accepted :)

**Comment by derdigge** [comment]
Is there an documentation how to communicate to that json interface of Hyperion?

**Comment by penfold42** [comment]
I just use hyperion-remote with the --print option to dump the json it uses
