### ISSUE TITLE
hyperion not work with more than 254 leds

### ISSUE THREAD

**Issue by jonudewux** [hyperion-project/hyperion#736]
When I put 254 leds in config file, everything is working fine, and I see startup effect.
With 255 or more leds in config file, leds are not working, also there is no error messages from hyperiond.
[config](https://gist.github.com/jonudewux/7bd7b57b3b80ce4aeb6347ffde32b25d) file with 254 leds.

**Comment by penfold42** [comment]
What are you using to receive the data ?

**Comment by jonudewux** [comment]
wifi udp receiver based on esp8266

**Comment by tpmodding** [comment]
with which sketch?

**Comment by penfold42** [comment]
Last I saw, the esp8266 doesn't do fragmented packet reassembly which limits this simple raw protocol (==0) to about 450 leds.
https://github.com/penfold42/stuff/blob/master/ESP-udp-neo.ino Works fine for <450 leds


Protocol 1 and 2 were my early attempts at chunking the updates - I can't remember which worked. My sketch above implements one of these.

Protocol 3 is probably what you want if you can find the sketch that implements tpm2net.

**Comment by jonudewux** [comment]
It was a issue on receiver side now, 32x8 led panel is running wonderful.
@tpmodding 
I didn't like sketches, is pure C implementation and is running under freertos.
