### ISSUE TITLE
LEDs too dark when disabling overscan in raspi config.txt

### ISSUE THREAD

**Issue by salami738** [hyperion-project/hyperion#741]
Hi,

i have the following setup: 
Sony KDL-50W805C (50" Android TV with 1920x1080px),
Raspi 3, Hyperion V1.03.2 brindosch-99d9396/d3713a8-1469452981,
WS2801 LED stripe (34 top/bottom, 20 left/right),
5V 8A Meanwell power source.

My tv has the problem, that overscan cant be disabled in the tv menu, So i have to use (/boot/config.txt):
```
disable_overscan=1
overscan_left=32
overscan_right=32
overscan_top=16
overscan_bottom=16
```
To use all pixels of the tv. If i dont use this, i have 32 black pixels left and right and 16 black pixels top and bottom.

If I start Hyperion and the "black edge detection" is activated, then the LEDs are much too dark (about 25% brightness). 

If i disable the "black edge detection" or use the set color feature from hypercon, all LEDs have the correct maximum brightness.

If you need additional infos or config files, let me know.

Greetings from germany.

**Comment by Paulchen-Panther** [comment]
Könntest du uns, deine config Datei zur Verfügung stellen?
Besser wäre es noch, im [Forum](https://hyperion-project.org/) einen neuen Thread mit deinem Problem zu eröffnen.
Vielen Dank.

Paulchen

**Comment by salami738** [comment]
Forum Thread unter: https://hyperion-project.org/threads/right-leds-are-darker-than-the-other-ones.643/

**Comment by salami738** [comment]
Anbei meine Config:

[hyperion.config.json.zip](https://github.com/hyperion-project/hyperion/files/737774/hyperion.config.json.zip)

**Comment by salami738** [comment]
Mit der folgenden Einstellung geht es nun:
```
	// BLACKBORDER CONFIG
	"blackborderdetector" : 
	{
		"enable" : true,
		"threshold" : 0.21,
		"unknownFrameCnt" : 600,
		"borderFrameCnt" : 50,
		"maxInconsistentCnt" : 10,
		"blurRemoveCnt" : 1,
		"mode" : "default"
	},
```

Anscheinend schneidet das den nicht sichtbaren schwarzen Rand zuverlässig ab.
Damit ist es wohl kein Bug, da durch Konfiguration lösbar.

**Comment by salami738** [comment]
danke für eure Mühe und macht weite so mit eurem Projekt! Werde mir das NG auch mal angucken, wenn es raus kommt
