### ISSUE TITLE
Cannot open UART because of hardcoded path

### ISSUE THREAD

**Issue by simonszu** [hyperion-project/hyperion#745]
Hi,

the current version of hyperion cannot open the UART on a Raspi GPIO, probably because of a hardcoded path. The error message during startup of hyperion is:
```
eb 16 18:04:55 calad hyperiond[343]: Opening UART: /dev/ttyACM0
Feb 16 18:04:55 calad hyperiond[343]: Unable to open RS232 device (IO Exception (2): No such file or directory, file /home/sascha/hyperion/dependencies/build/se... line 100.)
```

I am quite sure, because my home directory isn't called /home/sascha. I'm sorry i cannot provide more details, but apparently my screen size is too small to display all the error line, and it has no line wrapping. I have no config pointing to /home/sascha in my hyperion.config.json either.

**Comment by redPanther** [comment]
device path is not hardcoded! it's an option in config file. When you start hyperiond you have to supply your personal  config:
e.g. `/storage/hyperion/bin/hyperiond /storage/hyperion/my.config.json`
I don't know where your hyperion is installed so you have to adapt the path by your self.
