### ISSUE TITLE
Eagle files for 74HCT08 board

### ISSUE THREAD

**Issue by sebastiancretu** [hyperion-project/hyperion#746]
Hi,

Could you please also upload the Eagle files / printable files (toner transfer) for the 74HCT08 board? I couldn't find them anywhere with a link that works. Thanks.

**Comment by redPanther** [comment]
who is "you"? can yo adress someone or refer where you get the idea that we - the hyperion devs - can have such files.

for simple level shifter buy a ready made module: e.g. https://www.amazon.de/Kan%C3%A4le-Logic-Konverter-Bidirektionale-Shifter/dp/B00ZC6B8VM
it's unbeatable cheap and you don't have any work with making your own pcb.
