### ISSUE TITLE
Keep Pi on all the time?

### ISSUE THREAD

**Issue by Gershy13** [hyperion-project/hyperion#760]
Im new to this whole ambilight thing, and im wondering, should i leave the pi on when the tv and devices are off? Or should i turn it off. And what about the LEDs? Should i just turn off the led power supply every time i turn off the tv? 
The Pi and the LEDs are running off different power supplies. 
I was thinking of just leaving the pi and grabber and everything else on, and only when i need the ambilight, i turn the LED power supply on? Is this safe?

Also slightly unrelated, but do i need to overclock the pi, or should i just leave it normal?

Thanks
Gershy13

**Comment by RickDB** [comment]
Pi is meant to run 24/7 so no problems with that, LEDs while off use very little but if you want to conserve power or don't fully trust the power supply to run all the time a would turn that off while not using the system.

Cleaning up the issue tracker a bit and not this a "bit late" of a response but can always ask on our forums as this better for these kind of questions.
