### ISSUE TITLE
logger missing

### ISSUE THREAD

**Issue by michaelaye** [hyperion-project/hyperion#762]
The documentation here: http://docs.hyperion-rt.org/en/stable/advanced/logger.html?highlight=logger
indicates the availability of a hyperion logger, but accessing it as described failed:

![screenshot 2017-09-07 16 17 04](https://user-images.githubusercontent.com/69774/30187834-9b45b5ae-93e8-11e7-962e-6ee0e9629c52.png)

My system:
Python 3.5 on macOSX, via conda, using channel conda-forge

**Comment by brindosch** [comment]
Oh, it seems that you are at the wrong place.
-> https://github.com/hyperion-rt/hyperion

**Comment by michaelaye** [comment]
oops, sorry.
