### ISSUE TITLE
How can I get SSIS to connect to an Oracle Hyperion Essbase cube to use it as a data source?

### ISSUE THREAD

**Issue by srinivas736** [hyperion-project/hyperion#763]
SSIS to connect to an Oracle Hyperion EssbaseA comparable question was gotten some information about a particular rendition with no genuine answer other than "an outsider apparatus can do it."
 
A microsoft SSIS connectors wiki demonstrates you can do this through Star Analytics.
 
Starting with SQL Server 2005 SP2, Reporting Services (SSRS) has an information source association. This item highlight didn't appear to mean any articles for SSIS. One blogger recommended this may have been done as a renumeration game plan back before Oracle bought [Hyperion](https://mindmajix.com/oracle-hyperion-training) since Hyperion started supporting associating with SQL Server 2005 SSAS 3D shapes around then.
 
According to @billinkc he use to interface with it with straight .NET. A bit of burrowing returned Hyperion Application Builder .NET (HAB.NET). At first this seemed, by all accounts, to be a promising arrangement, however it turns out the item was ceased with the 11.1.3 discharge. @billinkc likewise gave a code test now, so I will test it out and check whether this works.
 
Beside permitting the Star Analytics server item which is cost restrictive (for me), are there whatever other arrangements out there?

**Comment by brindosch** [comment]
Hello,
this isn't Oracle Hyperion :)
