### ISSUE TITLE
Hyperion + Openelec + Arduino + Raspberry Pi + WS2812b

### ISSUE THREAD

**Issue by theshorterbus** [hyperion-project/hyperion#765]
I'm running 220 LEDs. Have LED PSU powering the LEDs and share ground with the Arduino Uno. Arduini is connected to a powered usb hub connected to the pi. Hyperion starts up what seems fine, however, I keep getting
 `Unable to open RS232 device (IO Exception (2): No such file or directory, file /home/sascha/hyperion/dependencies/build/serial/src/impl/unix.cc, line 100.)
ssh in: 	Device blocked for 3000 ms
ssh in: 	KODICHECK ERROR: Kodi Connection error (0)
ssh in: 	Device unblocked
ssh in: 	Opening UART: /dev/ttyUSB0` 
over an over again, nothing lights up. I have confirmed it all works before trying to get everything to work together. 

HELP ME I'm lost. I feel like it's the Arduino, but I'm unsure where to start. [Hyperion Log](https://pastebin.com/2qHk9YDV) , [hyperion config](https://pastebin.com/tP97TNxQ)

**Comment by theshorterbus** [comment]
In case it helps, I have a grabber in the rotation of things, that when I use a command to do a screenshot shows successful, however, then I cant find the screenshot on the pi.

**Comment by croaker-1** [comment]
Could you post your config.json file?

**Comment by croaker-1** [comment]
Oops. Sorry...missed that link in your original post.

**Comment by croaker-1** [comment]
Can you confirm your Arduino is on /dev//ttyUSB0? Check your /dev directory for other tty devices. I’ve got a similar setup (Raspbian with an Arduino Uno and USB frame grabber) so I’ll check my config when I get home for clues.

**Comment by theshorterbus** [comment]
From what I can tell, it's showing up as tty41

**Comment by croaker-1** [comment]
Does changing "output" : "/dev/ttyUSB0" to "output" : "/dev/tty41", in your /etc/hyperion.config.json make a difference?

If it helps, my config has this to my Arduino:
"output"     : "/dev/ttyACM0",

**Comment by theshorterbus** [comment]
/dev/tty41 definitely didn't work. Oddly enough when I tried "output" : "/dev/ttyACM0" im still getting refrences to usb0 https://pastebin.com/N8pHRBbj

**Comment by theshorterbus** [comment]
Perhaps it's my Arduino [sketch](https://pastebin.com/F6NAfRL5)?

**Comment by croaker-1** [comment]
I can see from the log you last sent that Hyperion is still looking at usb0:

/storage/.config/hyperion.config.json
in:     LEDDEVICE INFO: configuration:
ssh in:     {
ssh in:         "colorOrder" : "rgb",
ssh in:         "delayAfterConnect" : 0,
ssh in:         "name" : "MyHyperionConfig",
ssh in:         "output" : "/dev/ttyUSB0",
ssh in:         "rate" : 500000,
ssh in:         "type" : "adalight"

I doubt it’s the Arduino but you could rule it out by plugging the Arduino into your Mac/PC and running the Adalight Processing sketch available here:
https://learn.adafruit.com/adalight-diy-ambient-tv-lighting/download-and-install

I definatley looks like it is related to having the correct output device in your Hyperion config. 

To be sure you have the right port check out this article:
https://playground.arduino.cc/Interfacing/LinuxTTY

Particularly this part:
Find what USB port uses Arduino when you plug it into your computer. It can be something like /ttyUSBx or /ttyACMx (this is my case). To find the answer unplug the Arduino from the USB, run a Terminal (Applications > Accessories > Terminal) and type:

	$ cd /dev
	$ ls tty*
	...
	tty8
	tty9
	ttyS0
	ttyS1
	...
Plug in the Arduino into the USB and type in the terminal:

	$ ls tty*
You will find a new device! My case:

	...
	tty8
	tty9
	ttyACM0   <-- New device
	ttyS0
	ttyS1

**Comment by theshorterbus** [comment]
I was using different terminal command before, that worked perfect, I have same result showing ttyACM0
 as my Arduino. Now to figure out why even when changing the config directly within the  pi from putty, I'm still getting USB0

**Comment by theshorterbus** [comment]
1 Step forward, 2 Steps back! haha [Log](https://pastebin.com/zBFVENDZ)

**Comment by croaker-1** [comment]
Do the LEDs display the rainbow test pattern?

**Comment by theshorterbus** [comment]
No. On startup they light up with the default color stated I the Arduino
sketch. After few seconds they shut off, have yet to see them turn on after
initial startup

**Comment by croaker-1** [comment]
Here are a couple more things that may help you troubleshoot your issues:
- connect a known working FTDI connector to the Uno’s RX/TX pins (1 & 2) to see if any communication is taking place between the RPi and Arduino. 

- Change the baud rate to 230400 or 115200 in both your config.json and Arduino sketch. This is can be useful if the issue is being caused by a sub-standard cable or if you are using an inexpensive Uno clone that may have a knockoff UART.
- Test your Arduino config on another system to rule it out as the problem. If it works connected to your computer then you know it is not the problem. It’s always good practice to isolate the faulty compentents this way. This will help you focus your troubleshooting efforts and reduce the guesswork.

**Comment by theshorterbus** [comment]
> FTDI connector
Unfamiliar with this, but I'll look for suggested one and order it. In the meantime I'll get the Arduino running on the computer first again, I did once already, but was a different sketch, and was a while back. Also, I will try lowering bitrate as you advised. Appreciate the help, I'll let you know how that goes!

**Comment by theshorterbus** [comment]
Arduino works fine running different sketch. Before I tried lowering the bitrate however my Raspberry Pi model b failed on me, no longer boots up from an img. So I'm thinking perhaps this was my issue, as I had multiple times it would reboot unexpectedly and times where Hyperion would just stop working in the log, and I would have to reflash an img to get a clear log again.. Waiting for a FTDI connector, but it's from China, so who knows when I will receive it. I will try this again with a model 2 pi I have lying around somewhere, and see if I run into the same issue. Thanks for your help croaker-1! appreciated.
