### ISSUE TITLE
Not compiling with g++ 7.2.0

### ISSUE THREAD

**Issue by BadderBlackBart** [hyperion-project/hyperion#766]
Running Archlinux on a Raspberry Pi 3. The CXX compiler identification is GNU 7.2.0

While building I get the following compilation error:
`hyperion-1.03.2/include/utils/Image.h:165:3: error: there are no arguments to ‘assert’ that depend on a template parameter, so a declaration of ‘assert’ must be available`
`assert(other._width == _width);`
`assert(other._height == _height);`

**Comment by penfold42** [comment]
Try adding to Image.h
#include <cassert>

**Comment by jelly** [comment]
Full error is:
```
[ 24%] Building CXX object libsrc/utils/CMakeFiles/hyperion-utils.dir/ImageResampler.cpp.o
In file included from /tmp/hyperion.git/include/utils/ImageResampler.h:5:0,
                 from /tmp/hyperion.git/libsrc/utils/ImageResampler.cpp:1:
/tmp/hyperion.git/include/utils/Image.h: In member function ‘void Image<Pixel_T>::copy(const Image<Pixel_T>&)’:
/tmp/hyperion.git/include/utils/Image.h:165:3: error: there are no arguments to ‘assert’ that depend on a template parameter, so a declaration of ‘assert’ must be available [-fpermissive]
   assert(other._width == _width);
   ^~~~~~
/tmp/hyperion.git/include/utils/Image.h:165:3: note: (if you use ‘-fpermissive’, G++ will accept your code, but allowing the use of an undeclared name is deprecated)
/tmp/hyperion.git/include/utils/Image.h:166:3: error: there are no arguments to ‘assert’ that depend on a template parameter, so a declaration of ‘assert’ must be available [-fpermissive]
   assert(other._height == _height);
   ^~~~~~
make[2]: *** [libsrc/utils/CMakeFiles/hyperion-utils.dir/build.make:207: libsrc/utils/CMakeFiles/hyperion-utils.dir/ImageResampler.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
[ 24%] Building CXX object src/hyperion-remote/CMakeFiles/hyperion-remote.dir/JsonConnection.cpp.o
```

**Comment by penfold42** [comment]
Try the include above

- I just edited it cos GitHub swallowed half of it cos I didn't put it in code tags

**Comment by jelly** [comment]
@penfold42 Thanks after doing some more reading, I actually figured that out myself ;-)

**Comment by penfold42** [comment]
If you're keen, can you also try hyperion.ng ?

**Comment by brindosch** [comment]
Hello,
at least the cassert is part of it
https://github.com/hyperion-project/hyperion.ng/blob/master/include/utils/Image.h#L8

I might add a continuous test against recent version of essential parts
