### ISSUE TITLE
Hyperion + WS2812b + Raspberry Pi Model B+ v1.2

### ISSUE THREAD

**Issue by theshorterbus** [hyperion-project/hyperion#769]
[Log](https://pastebin.com/nN4n7fqt) | [config](https://pastebin.com/57u7RfPC) I get rainbow swirl on start, then nothing. It's working from SSH Hyperion mobile app, but I cannot get it to work from Hyperion desktop app, JSON, PROTO, or Grabber.

**Comment by theshorterbus** [comment]
`/storage/.config/autostart.sh > /dev/null 2>&1 &
ssh out: 	cat /storage/logfiles/hyperion.log
ssh in: 	Hyperion Ambilight Deamon (630)
ssh in: 		Version   : V1.03.3 (brindosch-2fbbcff/2f01dfa-1495880388
ssh in: 		Build Time: Jun  3 2017 02:06:37
ssh in: 	INFO: Selected configuration file: /storage/.config/hyperion.config.json
ssh in: 	HYPERION INFO: ColorTransform 'default' => [0; 217]
ssh in: 	HYPERION INFO: ColorCorrection 'default' => [0; 217]
ssh in: 	HYPERION INFO: ColorAdjustment 'default' => [0; 217]
ssh in: 	LEDDEVICE INFO: configuration: 
ssh in: 	{
ssh in: 		"colorOrder" : "rgb",
ssh in: 		"leds" : 256,
ssh in: 		"name" : "ambilight",
ssh in: 		"type" : "ws281x"
ssh in: 	}
ssh in: 	whiteAlgorithm ::
ssh in: 	HYPERION INFO: Json forward to 127.0.0.1:19446
ssh in: 	HYPERION INFO: Proto forward to 127.0.0.1:19447
ssh in: 	INFO: Creating linear smoothing
ssh in: 	HYPERION (CS) INFO: Created linear-smoothing(interval_ms=50;settlingTime_ms=200;updateDelay=0
ssh in: 	EFFECTENGINE INFO: 27 effects loaded from directory /storage/hyperion/effects
ssh in: 	EFFECTENGINE INFO: Initializing Python interpreter
ssh in: 	INFO: Hyperion started and initialised
ssh in: 	INFO: Boot sequence 'Rainbow swirl fast' EFFECTENGINE INFO: run effect Rainbow swirl fast on channel 0
ssh in: 	BLACKBORDER INFO: threshold set to 0.01 (3)
ssh in: 	BLACKBORDER INFO: mode:default
ssh in: 	started
ssh in: 	INFO: Kodi checker created and started
ssh in: 	terminate called after throwing an instance of 'std::runtime_error'
ssh in: 	  what():  JSONSERVER ERROR: could not bind to port
ssh in: 	Aborted (core dumped)`

**Comment by theshorterbus** [comment]
I'm able to get screen grab, had free green lines, but it's working, and SSH on the mobile app works great. However I keep getting a kodi error, and Hyperion wont startsceen capture to spit out led response

**Comment by penfold42** [comment]
JSONSERVER ERROR: could not bind to port

Either something else is using that port or you have another instance running

The forums at https://hyperion-project.org/ will likely get you more help

**Comment by croaker-1** [comment]
Is it possible you have two instances of hyperion running? Run this to see which (if any) process is bound to the JSON server port:

`sudo lsof -i :19446 | grep LISTEN`

If you see something like this:
`COMMAND   PID USER   FD   TYPE             DEVICE SIZE/OFF NODE NAME`
`hyperiond 1002 root    5u  IPv4 0xc5888ae5ba3b545f      0t0  UDP *:19446 (LISTEN)`

Kill all running hyperiond processes:
`sudo killall hyperiond`

Then start hyperiond again.

**Comment by theshorterbus** [comment]
when I used the terminal command through putty 
`sudo lsof -i :19446 | grep LISTEN`
nothing happens, just moves down a space waiting for new string

**Comment by penfold42** [comment]
Try looking for port 19444

**Comment by theshorterbus** [comment]
the same thing. tried 19446, 19445, 19446, and 19447. Also tried the kill all command, and I just get this back.
`killall: hyperiond: no process killed
`

**Comment by theshorterbus** [comment]
after running that, I rebooted everything, including the pc I'm running hypercon from. Open up the .jar and connect, hit start, and I get a cleaner version of the same log from before. 

> SSH Traffic:
ssh connected
ssh out: 	/storage/.config/autostart.sh > /dev/null 2>&1 &
ssh out: 	cat /storage/logfiles/hyperion.log
ssh in: 	Hyperion Ambilight Deamon (2507)
ssh in: 		Version   : V1.03.3 (brindosch-2fbbcff/2f01dfa-1495880388
ssh in: 		Build Time: Jun  3 2017 02:06:37
ssh in: 	INFO: Selected configuration file: /storage/.config/hyperion.config.json
ssh in: 	HYPERION INFO: ColorTransform 'default' => [0; 217]
ssh in: 	HYPERION INFO: ColorCorrection 'default' => [0; 217]
ssh in: 	HYPERION INFO: ColorAdjustment 'default' => [0; 217]
ssh in: 	LEDDEVICE INFO: configuration: 
ssh in: 	{
ssh in: 		"colorOrder" : "rgb",
ssh in: 		"leds" : 218,
ssh in: 		"name" : "ambilight",
ssh in: 		"type" : "ws281x"
ssh in: 	}
ssh in: 	whiteAlgorithm ::
ssh in: 	HYPERION INFO: Json forward to 127.0.0.1:19446
ssh in: 	HYPERION INFO: Proto forward to 127.0.0.1:19447
ssh in: 	INFO: Creating linear smoothing
ssh in: 	HYPERION (CS) INFO: Created linear-smoothing(interval_ms=50;settlingTime_ms=200;updateDelay=0
ssh in: 	EFFECTENGINE INFO: 27 effects loaded from directory /storage/hyperion/effects
ssh in: 	EFFECTENGINE INFO: Initializing Python interpreter
ssh in: 	INFO: Hyperion started and initialised
ssh in: 	INFO: Boot sequence 'Rainbow swirl fast' EFFECTENGINE INFO: run effect Rainbow swirl fast on channel 0
ssh in: 	BLACKBORDER INFO: threshold set to 0.01 (3)
ssh in: 	BLACKBORDER INFO: mode:default
ssh in: 	started
ssh in: 	INFO: Kodi checker created and started
ssh in: 	terminate called after throwing an instance of 'std::runtime_error'
ssh in: 	  what():  JSONSERVER ERROR: could not bind to port
ssh in: 	Aborted (core dumped)

**Comment by penfold42** [comment]
What was the solution?

**Comment by theshorterbus** [comment]
not entirely sure. I reinstalled everything a 4th time, however, I noticed
my grabber toggle was between PAL and NTSC. Pushed it forward, plugged in
the new build, and voila. Maybe the grabber? I tried without a grabber, so
I'm not convinced, and I also had reinstalled multiple time. It's working
at least.
