### ISSUE TITLE
Using JSON client API to send image data to hyperion

### ISSUE THREAD

**Issue by abrenoch** [hyperion-project/hyperion#774]
I'm toying around with sending base64 image data to hyperion over the JSON client API, but I'm running into trouble with a "size of image data does not match the width and height" error.

I found this a bit confusing as I did provide the correct dimensions. So I dug into the code and on line 332 in the file JsonClientConnection.cpp, where that check is performed, it seems to be comparing the size of the image data to the width multiplied by the height multiplied by 3.

Is this a reasonable way to determine the size of the supplied image? The image I was testing has a size of 22,911 bytes and the dimensions 640x400. I'm just not following how that math work I guess! I did encode the image as a jpeg, maybe I should do a png instead?

Just trying to figure out how to get this ticking!

**Comment by penfold42** [comment]
Doesn’t it want it as raw 24 bit?

**Comment by abrenoch** [comment]
Possibly, I was digging around for the expected format but was coming up short. I'll play around with formats and see if I can get a response.

**Comment by penfold42** [comment]
Check out the source for Hyperion-remote - it can set an image from disk

**Comment by abrenoch** [comment]
That seems like a good starting point, thanks for the tip!

I'll close this out and re-open if I run into issues!
