### ISSUE TITLE
problem install hyperion

### ISSUE THREAD

**Issue by gamer06** [hyperion-project/hyperion#780]
i'm with this problem when i try install hyperion, why?

Thanks!!

This script will install/update Hyperion Ambient Light
Created by brindosch - hyperion-project.org - the official Hyperion source.
*******************************************************************************
---> Stop Hyperion, if necessary
---> Install/Update Hyperion dependencies (This may take a while)
---> Downloading the appropriate Hyperion release
2018-02-14 03:39:18 URL:https://sourceforge.net/ [652/652] -> "-" [1]

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
chmod: cannot access ‘/usr/share/hyperion/bin’: No such file or directory
---> Installing systemd script
cp: cannot stat ‘/usr/share/hyperion/services/hyperion.systemd.sh’: No such file or directory
Failed to execute operation: No such file or directory
rm: cannot remove ‘/usr/share/hyperion/services’: No such file or directory
---> Starting Hyperion
Failed to start hyperion.service: Unit hyperion.service failed to load: No such file or directory.
*******************************************************************************
Hyperion Installation/Update finished!
Please download the latest HyperCon version to benefit from new features!
To create a config, follow the HyperCon Guide at our Wiki (EN/DE)!
Wiki: wiki.hyperion-project.org Webpage: www.hyperion-project.org

**Comment by Qballjos** [comment]
Same problem here seems unable to download from sourceforge.net

> 2018-02-14 03:39:18 URL:https://sourceforge.net/ [652/652] -> "-" [1]
> 
> gzip: stdin: not in gzip format

is there an eta on a fix

**Comment by penfold42** [comment]
Ping @brindosch

**Comment by Raijeru** [comment]
i have the same problem. Any ideas how to fix it?

**Comment by Qballjos** [comment]
Wait until sourcefourge is up again

**Comment by tpmodding** [comment]
The sourceforge.net website is temporarily in static offline mode.

Only a very limited set of project pages are available until the main website returns to service.
