### ISSUE TITLE
[Pi 3 Mobel B+ Plus] Unable to initialize ws281x library

### ISSUE THREAD

**Issue by IvanDoganov** [hyperion-project/hyperion#785]
After upgrading to the new Raspberry Pi 3 B+ hyperion stop loading on Libreelec 8.2.4. Log says: "Unable to initialize ws281x library." After searching a bit I found it may be related to the new hardware.

This is my cat/cpuinfo:

`processor       : 0
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 38.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 1
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 38.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 2
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 38.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

processor       : 3
model name      : ARMv7 Processor rev 4 (v7l)
BogoMIPS        : 38.00
Features        : half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32 lpae evtstrm crc32
CPU implementer : 0x41
CPU architecture: 7
CPU variant     : 0x0
CPU part        : 0xd03
CPU revision    : 4

Hardware        : BCM2835
Revision        : a020d3
Serial          : 00000000733a6589`

**Comment by penfold42** [comment]
If you can build from source, you need an upgraded rpi_ws281x library

**Comment by IvanDoganov** [comment]
I can't, unfortunately :(

**Comment by penfold42** [comment]
@brindosch

Are you planning a rebuild any time soon ?
https://github.com/jgarff/rpi_ws281x/commit/caa135d2216400c8f7d4aaff956ba5347a4463ef

**Comment by brindosch** [comment]
Done, just install/update as usual
