### ISSUE TITLE
Website reCAPTCHA outdated and unusable.

### ISSUE THREAD

**Issue by Robert16296** [hyperion-project/hyperion#789]
The reCAPTCHA used on the https://hyperion-project.org website is outdated and at least the contact form (hence this issue) and signup page are unusable. 

![screenshot from 2018-04-04 15-59-53](https://user-images.githubusercontent.com/8398505/38312289-ac9df662-3821-11e8-9285-3e511aa92eca.png)

See http://g.co/recaptcha/upgrade

**Comment by penfold42** [comment]
Thanks Robert

@brindosch ?

**Comment by brindosch** [comment]
Upgraded, thanks for reporting
