### ISSUE TITLE
Support new Philips Hue Entertainment API

### ISSUE THREAD

**Issue by rodydavis** [hyperion-project/hyperion#791]
I currently have a good working Hyperion Setup on a Rasberry PI Zero and LED Strips on my TV. I also have the Philips Hue White and Ambiance lights all throughout my living room. Philips Hue finally announced the API for spatial lights and was curious if this could be intergrated in to the project. I am a developer and can help out. Any ideas?

https://developers.meethue.com/entertainment-blog

https://developers.meethue.com/content/huestacean-low-latency-screen-sync-using-entertainment-api

https://www.reddit.com/r/Hue/comments/7pi19t/heads_up_hue_entertainment_api_is_now_available/

**Comment by penfold42** [comment]
This would be cool - not for me, but for others
I can help tho - I’ve done a bit of Hyperion led device driver worn previously.

I’d recommend doing it for https://github.com/hyperion-project/hyperion.ng/pulse
As it will replace Hyperion classic at some point.

Alll the existing drivers are here:
https://github.com/hyperion-project/hyperion.ng/tree/master/libsrc/leddevice

**Comment by AppleEducate** [comment]
Awesome! I'll check it out.

**Comment by AppleEducate** [comment]
Does it happen if you ssh into the pi? Or the pi directly output video?

**Comment by zlokomatic** [comment]
Im logged into the pi via ssh to start Hyperion
Then i start a video in Kodi and the screen turns black

**Comment by AppleEducate** [comment]
Gotcha, I don't use Kodi because I use a video grabber. Make sure the PI is getting plenty of power. It may be going black because of that. I had something similar happen on Retro PI

**Comment by zlokomatic** [comment]
YouTube are right. Wirth another power supply it is better

**Comment by HazCod** [comment]
Hey @zlokomatic , out of interest, how is the development going?
This would fit nicely on a Raspberry zero.

**Comment by zlokomatic** [comment]
I already pushed it in my fork
https://github.com/zlokomatic/hyperion if you want to try it and did not switch to hyperion.ng yet.

In the config you need to provide the type phillipshueentertainment, the username, clientkey and groupId from the hue api.

Get the username and key from the api with: 
`{
    "devicetype":"hyperion#pi",
    "generateclientkey":true
}`

I just started porting it to .ng but as time is always limited i dont think i will have  it pushed before the end of the week.

**Comment by jazz1138** [comment]
Hey @zlokomatic,

Very nice work indeed. The difference is amazing! I'm using the v4l2 grabber method on a Pi and the instructions provided worked great. The only variation was that the libmbedtls-dev package was required for I assume the clientkey part. Also there was a typo in the device type that tripped me up, it should be "philipshueentertainment" with 1 "l".

In my device section I have also commented out "transitiontime","lightIds" and "switchOffOnBlack" as I assume these are now redundant.

Do you have any further tips on optimising the config for the new API now that we can send more requests to the bridge i.e. smoothing and capture frequencies. I'm also assuming the location settings for Entertainment lights in the Hue App have no effect so the "leds" config section can stay as is.

Thanks again.

**Comment by FabianHertwig** [comment]
@zlokomatic @jazz1138 
Could you provide a guide how I can test this on my raspberry?
Currently I have hyperion running for a led strip and additionally for a PhilipsHue-Device. I set it up as described here: https://hyperion-project.org/wiki/PhilipsHue-Device

How do I install hyperion from your fork? Can you provide the part of the config for the Philips Hue Entertainment device?

**Comment by AppleEducate** [comment]
Hopefully, Philips Hue Integrates directly with Xbox One and PS4. They just launched support for MacOS and Windows so we are getting close. Hyperion support, of course, would be best.

**Comment by zlokomatic** [comment]
If you are able to compile hyperion then just checkout my repository, install libmbedtls-dev
and compile.

To generate the username and clientkey to a POST request to _**http://\<ip-address.of.the.bridge\>/api**_
with body:

```js
{
    "devicetype":"myapplication#myiphone",
    "generateclientkey":true
}
 ```

Get the groupId of the Entertainment group with a 
GET request to _**http://\<ip-address.of.the.bridge\>/api/\<username\>/groups/**_

Now in the hyperion.conf.json

```js
        "device" :
        {
                "name"       : "HueConfig",
                "type"       : "philipshueentertainment",
                "output"     : "\<ip-address.of.the.bridge\>",
                "username"     : "",
                "clientkey"     : "",
                "colorOrder" : "rgb",
                "groupId"   : 5
        },
```

**Comment by FabianHertwig** [comment]
Im not able to compile it myself. Will this be merged sometime?

How do I install libmbedtls-dev and qt4 to be able to compile?

**Comment by zlokomatic** [comment]
Sorry i dont know osmc but you could try getting it from 
https://github.com/ARMmbed/mbedtls and compile it manually

**Comment by oynek** [comment]
This is really much appreciated. I would also love to see a guide for this! <3

**Comment by HazCod** [comment]
@zlokomatic Can you please create a pull request with your changes?

**Comment by croaker-1** [comment]
## Quickstart guide
Here's a quick rundown of how I built this. It is not a complete guide but should be enough to get you started. Hope it helps.

### My setup:
RPi 2 running (minimal) Raspbian GNU/Linux 9.4 (stretch)
Fushicai usbtv007 USB capture device

### Get dependencies
`sudo apt-get update`
`sudo apt-get upgrade`
`sudo apt-get install git cmake build-essential libqt4-dev libusb-1.0-0-dev python-dev \`
`libxrender-dev python libmbedtls-dev`

### Set environment variables
`export HYPERION_DIR="hyperion-master"`
`export FIRMWARE_DIR="raspberrypi-firmware"`

### Clone repo
`git clone --recursive https://github.com/zlokomatic/hyperion.git "$HYPERION_DIR"`
`git submodule init`
`git submodule update`

### Create build directory
`mkdir "$HYPERION_DIR/build"`
`cd "$HYPERION_DIR/build"`

### Generate make files with Hue Entertainment enabled
`cmake -DENABLE_HUEENTERTAINMENT=ON -DCMAKE_BUILD_TYPE=Release -DPLATFORM="rpi-pwm" -Wno-dev ..`

### Build hyperion
`make -j $(nproc)`

### Remove non-release files, copy binaries to /usr/bin
### Create effects folder and copy effects.
`strip bin/*`
`sudo cp ./bin/hyperion-remote /usr/bin/`
`sudo cp ./bin/hyperiond /usr/bin/`
`sudo mkdir -p /opt/hyperion/effects && sudo cp -R ../effects/ /opt/hyperion/`

**Comment by SJunkies** [comment]
@zlokomatic
At first, thank you for the great work!!!

>I just started porting it to .ng but as time is always limited i dont think i will have it pushed before the end of the week.

I know time is always limited, but I'm very interested in your hyperion.ng port ;) 
When can we expect your push, because the targeted end of the week lays more than one month in the past ;) #nopressure THX

**Comment by zlokomatic** [comment]
@SJunkies you are right. I didnt have the time to get stuff done on hyperion.ng but i pushed what i have done so far. Porting to ng is much more work than i initially thought but it should already be working more or less. I cant really tell because i dont have the time to test atm :/

**Comment by SJunkies** [comment]
@zlokomatic great thx!!! 🥇I will try out your repository next weekend. 👍

**Comment by kingunlim** [comment]
i really don't know what the f... im doing, don't get me wrong i have experience but the howtwo is to less.
can someone please help me out here,
i have tried everything from openelec to osmc to raspbian.
i can get the user and group id with the api but i don't know how my config should look after the install.
just the entrys from zlokomatic? please someone help me

**Comment by croaker-1** [comment]
@kingunlim Here is my working config.json :

`{
	// DEVICE CONFIGURATION 
    "device" :
     {
             "name"       : "HueConfig",
             "type"       : "philipshueentertainment",
             "output"     : "<hue hub ip address>",
             "username"     : "<hue api username>",
             "clientkey"     : "<hue api clientkey>",
             "colorOrder" : "rgb",
             "groupId"   : <hue api groupId>
     },
	// COLOR CALIBRATION CONFIG
    "color" :
    {
        "transform" :
        [
            {
                "id"   : "default",
                "leds" : "*",
                "hsv" :
                {
                    "saturationGain" : 1.0000,
                    "valueGain"      : 1.0000
                },
                "red" :
                {
                    "threshold"  : 0.0000,
                    "gamma"      : 1.0000,
                    "blacklevel" : 0.0000,
                    "whitelevel" : 1.0000
                },
                "green" :
                {
                    "threshold"  : 0.0000,
                    "gamma"      : 1.0000,
                    "blacklevel" : 0.0000,
                    "whitelevel" : 1.0000
                },
                "blue" :
                {
                    "threshold"  : 0.0000,
                    "gamma"      : 1.0000,
                    "blacklevel" : 0.0000,
                    "whitelevel" : 1.0000
                }
            }
       ],
        "smoothing" :
        {
            "type"            : "linear",
            "time_ms"         : 200,
            "updateFrequency" : 20.0000
        }
    },

        // BLACKBORDER CONFIG
        "blackborderdetector" : 
        {
                "enable" : true,
                "threshold" : 0.38,
                "unknownFrameCnt" : 600,
                "borderFrameCnt" : 50,
                "maxInconsistentCnt" : 10,
                "blurRemoveCnt" : 1,
                "mode" : "default"
        },


	// BOOTEFFECT CONFIG
	"bootsequence" : 
	{
		"color" : [0,0,0],
		"effect" : "Rainbow swirl fast",
		"duration_ms" : 3000,
		"priority" : 700
	},

	// JSON SERVER CONFIG
	"jsonServer" : 
	{
		"port" : 19446
	},

	// PROTO SERVER CONFIG
	"protoServer" : 
	{
		"port" : 19447
	},

	// EFFECT PATH
	"effects" : 
	{
		"paths" : 
		[
			"/storage/hyperion/effects",
			"/usr/share/hyperion/effects"
		]
	},

	// NO FRAME GRABBER CONFIG
	// NO KODI CHECK CONFIG
	// NO BOBLIGHT SERVER CONFIG
	// NO JSON/PROTO FORWARD CONFIG

	// LED CONFIGURATION
	"leds" : 
	[
		{
			"index" : 1,
			"hscan" : { "minimum" : 0.0000, "maximum" : 0.2000 },
			"vscan" : { "minimum" : 0.0000, "maximum" : 0.2000 }
		},
		{
			"index" : 3,
			"hscan" : { "minimum" : 0.8000, "maximum" : 1.0000 },
			"vscan" : { "minimum" : 0.0000, "maximum" : 0.2000 }
		},
		{
			"index" : 0,
			"hscan" : { "minimum" : 0.8000, "maximum" : 1.0000 },
			"vscan" : { "minimum" : 0.8000, "maximum" : 1.0000 }
		},
		{
			"index" : 2,
			"hscan" : { "minimum" : 0.0000, "maximum" : 0.2000 },
			"vscan" : { "minimum" : 0.8000, "maximum" : 1.0000 }
		}
	],

	"endOfJson" : "endOfJson"
}
`

This config has no frame grabber information because I am running it as a secondary Hyperion instance. It receives frame information forwarded by they primary instance using this entry in the primary config.json:

`"forwarder" :
{
  "proto" : [ "127.0.0.1:19447" ],
  "json"  : [ "127.0.0.1:19446" ]
},
`

This should help you put together your own config.

**Comment by kingunlim** [comment]
Ok, I’ll start from scratch now:
First i’ll flash my raspberry again with raspbian?
after that, i’ll go on with your first quickstart quide @croaker-1 ?
I must first do all your steps, after the last points: Create effects folder and copy effects.
I must edit my hyperion.conf.json file like yours but with my edits, 
I make a conf file and edit it with my changes that i get before like @zlokomatic said.
"name"       : "HueConfig",
             "type"       : "philipshueentertainment",
             "output"     : "<hue hub ip address>",
             "username"     : "<hue api username>",
             "clientkey"     : "<hue api clientkey>",
             "colorOrder" : "rgb",
             "groupId"   : <hue api groupId>

And put the conf file in which directory?
I don’t have a usb grabber or anything just the raspberry and the hue lamps with hue bridge v2 with entertainment group.
Does your config work form me?
How can i start the hyperion plugin after that, i think i must start it again after every reboot?
How can i test the plugin, just install kodi and start a movie?
Thanks for your help.

**Comment by kingunlim** [comment]
i don't know i make everything as i said in my previous post, but i don't think hyperion ist installed after i follow the quickstart guide from @croaker-1 
because i just see a folder unter /home/pi/hyperion-master

is this the right path? 

can someone please help me out, as i said i just want to install hyperion with the new entertainment groups under raspian and i have kodi installed and want to config the grabber for this kodi invironment.

**Comment by kingunlim** [comment]
ok, i'll reinstall everything again ;(
@croaker-1 
1.
can you please tell me, is there anything i must do after i attempt all steps from your quickstart guide, other than put my hyperion.config.json file in the right location?

2.
as i see your quickstart guide pulled the hyperion install from the @zlokomatic repo git,
so the paths are different? 
normally hyperion would install itself to /pi/home/hyperion
but this script will install to /pi/home/hyperion-master

3.
is there anything differnt to the normal hyperion installation, for example:
can i connect with HyperCon.jar to check my configs and stop and start hyperion?

4.
maybe you can also have a look at my posted config file here to check if everything is ok, it should  grabb my kodi instance on the same pi

5.
the finish steps would be that my raspberry would grab the kodi from my secound amazon fire tv device if its possible but this is the future plan.



my config file:

> {
	// DEVICE CONFIGURATION 
    "device" :
     {
             "name"       : "HueConfig",
             "type"       : "philipshueentertainment",
             "output"     : "192.168.",
             "username"     : "wAGylqqkqt",
             "clientkey"     : "9348956",
             "colorOrder" : "rgb",
             "groupId"   : 2
     },
	// COLOR CALIBRATION CONFIG
    "color" :
    {
        "transform" :
        [
            {
                "id"   : "default",
                "leds" : "*",
                "hsv" :
                {
                    "saturationGain" : 1.0000,
                    "valueGain"      : 1.0000
                },
                "red" :
                {
                    "threshold"  : 0.0000,
                    "gamma"      : 1.0000,
                    "blacklevel" : 0.0000,
                    "whitelevel" : 1.0000
                },
                "green" :
                {
                    "threshold"  : 0.0000,
                    "gamma"      : 1.0000,
                    "blacklevel" : 0.0000,
                    "whitelevel" : 1.0000
                },
                "blue" :
                {
                    "threshold"  : 0.0000,
                    "gamma"      : 1.0000,
                    "blacklevel" : 0.0000,
                    "whitelevel" : 1.0000
                }
            }
       ],
        "smoothing" :
        {
            "type"            : "linear",
            "time_ms"         : 200,
            "updateFrequency" : 20.0000
        }
    },

        // BLACKBORDER CONFIG
        "blackborderdetector" : 
        {
                "enable" : true,
                "threshold" : 0.38,
                "unknownFrameCnt" : 600,
                "borderFrameCnt" : 50,
                "maxInconsistentCnt" : 10,
                "blurRemoveCnt" : 1,
                "mode" : "default"
        },


	// BOOTEFFECT CONFIG
	"bootsequence" : 
	{
		"color" : [0,0,0],
		"effect" : "Rainbow swirl fast",
		"duration_ms" : 3000,
		"priority" : 700
	},

	// JSON SERVER CONFIG
	"jsonServer" : 
	{
		"port" : 19446
	},

	// PROTO SERVER CONFIG
	"protoServer" : 
	{
		"port" : 19447
	},

	// EFFECT PATH
	"effects" : 
	{
		"paths" : 
		[
			"/storage/hyperion/effects",
			"/usr/share/hyperion/effects"
		]
	},

	// NO FRAME GRABBER CONFIG
	// NO KODI CHECK CONFIG
	// NO BOBLIGHT SERVER CONFIG
	// NO JSON/PROTO FORWARD CONFIG

	// LED CONFIGURATION
	"leds" : 
	[
		{
			"index" : 1,
			"hscan" : { "minimum" : 0.0000, "maximum" : 0.2000 },
			"vscan" : { "minimum" : 0.0000, "maximum" : 0.2000 }
		},
		{
			"index" : 3,
			"hscan" : { "minimum" : 0.8000, "maximum" : 1.0000 },
			"vscan" : { "minimum" : 0.0000, "maximum" : 0.2000 }
		},
		{
			"index" : 0,
			"hscan" : { "minimum" : 0.8000, "maximum" : 1.0000 },
			"vscan" : { "minimum" : 0.8000, "maximum" : 1.0000 }
		},
		{
			"index" : 2,
			"hscan" : { "minimum" : 0.0000, "maximum" : 0.2000 },
			"vscan" : { "minimum" : 0.8000, "maximum" : 1.0000 }
		}
	],

	"endOfJson" : "endOfJson"
}

>

**Comment by croaker-1** [comment]
@kingunlim 

1. As far as I know you can put the config file anywhere (I keep mine in` /etc/config.json`). You just need to reference it in the startup script or on the command line.

`/usr/bin/hyperiond /etc/config.json`

2. The name of the build directory shouldn't matter since you `cd /pi/home/hyperion-master` into it before building.

3. If it builds properly it should work just like the main hyperion fork. When you start Hyperion you should get the rainbow swirl effect on your lights. This is how you know it is talking to your hue hub and lights. Next step is ensure Kodi is talking to your Hyperion server (see below).

4 & 5 Have a look [here](https://hyperion-project.org/wiki/Kodi-Addon) for information on setting up the Kodi add on. I don't run Kodi so am unfamiliar with it but from reading the wiki, the most important bits for you are:

- **Hyperion host IP-address:** the ip address of the pi running hyperion
- **Hyperion host PROTO-port:** needs to match the port used in your hyperion config, in your current configuration it would be 19447
- 

```
// PROTO SERVER CONFIG
"protoServer" : 
{
	"port" : 19447
},

```

Hope that helps.

**Comment by mawi13** [comment]
Hey may somebody can help me out?
I got hyperion with my Hue lamp to work but i have the problem that I'm just using 2 color lights and when i have in my config file;
"leds" : 
	[
		{
			"index" : 5,
			"hscan" : { "minimum" : 0.0000, "maximum" : 1.0000 },
			"vscan" : { "minimum" : 0.0000, "maximum" : 1.0000 }
		},
		{
			"index" : 8,
			"hscan" : { "minimum" : 0.0000, "maximum" : 1.0000 },
			"vscan" : { "minimum" : 0.0000, "maximum" : 1.0000 }
		}
		
	],
- 5 and 8 are the ids from the lamps but when i start hyperion with this config he just finds 2 lamps with id 4 and id 5....
HYPERION INFO: Not creating any smoothing
EFFECTENGINE INFO: 27 effects loaded from directory /opt/hyperion/effects
EFFECTENGINE INFO: 27 effects loaded from directory /opt/hyperion/effects
EFFECTENGINE INFO: Initializing Python interpreter
LedDevicePhilipsHue::saveStates(nLights=2): found light with id 4.
LedDevicePhilipsHue::saveStates(nLights=2): found light with id 5.
INFO: Hyperion started and initialised

Why it just finds 2 lamps and not all 5. when i make 5 entries for leds it finds all 5 light bulbs i have at home but Im not able to get both of them to work.
Thx for your advice in advance

**Comment by kingunlim** [comment]
@croaker-1 
thx bro, i managed to get everything to work,
now i have a little problem with the config file.
atm i just want my 2 lamps to next to my tv left and right.
they are working atm but the colours are not very good and the are very dark,
the lamps are two hue go's.

maybe someone can explain a little bit how does the image grabbing work and how the led id config is working?

**Comment by croaker-1** [comment]
@kingunlim 

I'm glad to hear you got it working. 😊

Have a look at these bits in your config:
```
"hscan" : { "minimum" : 0.0000, "maximum" : 1.0000 },
"vscan" : { "minimum" : 0.0000, "maximum" : 1.0000 }

```
This defines what area of the screen is being used for color sampling for any particular LED. Min is the left(hscan) or top(vscan) corner position and max is the right(hscan) or bottom(vscan) corner position. The example above is sampling your entire screen and returning an average of every color being displayed...which would explain the dark, muddy colors.

The example below would take a color sample of everything within the first 1/4 of the lefthand side of your screen.
```
"hscan" : { "minimum" : 0.0000, "maximum" : 0.2500 },
"vscan" : { "minimum" : 0.0000, "maximum" : 1.0000 }
```

Poor ASCII art representation:
```
+----------------+
|xxxx            |
|xxxx            |
|xxxx            |
|xxxx            |
|xxxx            |
+----------------+
```

There is more info about this here:
https://hyperion-project.org/wiki/hyperion-config-json-with-comments?highlight=json

**Comment by mawi13** [comment]
Yeah i know, this was no accident because I use it with me celing lamp. I tried it with the full screen average because the rroom should look like these, have to check this in practise later on. But may somebody knows how i can get both lamps to work? my ids are 5 and 8 and when i set 2 leds he just finds number 4 and 5 (ids start with 4) also i have the right groupId choosen...

**Comment by kingunlim** [comment]
perfect thx i'll test it with your entrys when i'm at home.

so i'll copy your example for my left go
and maybe you can give me also the entries for my right go?
so the left go led can display 1/4 of the left screen and the right one will display 1/4 of the right screen.

one thing is strange for me,
at the  beginnig of my config i define the entertainment group that have my led id's and the position in the hue app.
but i must add the right led id's from my hue app at the button of the config for it to work.
but the entertainment group should have this values or. why should i define it again of the config.

if im right at the moment just the new protocol is taken from the api and not the led configs?

thx for answering all my stupid questions

**Comment by kingunlim** [comment]
@croaker-1 
i don't know how often do you check this thread, but i hope you don't give up on me ;)

**Comment by cmuckel** [comment]
@kingunlim can you tell me how do you get your environment work? i followed the steps from the quick guide but i am not sure that hyperion is installed correctly....

**Comment by joeblack2k** [comment]
@AppleEducate is it already merged in the NG repro ? i have VMWARE ubuntu running and i have no clue how to build this myself..

**Comment by cmuckel** [comment]
that would be interesting....
independently it would be great if you poeple could post a detailled how-to, for building / installing this hyperion version with the Entertainment API. I followed the steps from @croaker-1 's quick guide but I think there are a few steps I don't consider...

1. Does your version work with HyperCon on Windows? (For SSH Send)
2. What do you mean with the binaries? Which files must be copied to a specific folder?
3. Must a stable version be installed before?

So many questions.. sorry...

**Comment by zlokomatic** [comment]
Hi,

i uploaded the version i compiled on my rpi3 here:
https://www.file-upload.net/download-13297386/hyperion_ng_entertainment.tgz.html

You dont need hypercon anymore as hyperion.ng got a webinterface to configure everything

I did not create a pull request for hyperion,ng as i still did not test it at all :/
But hopefully with these binaries you guys can test and tell me if there are any problems :)

**Comment by cmuckel** [comment]
Okay sorry for my next stupid question.... i understand nothing.. wtf ...
Can anyone tell me, what are the first steps? And what should I do with the files from @zlokomatic  :D

sorry... but I work the first time with github...

**Comment by cmuckel** [comment]
After many attempts it worked!!!! Thank you @zlokomatic 
Learning by Doing :D

I think I found a Bug in the normal Hyperion.ng Version and yours. 

My Hue Lamps don't switch off on black screen. There completely white. But i checked this option in the Dashboard / WebUi. 

Have you any ideas for this problem, guys?

**Comment by CloneBoy83** [comment]
@cmuckel 

i have downloaded the compiled version from @zlokomatic, how can i install this now on mi raspi ?

**Comment by vnizzz** [comment]
Hi, I have Hue working with Hyperion for more over a year now (it's been set up with [this method](https://hyperion-project.org/wiki/PhilipsHue-Device)) therefore I was wondering if anybody can help me to understand if there is any reason to switch to new Entertainment API? Is there any difference in performance?

**Comment by vnizzz** [comment]
I managed to get it working. Thanks @zlokomatic for you work!

Few notes:
- I'm using retropie/raspbian and apparently there is no libmbedtls-dev package there. Therefore in https://github.com/hyperion-project/hyperion/issues/791#issuecomment-405861300 when you would need another step(s) in "Get dependencies" which are 
>mkdir ~/libmbedtls && cd ~/libmbedtls
>git clone --recursive https://github.com/ARMmbed/mbedtls.git
>mkdir build
>cd build/
>cmake -DUSE_SHARED_MBEDTLS_LIBRARY=On ../mbedtls/
>make
>sudo make install
- When you are trying to get a username/key from your hue API you should press the button on the bridge. I believe I knew that but forgot and it took some time for me to realize why my `{ "devicetype":"hyperion#pi", "generateclientkey":true }` isn't working
- I was constantly seeing `"what():  Given group is no entertainment group"` until I found out that it wasn't because of the actual group id, but because of the name of the parameter in the config. Apparently it seems to be case-sensitive and didn't work because it was saying "`groupid: 7`" instead of "`groupId: 7`" (Capital "I")
- While everything is working great the only downside I see in comparison with [previous approach](https://hyperion-project.org/wiki/PhilipsHue-Device) is that I used to be able to take control over lights when there was no signal going through v4l - Hyperion wasn't sending any signal therefore other clients (such as phone app, Alexa, Logitech Harmony, IFTTT etc) could turn it on and off. Plus Hyperion apparently didn't know how to turn lights on and if they were off they would stay this way even if the signal is coming through (Until you turn them on manually). 
I'm wondering if we could have a setting a config "force turn on" and if it's set to `false` - it should read lights' current state and if it's off - let them be. Also I believe it should release control once it sees no signal so other clients could take over it (Stop syncing/close "entertainment" session).
So far it just says "Light sync is active" and no other app/client can't control it until I disable sync manually. 
![img_3174](https://user-images.githubusercontent.com/1895254/45659009-4f328c00-bac0-11e8-82a3-013f0450d330.jpg)

**Comment by kingunlim** [comment]
i don't get it,
does nobody have any problems with blue light?
mine doesn't work correctly at all.
https://imgur.com/a/1ejVSIc

**Comment by AnthraxLeprosyPi** [comment]
> After many attempts it worked!!!! Thank you @zlokomatic
> Learning by Doing :D
> 
> I think I found a Bug in the normal Hyperion.ng Version and yours.
> 
> My Hue Lamps don't switch off on black screen. There completely white. But i checked this option in the Dashboard / WebUi.
> 
> Have you any ideas for this problem, guys?

So this is ready to take out for a spin?

**Comment by AnthraxLeprosyPi** [comment]
> If you are able to compile hyperion then just checkout my repository, install libmbedtls-dev
> and compile with `cmake -DENABLE_HUEENTERTAINMENT=ON -DCMAKE_BUILD_TYPE=Release ..`
> ,
> ```

Hey everybody, just tried to build on a brand new Vero 4k+ - sadly this happens (I installed libmbedtls-dev,/ build it myself): 

CMake Error at CMakeLists.txt:259 (find_package):
  By not providing "FindMbedTLS.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "MbedTLS", but
  CMake did not find one.

  Could not find a package configuration file provided by "MbedTLS" with any
  of the following names:

    MbedTLSConfig.cmake
    mbedtls-config.cmake

  Add the installation prefix of "MbedTLS" to CMAKE_PREFIX_PATH or set
  "MbedTLS_DIR" to a directory containing one of the above files.  If
  "MbedTLS" provides a separate development package or SDK, be sure it has
  been installed.

**Comment by Multisaft7** [comment]
Hey I am using hypercon on my rpi3 with libreelec and also got about 5 hue lamps in my living room... I lost a bit the overview of this thread so is there actually a guide setting up hue entertainment with my current hypercon?

**Comment by kaazvaag** [comment]
> * While everything is working great the only downside I see in comparison with [previous approach](https://hyperion-project.org/wiki/PhilipsHue-Device) is that I used to be able to take control over lights when there was no signal going through v4l - Hyperion wasn't sending any signal therefore other clients (such as phone app, Alexa, Logitech Harmony, IFTTT etc) could turn it on and off. Plus Hyperion apparently didn't know how to turn lights on and if they were off they would stay this way even if the signal is coming through (Until you turn them on manually).
>   I'm wondering if we could have a setting a config "force turn on" and if it's set to `false` - it should read lights' current state and if it's off - let them be. Also I believe it should release control once it sees no signal so other clients could take over it (Stop syncing/close "entertainment" session).
>   So far it just says "Light sync is active" and no other app/client can't control it until I disable sync manually.

@zlokomatic, great work for implementing the Hue entertainment API into hyperion!!

I agree with vnizzz. It is really a bummer when it is not possible to control the lights when there is no signal going through HDMI/Android Grabber.

@zlokomatic, Could you implement that "Hue entertainment mode" is forced to switch off when there is no signal (HDMI/Android grabber). And turn on "Hue entertainment mode" when there is a signal. It is not user friendly when you have to switch off Hue entertainment mode manually using the Hue app.

For example. There is an android app [MrMC](https://github.com/MrMC/mrmc/blob/2eda5d876f3712b0e77fad33b938727211fae00f/xbmc/services/hue/HueServices.cpp) which also has implemented Hue entertainment support. When using that app the Hue entertinment mode starts when playing a video and the Hue entertainment mode stops when the video stops. It would be nice to have this implemented in hyperion so that Hue entertainment will work with any app on my ShieldTV.

**Comment by kingunlim** [comment]
yeah there are some problems with this commit, 
also the colors don't work quite well, blue is the biggest problem, 
and also that hyberion don't stop the entertainment api.
maybe someone can update this things.

**Comment by snickers2k** [comment]
any news on this?

**Comment by daveb121** [comment]
I started out with the standard Hyperion entertainment build and found colours a bit merky even with a very small sample size. I've since switched over to using the Hyperion NG version and found colours to be much better. Every now and again I do get the error  "mbedtls_ssl_handshake FAILED -26624" but restarting  the service solves the problem.. Once started it never fails.

I'd like to give @zlokomatic a huge thank you for this. This has done wonders for my setup - I've configured to start/stop the service via a bash script launched from my tv remote so I've now got an awesome Kodi setup that everyone loves.

**Comment by daveb121** [comment]
The reason for the error is the lights stay streaming for a little while after the service has stopped. If I stop the light sync in the hue app the error doesn't happen... I guess I shouldn't have been stopping and starting the service so quickly.

**Comment by otarie1** [comment]
A Big Thank you to everyone involved! But could someone please compile this for Libreelec/Coreelec and make it available for a wider audience? I'm running the recent Coreelec on an odroid C2 and been trying for weeks to get this going but im always running into errors. Help would be very appreciated.

**Comment by ddluk** [comment]
@zlokomatic Downloaded binaries available by you but after providing configuration for philipshueentertainment:

`    "device": {
        "clientkey": "...",
        "colorOrder": "rgb",
        "groupId": 7,
        "output": "192.168.1....",
        "rewriteTime": 5000,
        "type": "philipshueentertainment",
        "username": "..."
    },`

hyperiond is crashing with following error:

> terminate called after throwing an instance of 'std::out_of_range'
> what():  vector::_M_range_check: __n (which is 4) >= this->size() (which is 4)
> Aborted

I checked with different configuration and it's crashing when valid groupId is provided. When non entertainment group is provided everything is working properly.

**Comment by andytyrer** [comment]
Hi Can someone help me out.

I have compiled everything and run the installer from the hyperion-master/bin folder.

I have added my hyperion.config.json file and started the service.

I get the following error where the service will not start.

ssh in: 	May 19 09:03:25 raspberrypi hyperiond[9881]: LEDDEVICE ERROR: Unknown/Unimplemented device philipshueentertainment

Many thanks.

**Comment by tpmodding** [comment]
@andytyrer 
hyperion is discontinued, please use hyperion.ng
https://github.com/hyperion-project/hyperion.ng
for support use our forum
https://hyperion-project.org/
