### ISSUE TITLE
hyperion apa102 pi3b

### ISSUE THREAD

**Issue by paksilori** [hyperion-project/hyperion#796]
Hi everyone, I just did the hyperion tutorial and can't make my LED's to work.
Connecting thrue ssh my log is this:

Hyperion Ambilight Deamon (552)
ssh in: 		Version   : V1.03.4 (brindosch-c750c41/dc6a602-1522918225
ssh in: 		Build Time: Apr  5 2018 01:57:25
ssh in: 	INFO: Selected configuration file: /storage/.config/hyperion.config.json
ssh in: 	HYPERION INFO: ColorTransform 'default' => [0; 69]
ssh in: 	HYPERION INFO: ColorCorrection 'default' => [0; 69]
ssh in: 	HYPERION INFO: ColorAdjustment 'default' => [0; 69]
ssh in: 	LEDDEVICE INFO: configuration: 
ssh in: 	{
ssh in: 		"colorOrder" : "rgb",
ssh in: 		"name" : "MyHyperionConfig",
ssh in: 		"output" : "/dev/spidev0.0",
ssh in: 		"rate" : 1000000,
ssh in: 		"type" : "apa102"
ssh in: 	}
ssh in: 	INFO: Creating linear smoothing
ssh in: 	HYPERION (CS) INFO: Created linear-smoothing(interval_ms=33;settlingTime_ms=100;updateDelay=0
ssh in: 	EFFECTENGINE INFO: 27 effects loaded from directory /storage/hyperion/effects
ssh in: 	EFFECTENGINE INFO: Initializing Python interpreter
ssh in: 	INFO: Hyperion started and initialised
ssh in: 	terminate called after throwing an instance of 'std::runtime_error'
ssh in: 	  what():  JSONSERVER ERROR: could not bind to port
ssh in: 	Aborted (core dumped)
 

Can anyone help me with thin? 
I did all the checks 10 times, uninstal reinstal hyperion & libraelec.
Thank you

**Comment by Paulchen-Panther** [comment]
This Line:
ssh in: what(): JSONSERVER ERROR: could not bind to port
The JSON Port is busy

Config please!

**Comment by paksilori** [comment]
what is json port?!

**Comment by Paulchen-Panther** [comment]
JSON: https://en.wikipedia.org/wiki/JSON

**Comment by RickDB** [comment]
@paksilori Gonna close this one due to lack of response, feel free to ask on our forums or check out our wiki install section:

https://hyperion-project.org/wiki/2-Installation
