### ISSUE TITLE
Hyperion does not start on Raspberry Pi 3B model

### ISSUE THREAD

**Issue by marrobHD** [hyperion-project/hyperion#802]
OS: osmc
Model: Raspberry Pi 3B

When the system starts I get an error message saying Hyperion could not start. Then I checked Hyperion for "sudo service hyperion status" Hyperion. There is this output;
https://hastebin.com/ogikowowoy.rb

Thanks for help!
~Marlon

**Comment by Paulchen-Panther** [comment]
Please execute `/usr/bin/hyperiond /etc/hyperion/hyperion.config.json` from ssh console and post output result please.
thanks.

**Comment by marrobHD** [comment]
Hyperion Ambilight Deamon (3704)
        Version   : V1.03.4 (brindosch-c750c41/dc6a602-1522918225
        Build Time: Apr  5 2018 01:57:25
ERROR: No valid config found

**Comment by Paulchen-Panther** [comment]
In other words, the configuration file '/etc/hyperion/hyperion.config.json' doesn't exists.
Use hypercon to recreate the config file and then save the config to /etc/hyperion/

**Comment by marrobHD** [comment]
How?

**Comment by Paulchen-Panther** [comment]
What how? Hypercon? Configuration file? Path?
Please, more exactly

**Comment by marrobHD** [comment]
Wo finde ich einen Download Link zum herunterladen von HyperCon?

**Comment by Paulchen-Panther** [comment]
Du kannst deutsch?
[Hypercon](https://hyperion-project.org/wiki/HyperCon-Informationen)

**Comment by marrobHD** [comment]
Klar :)

**Comment by Paulchen-Panther** [comment]
So klar ist das nicht. :)
Wie hast du denn Hyperion auf dem Pi installiert? Selber kompiliert?

**Comment by marrobHD** [comment]
Oh ich habe das Programm ja komplett vergessen. Ich hatte gedacht es reicht erstmal wenn man da nichts einstelt, weil mein Grabber erst kommt und die SK9822 auch erst jetzt bestellt sind. Die SK9822 und die APA102C haben doch das gleiche Protokoll oder täusche ich mich?

**Comment by Paulchen-Panther** [comment]
Hyperion verlangt in der klassischen Version immer eine Konfigurationsdatei als Parameter.
Ob die SK9222 und die APA102C das gleiche Protokoll verwenden kann ich die nicht sagen. Ich verwende die WS2812b.

**Comment by Paulchen-Panther** [comment]
Hier ist eine gute Vergleich der SK9822 und den APA102:
https://cpldcpu.wordpress.com/2016/12/13/sk9822-a-clone-of-the-apa102/

**Comment by Paulchen-Panther** [comment]
Wie oben erklärt. Erstelle die Konfigurationsdatei (hyperion.config.json) mit Hypercon und kopiere diese dann nach /etc/hyperion. Dann sollte dein Dienst auch starten.

**Comment by marrobHD** [comment]
Danke :)

**Comment by marrobHD** [comment]
Eine Frage, wo steh in der Wiki wo man die LED Strips anschließen muss?

**Comment by Paulchen-Panther** [comment]
https://hyperion-project.org/wiki/Supported-hardware
