### ISSUE TITLE
Feature Request: MqTT support to control the Ambilight

### ISSUE THREAD

**Issue by marrobHD** [hyperion-project/hyperion#803]
Model: Raspberry Pi 3B
OS: osmc

That would be my suggestion:

A state topic like "home/tv1" that gives eg. the output: {"state":"ON","color":{"r":255,"g":0,"b":127},"brightness":255,"effect":"solid"} or: {"state":"ON","color":{"r":255,"g":0,"b":127},"brightness":255,"effect":"rainbow"}

A command topic like "home/tv1/set" to which you e.g. can send: {"state": "OFF"} or: {"state": "ON", "color": {"r": 0, "g": 0, "b": 255}} or: {"state": "ON", "effect": "rainbow"}

Thanks in advance
~Marlon

**Comment by RiRomain** [comment]
There is the JSON interface for interaction with third party, I suppose you could write an MQTT client that translate the received command in JSON

https://hyperion-project.org/wiki/hyperion-remote-JSON-interface

**Comment by starkillerOG** [comment]
@marrobHD I also wrote a little python script that translates MQTT (from a milight remote / esp8266_milight_hub) to Hyperion JSON interface. see: https://github.com/starkillerOG/python_scripts_milight
It is the MilightControl.py file.

**Comment by penfold42** [comment]
I’d like to see MQTT support too.

It won’t happen here tho - suggest opening new issue at https://github.com/hyperion-project/hyperion.ng

**Comment by tpmodding** [comment]
As penfold said, it will not happen here..
