### ISSUE TITLE
Bilddaten scheinen immer wieder überschrieben zu werden

### ISSUE THREAD

**Issue by jtkDvlp** [hyperion-project/hyperion#806]
Hallo zusammen,

ich habe das Problem, dass sowohl externen als auch internen Grabber scheinbar die Bilddaten immer wieder überschrieben werden und so die LEDs mit falschen Farben angesteuert werden. Beim Startup blinken die vermutlich richtigen Farben kurz auf (nein ich habe kein Starteffekt eingestellt). Auch bei senden von Farben von der Palette unter dem Reiter "SSH" blinkt nur kurz die ausgewählte Farbe auf und dann ist *immer* ein Verlauf von weiß nach rot gegeben. Ich habe keine Idee mehr was ich noch probieren oder prüfen soll.

Das Problem tritt mit einen Raspberry PI 3B+, Rasbian und WS2812b LEDs (167 Anzahl) auf. Anbei meine Konfig [hyperion.config.zip](https://github.com/hyperion-project/hyperion/files/2728718/hyperion.config.zip)

Bitte um Hilfe!

**Comment by WoLpH** [comment]
This sounds like a hardware issue actually. My guess would be not enough
power, do you have a slightly more powerful power supply to test with? Also
note that long power cables from the strip to the power supply can cause
issues.

**Comment by El-Mare** [comment]
Hi,

had the same problem recently...

Solution can be found here for example:
https://hyperion-project.org/threads/rpi3-ws2812b-spi-ws2812x-spi-not-working.3076/

On a RPi 3 you have to change the GPU core frequency to 250 MHz, otherwise the SPI clock has the wrong frequency. Do this by adding the following line to /boot/config.txt and reboot.

core_freq=250

**Comment by jtkDvlp** [comment]
Hi guys,

thank you for your replys. It seems to be an combination of both. 

@El-Mare set core_freq to 250 works (I would never thought of something like). 

@WoLpH I will test it and give feedback. I already though of that. I got an 5V 15A power supply, so I thought it should be enough. But I have to apply the power cabel every maybe 80-100 cm, do not thought about that :-$ A tend from white to red is caused by long cabel low power and the red led needs less than the other XD In a few days I will test and give feedback.

**Comment by WoLpH** [comment]
It's easy enough to test with a multimeter usually, simply look at the voltage along several points. If it deviates from 5v too much it will cause problems.

Also, testing with just 20 leds or so can be an easy test :)
Voltage drop is definitely a large factor in many cases: https://www.rapidtables.com/calc/wire/voltage-drop-calculator.html#calculator

**Comment by jtkDvlp** [comment]
Yeah that´s right. I already tested it with my multimeter. I also tested it with the leds. I probably do not even need extra power after x leds. It seems my connectors for the corners are the problem. Their resistance is quite high.

Thank you for your help :+1:
