### ISSUE TITLE
random colors at parts of strip

### ISSUE THREAD

**Issue by droopified** [hyperion-project/hyperion#808]
i have been using this project for a while now and havnt had a real issue but i do notice that some sections flash different colors. i know that ground issues can cause this but i am not sure if it would cause the whole strip to do that instead of sections. not sure if its a specific color range causing it to glitch but after the scene changes colors that section works like normal. any advice?

**Comment by tpmodding** [comment]
you dont share any informations with us....how could we give you any advice?
