### ISSUE TITLE
Support for UTV007 grabber

### ISSUE THREAD

**Issue by jjkcharles** [hyperion-project/hyperion#811]
I'm trying to configure Hyperion with an external USB grabber but been facing error message when I try to test the grabber. I am following [this link](https://hyperion-project.org/wiki/II-V42L-Grabber-USB-Grabber) and bought an [UTV007 Grabber](https://www.ebay.com/itm/EasyCap-DC60-USB-Video-Capture-Card-Adapter-with-ChipSet-UTV-007-for-Win-7-8-10/264137432345?epid=28013314330&hash=item3d7fd15d19:g:07gAAOSw6S9cPFYU&frcectupt=true)

But, when I try to take a screenshot through Hyperial-v4l2 below is the message I get,
```
hyperion-v4l2:
	version   : V1.03.4 (brindosch-c750c41/dc6a602-1522918225
	build time: Apr  5 2018 01:57:25
V4L2GRABBER INFO: width=640 height=480
V4L2GRABBER ERROR: Only pixel formats UYVY, YUYV, and RGB32 are supported ERROR
```
Can you advise, how I can fix this?

**Comment by bennealon** [comment]
You need to supply some parameters, a working example for my setup, which is similar to your - would look like:

hyperion-v4l2 --width 640 --height 480 --screenshot --frame-decimator 2 --size-decimator 8 --crop-left 0 --crop-right 0 --crop-top 0 --crop-bottom 0

**Comment by jjkcharles** [comment]
@bennealon I did provide similar parameters when capturing screenshot, but just that I haven't mentioned it in the issue description.

Are you using the same USB Grabber that I have linked?

**Comment by bennealon** [comment]
Yes, its the generic EasyCap one referenced in the wiki, works perfectly with both Hyperion and the Config. Have you tried running HyperCon and following the instructions in the Wiki for grabbing a screenshot within there? That might be the best place to start, rather than doing it on the CLI.

**Comment by tpmodding** [comment]
Please use the Forum for such kind of Support. Thanks
