### ISSUE TITLE
is the support team here serious?

### ISSUE THREAD

**Issue by droopified** [hyperion-project/hyperion#813]
you reply saying we dont provide any information and then close the thread? how about giving us a little time to actually reply? i dont know what info you are looking for but i was hoping for a someone to say "i had a similar issue, did u try...".

**Comment by penfold42** [comment]
The forums are a better place for interactive “how do I” and general experience sharing.

https://hyperion-project.org/

This issue tracker is primarily for capturing enhancement requests and defects in Hyperion

**Comment by RickDB** [comment]
Please use the forum for discussions like @penfold42 suggested.
