### ISSUE TITLE
 hyperium says failed to patch optifine at the end of the installation what can I do? help me please I am new

### ISSUE THREAD

**Issue by BullyGamer24** [hyperion-project/hyperion#815]
when i try to install hyperium it tells me what i put in the title i am using mac help me please

**Comment by Paulchen-Panther** [comment]
optifine???

**Comment by tpmodding** [comment]
this is not the hyperium game, this is hyperion ambilight...

**Comment by Paulchen-Panther** [comment]
thanks @tpmodding
