### ISSUE TITLE
Kodicheck a bit buggy on leia

### ISSUE THREAD

**Issue by kyh3im** [hyperion-project/hyperion#816]
After pausing a video kodicheker doesn't turn off the led. Sometimes the effect is opposite, like it turns leds off but doesn't bring it on after hitting play button.

I assume it might be due to changes in JSON-RPC API/v9 that's been introduced in Leia

I'm using the latest stable OSMC on RPi3b+
I've tried the latest version from HyperCon and also pulled/built the latest version from github
```bash
$/usr/bin/hyperiond /etc/hyperion/hyperion.config.json
Hyperion Ambilight Deamon (12431)
	Version   : master (brindosch-c750c41/dc6a602-1522918225
	Build Time: May 14 2019 20:14:25
```

My hyperion.config.json: 
```JSON
	"xbmcVideoChecker" : 
	{
		"xbmcAddress" : "127.0.0.1",
		"xbmcTcpPort" : 9090,
		"grabVideo" : true,
		"grabPictures" : true,
		"grabAudio" : true,
		"grabMenu" : true,
		"grabPause" : true,
		"grabScreensaver" : false,
		"enable3DDetection" : false
	},
```

**Comment by RickDB** [comment]
Could you set Kodi to debug logging and post the output when the Kodichecker takes into effect (pausing / stop etc..), we have some version checks in the current Kodi addon so can apply needed fixes for Leia in specific if need be just need to know what they changed of course :)

**Comment by lsellens** [comment]
There was a change to add Player.OnResume
https://github.com/xbmc/xbmc/commit/5554edd9615ad0f01f2e87411627a2f5b08189ff#diff-776109f26a56c80bd8fe22555bedb6e2

**Comment by kyh3im** [comment]
I switched to debug mode so here my logs:

Kodi logs play/pause start at *2019-08-18 12:36:02.213 T:1915684400*
[kodi.logs.txt](https://github.com/hyperion-project/hyperion/files/3512876/kodi.logs.txt)


Logs for kodicheck: 
```KODICHECK INFO: switching to VIDEO mode
KODICHECK INFO: switching to PAUSE mode
KODICHECK INFO: switching to MENU mode
KODICHECK INFO: switching to VIDEO mode
KODICHECK INFO: switching to PAUSE mode
KODICHECK INFO: switching to MENU mode
```
But hyperion doesn't stop the effect in the PAUSE mode

**Comment by lsellens** [comment]
I fixed this and sent a pull request
https://github.com/hyperion-project/hyperion/pull/823

**Comment by kyh3im** [comment]
Thank you guys, everything works fine :)
