### ISSUE TITLE
Hyperion Flicker on Raspberry Pi 4

### ISSUE THREAD

**Issue by DerGary** [hyperion-project/hyperion#821]
Hello,

I upgraded my Raspberry pi 3 with a rasperry pi 4 and on the raspberry pi 3 my leds (apa102) work fine with hyperion on libreelec but on the raspberry pi 4 with the same config installed the newest version via hypercon I have the problem that all leds are flickering. I captured a video:

https://youtu.be/zkHjRDkIWUU

Here is my config:
[hyperion.config.json.txt](https://github.com/hyperion-project/hyperion/files/3417511/hyperion.config.json.txt)

Is there a Problem with the configuration or with hyperion in general on the raspberry pi 4?

Greetings
Gary

**Comment by penfold42** [comment]
What level shifter are you using ?

**Comment by DerGary** [comment]
@penfold42 What do you mean by level shifter?

**Comment by Paulchen-Panther** [comment]
https://learn.adafruit.com/neopixel-levelshifter

**Comment by DerGary** [comment]
Why would I need this? I'm using this setup: 

![pattern-conn - DE](https://user-images.githubusercontent.com/4302467/61654586-0689c780-acbd-11e9-8c9e-c63d467b53ff.png)

From this tutorial:
https://hyperion-project.org/threads/raspberry-pi-3-mediacenter-hyperion-ambilight-ohne-l%C3%B6ten.112/

So the LEDs have their own 5V power supply.
The whole setup works flawlessly on the pi3 but not on the pi4.

**Comment by tpmodding** [comment]
because sometimes the signal isnt strong enough, thats why he asked... we dont know how the pi4 works cause we dont own it...with a level shifter you are 100% on the safe side that the signal is strong enough and doesnt make problems...

**Comment by DerGary** [comment]
thank you for the clarification. I ordered one and will try it as soon as it arrives.

**Comment by DerGary** [comment]
I got the level shifter installed today and it fixed my flickering issues thanks very much. I now have another Issue but I will open another issue on github for that.
