### ISSUE TITLE
Hyperion Raspberry PI 4 4K h265 HDMI Signal drop

### ISSUE THREAD

**Issue by DerGary** [hyperion-project/hyperion#822]
Hello,

System:
Raspberry Pi 4
Libreelec 9.1.001 With Kodi 18.3 (Kernel 4.19.50)
Hyperion 1.03.4

I recently got my Raspberry Pi 4 and after getting it to work with my current ambilight, I now have the issue that I can't play 4K h265 content with hyperion running. When I do the HDMI Signal drops out and the TV gets no signal. I testet 1080p-h264, 1080p-h265 and 4K-h265 and the problem only appears with 4K encoded with h265. Strangly when the HDMI Signal is lost the Ambilight seems to work fine. When I disable hyperion the HDMI signal returns immediately.

I think there is a problem with Hyperion destroying the signal when its 4K. Can someone please look into this? I would be happy to provide further information when needed.

I made a short Video portraying the bug:

https://www.youtube.com/watch?v=obdolp8Anqc&feature=youtu.be

Greetings Gary

**Comment by tpmodding** [comment]
WE PROVIDE NO SUPPORT AT GITHUB!
All misleading issues will be closed without a announcement!

you allready opend a thread in the forum...will close here

**Comment by DerGary** [comment]
@tpmodding I created a thread at the forum [link](https://hyperion-project.org/threads/hyperion-raspberry-pi-4-4k-h265-hdmi-signal-drop.3675/) but it seems like the community is not as active on the forum as it is on github....

**Comment by tpmodding** [comment]
Only devs are active on github... i will do my best to help you
