### ISSUE TITLE
How to turn LEDs off when TV goes off

### ISSUE THREAD

**Issue by aliekiddo** [hyperion-project/hyperion#830]
I have gotten my install set up and it looks great, however I want the LEDs to yurn off when the TV is turned off. Right now the LEDs are picking up input from the Chromecast and I can see the background images when the TV is off.

A possible solution I am looking at is assigning a command to the TV remote power button.
I am trying to see if a modified script from a tutorial would work but it was not written for OpenElec. What is the check status command for OpenElec?

I still cannot post on the forum - It has been 2 weeks since I signed up and I cannot find any information about how to get permissions to post.

**Comment by tpmodding** [comment]
you can now post in the forum, we have problems with some spambots, currently registration is not active...

just 2 ideas:
1. as you said, IR-receiver at the rpi, and read the power on/off button from the remote
2.a relais which is connected to the usb port from your tv, which goes on and off with your TV...

**Comment by aliekiddo** [comment]
On the forum front if I log in it now says 
"You do not have permission to view this page or perform this action." on every page - I can't see anything on any page.

https://www.dropbox.com/s/jmvg1yia6ie0tkw/Screenshot%202020-01-13%2019.04.48.png?dl=0

I am trying to get a remote script to work but I cannot find any guides on how to do this for OpenElec.

I was going to try using this as a starting point:
['How to: turn Hyperion on/off using your TV remote' tutorial](http://blog.nadnerb.co.uk/?p=11)

`    #!/bin/sh
    SERVICE='hyperiond'
    if ps | grep -v grep | grep $SERVICE > /dev/null
    then
    killall hyperiond
    curl -v -H "Accept: application/json" -H "Content-type: application/json" -X POST -d '{"id":1,"jsonrpc":"2.0","method":"GUI.ShowNotification","params":{"title":"Hyperion","message":"Disabled","image":"/storage/hyperion/hyperion.png"}}' http://openelec.local:8080/jsonrpc
    else
    /storage/hyperion/bin/hyperiond.sh /storage/.config/hyperion.config.json </dev/null >/dev/null 2>&1 &
    curl -v -H "Accept: application/json" -H "Content-type: application/json" -X POST -d '{"id":1,"jsonrpc":"2.0","method":"GUI.ShowNotification","params":{"title":"Hyperion","message":"Enabled","image":"/storage/hyperion/hyperion.png"}}' http://openelec.local:8080/jsonrpc
    fi`

For the life of me I cannot find the code for how to check if Hyperion is running in OpenElec
I have also tried capturing the remote's IR from SSH but the command 'irw' returns nothing.

I have tried powering the HDMI splitter and HDMI to RCA via the TV USB but this does not turn off the LEDs, it just leaves them in their last (dimmer) state

**Comment by Paulchen-Panther** [comment]
@RickDB Could you please take a look at what's going on with his account? Thank you very much.

**Comment by aliekiddo** [comment]
I'm still having the same issue with the hyperion-project.org site saying I don't have permissions to view any pages. I have tried to use the 'Contact Us' in the footer (3 or 4 times over the last 3 weeks) 
initially asking what I needed to do to get permissions to post and then regarding not being able to view any pages whilst being logged in but I haven't gotten any response.

I don't even have the ability to close my account or edit my profile (as I don't want a site to be able to keep my information if I have no control over it)

I'd like to be able to take the original issue of how to turn the LED's on/off over there

**Comment by tpmodding** [comment]
@aliekiddo and now?

**Comment by aliekiddo** [comment]
Yes, much better :) Thank you @tpmodding 
I'll take this issue over to the forum
