### ISSUE TITLE
Web Interface crashes when saving nanoleaf

### ISSUE THREAD

**Issue by Sousanator** [hyperion-project/hyperion#835]
I'm running a fresh install of Raspbian Buster and used the docker image to install hyperion.ng.  I have the latest version (April 22 2020 v2 alpha 5)

I've tested phillipshue and have that working.  In a new instance I'm trying to add nanoleaf but whenever I hit save (under Configuration > LED Hardware) Hyperion reboots.  When it starts up again it immediately reboots... over and over.  I can't get back into the interface unless I reinstall the image again. 
![firefox_2020-04-23_01-46-42](https://user-images.githubusercontent.com/25991568/80064648-87a11400-8506-11ea-968f-fe504bc29aca.png)

I know my IP address and API key are correct as I'm using them in SmartThings.
I've tried going into Expert settings and reducing the number of LEDs but that didn't help either.  
I can't check the log since I can't get in the interface.
Anything else I can try?

**Comment by Lord-Grey** [comment]
@Sousanator Would you be able to connect to the RPi via ssh (e.g. via Putty) in general to execute hyperion via the command line in debug mode?

**Comment by Lord-Grey** [comment]
I assume it is related to issue https://github.com/hyperion-project/hyperion.ng/issues/673, but lets validate.

**Comment by Lord-Grey** [comment]
Additional question: What nanoleaf device did you configure Aurora or Canvas?

**Comment by Lord-Grey** [comment]
OK. I was able to reproduce the failure. I am looking for the root cause.

**Comment by Lord-Grey** [comment]
@Sousanator  The root cause is that the Nanoleaf-Code in PR https://github.com/hyperion-project/hyperion.ng/pull/712
overwrote the fix in https://github.com/hyperion-project/hyperion.ng/pull/698

In case you compile yourself, replace in LedDeviceNanoleaf.cpp the open method by the following code snippet:

```
int LedDeviceNanoleaf::open()
{
	int retval = -1;
	_deviceReady = false;

	if ( init(_devConfig) )
	{
		if ( !initNetwork() )
		{
			this->setInError( "UDP Network error!" );
		}
		else
		{
			if ( initLeds() )
			{
				_deviceReady = true;
				setEnable(true);
				retval = 0;
			}
		}
	}
	return retval;
}
```

After compilation, you should be able bringing up hyperion.ng again and enjoy your Nanoleaf.
I will check in the fix in the masterrepository.

**Comment by Sousanator** [comment]
I realize now I posted this in the wrong project (should be under hyperion.ng) but thanks for helping.

I was able to compile and install your change and this did fix the issue
Thanks! I now have my Aurora Nanoleaf working.  Hopefully this get fixed (again) in the next release
